- src/App.vue
Previously it wasn't possible to actually close the DevTools (unless you knew where the close button was).
Here is how it looks now:
Game changer 👯
> Allow VueQuery DevTools to be closed

- src/components/_global/BalTable/BalTable.vue
I noticed this behaviour on the homepage: (when scrolling mobile / small screen)
This looks like a regression? I added the z-index to the sticky class and it seems to solve it.
> Fix BalTable z-index issue when sticky

- src/views/Pool.vue
If the poolQuery fails we should redirect back to pools list. Ideally we should show a notification that the pool failed to load, but before we implement that we should get Pon to design some notifications (where they should appear and how they should look).
> Handle pool loading error

- src/components/_global/BalTable/BalTable.vue
- src/components/pages/pool/PoolActivitiesCard/Table.vue
- src/components/pages/pool/PoolBalancesCard.vue
- src/components/tables/PoolsTable.vue
Adds an initialState to BalTable so that we can set things like sortColumn/sortDirection when the table loads initially.
> Add initial state prop to BalTable

- package-lock.json
- package.json
This version has a bunch of non breaking changes and a fix for devtools resizing (great to have this working now)
> Chore: update vue-query dep to latest

- src/components/inputs/TokenSearchInput.vue
- Selecting ETH will now filter WETH when choosing ETH from the token filter modal
- Selecting ETH in the token filter modal should select WETH as the filtered token, make sure that WETH and only WETH pools show up in the table after
> update: selecting eth as a filtered token will instead filter on weth

- src/components/lists/TokenListItem.vue
- src/composables/useAccountBalances.ts
- Fixed a problem where USDC and other tokens were not being parsed with the correct decimals
- Changed the token filter modal to show dust amounts as < 0.0001 rather than just 0
- Make sure to load USDC into your wallet and check that the correct amount is being shown on the token modal. E.g. if you have 5 usdc in your wallet make sure that the modal shows 5 USDC and not 5e-13.
- Load up a token with a dust amount into your wallet, check that it shows < 0.0001 on the modal rather than just 0
> Fix USDC decimal parsing on balances. Show dust amounts as < 0.0001 if so

- src/components/_global/BalLineChart/BalLineChart.vue
**Testing Critera**
- No hand pointer should be visible when hovering over a line in the chart on desktop
> fix: remove cursor pointer from hovering over line in chart

- src/store/modules/web3.ts
- Commit the web3 loading state to true when changing chain or account so dependents can change without undefined errors
- Change between accounts and chains on metamask, the navbar should update to reflect changes (does the address change?)
> When changing the account via metamask, the navbar does not reflect this change

- src/components/_global/BalTable/BalTable.vue
Fixes the following compilation error:
> frontend-v2/src/components/_global/BalTable/BalTable.vue
>  237:16  error  Type of the default value for 'initialState' prop must be a function  vue/require-valid-default-prop
> [hotfix] require-valid-default-prop compilation

- src/lib/utils/date.ts
- src/lib/utils/liquidityMining/index.ts
As discussed with @markusbkoch its better to switch to UTC time when computing the diff.
> Liquidity Mining - Switch to using UTC time for time diff

- src/composables/useWeb3Watchers.ts
- Instead of re-calculating allowances and balances on all blocknative notify events, only do it on `txConfirmed` events
> Only recalculate balances and allowances on txConfirmed events

- src/components/forms/pool_actions/InvestForm.vue
Here we're writing a number into an array of strings if we click the "max" button on the invest form.
This causes an error when we try to calculate the price impact as we then try and call `parseUnits` (which only accepts strings) on this number. This then causes the InvestForm to disappear.
I've ensured that we convert this number to a string as a quick fix.
> UI-509 prevent writing a number into amounts

- src/components/_global/BalLineChart/BalLineChart.vue
- src/components/pages/pool/PoolChart.vue
- Turn off HODL state in pool chart by default
- Open pool page, check if HODL is off by default. Make sure that you can re-activate it though.
> update: turn off HODL line in pool chart by default

- src/components/_global/BalBtn/BalBtn.vue
- For the BalBtn disabled state, for both gradient and solid scenarios: it will become a greyed out button.
- You can verify the disabled state of the button by going into a Pool and on the invest widget select custom amounts. Zero out all the inputs and the button should be disabled along with the new grey state.
> update: blanket gray state for disabled buttons

- src/components/cards/TradeCard/TradePair.vue
Fixes #UI-469.
- On selection check if tokenIn/Out === tokenIn/Out (i.e. same token>token trade)
- If it does call handleSwitchTokens to flip tokenIn/Out
-
> Call handleSwitchTokens if tokenIn/Out === tokenIn/Out on selection.

- package-lock.json
- package.json
Fixes # .
- Temp fix. Subgraph for Kovan has been updated for Stable Pools but it doesn't seem to be handling them correctly as the tokens and tokensList arrays are showing as empty. This is causing the SOR balances multicall to fail. So the Kovan app is currently only returning V1 swaps.
- SOR in this version is filtering Stable pools from multicall.
-
> Change to SOR that is filtering Stable pool.

- src/services/gnosis/constants.ts
Gnosis is only supported on Mainnet/Rinkeby/xDai so I just default to Mainnet if it isn't the case.
> fix: gnosis contracts address

- package-lock.json
- package.json
- src/services/balancer/subgraph/entities/pools/index.ts
Fixes an issue where the Nth to Mth pools in the time travel query are not the same Nth to Mth in the current state query, in which case 24h volume is incorrectly returned.
> Missing past pools

- src/composables/trade/useSor.ts
- src/lib/config/docker.json
- src/lib/config/homestead.json
- src/lib/config/index.ts
- src/lib/config/kovan.json
- src/lib/config/polygon.json
- src/lib/config/rinkeby.json
- src/services/balancer/subgraph/client.ts
I've consolidated the subgraph urls so that they live in the relevant network config. The subgraph service can then pull them through the `ConfigService`.
As an aside, do we want to make the methods on the `ConfigService` static?
> refactor: store subgraph urls in network config json files

- src/components/navs/AppNav/AppNavSettings.vue
- src/components/popovers/TradeSettingsPopover.vue
- src/composables/useWeb3.ts
The "trade liquidity" UI is now hidden on any network where no address is provided for `ExchangeProxy`.
`useWeb3` has been refactored to use the `ConfigService`.
> Hide trade liquidity UI on networks where V1 isn't deployed

- src/pages/Home.vue
In the spirit of #436, this PR removes links to the V1 dashboard from networks where V1 isn't deployed.
> feat: hide links to V1 dashboard on networks where it isn't deployed

- src/components/cards/TradeCard/GasReimbursement.vue
Currently on any network where we aren't running the BAL4Gas program the trading page will crash.
I've added graceful failure for getting eligible assets to prevent this.
> Prevent GasReimbursement component crashing trading page on unreimbursed networks

- src/services/coingecko.ts
- src/services/coingecko/api/price.service.ts
- src/services/coingecko/coingecko.service.ts
We now query prices for tokens on Coingecko for whichever network we are connected to.
> Allow pulling token prices from chains other than Ethereum from CoinGecko

- src/components/cards/TradeCard/TradeCard.vue
- src/components/cards/TradeCardGP/TradeCardGP.vue
- src/components/forms/pool_actions/InvestForm.vue
- src/composables/useTokenLists.ts
- src/composables/useTokens2.ts
- src/constants/tokenlists.ts
- src/constants/tokens.ts
- src/lib/config/docker.json
- src/lib/config/homestead.json
- src/lib/config/index.ts
- src/lib/config/kovan.json
- src/lib/config/polygon.json
- src/lib/config/rinkeby.json
- src/store/modules/registry.ts
I've added a mapping in `tokenLists.ts` to allow us to choose a set of token lists depending on the network so that we can have a separate choice of tokenlists for Polygon, etc.
I've also added a small function to allow us to deduplicate some of the definitions in there.
> refactor: prep tokenlists definitions for multichain

- src/constants/initialTokens.json
- src/constants/injected.json
- src/lib/config/polygon.json
I'm trying to flush out any possible bugs and get a rough version of the frontend which allows trading on Polygon. We have contracts + subgraph deployed so all the tasks from here is frontend related.
Todo:
Bugs:
> Polygon MVP

- src/assets/css/global/typography.css
- src/components/navs/AppNav/AppNavAccountBtn.vue
- src/components/pages/pool/PoolBalancesCard.vue
Applies fix from #310 to `PoolBalancesCard`
> fix: remove times sign rendering of "x" in PoolBalanceCard

- src/lib/config/polygon.json
This isn't causing any issues but a double slash in the urls doesn't look great.
> chore: remove trailing slash from polygonscan url

- src/components/navs/AppNav/AppNavActions.vue
- src/composables/useWeb3.ts
Claiming only works on Mainnet for now and so other networks shouldn't show it.
For now, it's completely removed - but might get a nicer design from Pon.
> Disable/remove claim button on non Mainnet networks

- src/constants/initialTokens.json
We're currently pushing people towards DAI (a token that we have no liquidity for). This is also a non-checksummed address so we're missing the metadata from the tokenlist.
I've changed this to instead use WETH.
> fix: change initial output token on Polygon to WETH

- src/services/balancer/subgraph/service.ts
24h volume displayed in the UI is approximate, computed using a timetravel query that relies on the network's blocktime, which is lower on Polygon. Meaning we're currently underestimating volume by a factor of ~6
> add polygon blocktime

- src/components/forms/pool_actions/InvestForm.vue
- src/components/forms/pool_actions/WithdrawForm.vue
- src/components/pages/pool/PoolActionsCard/PoolActionsCard.vue
- src/composables/pools/useTokenApprovals.ts
- src/composables/trade/useSor.ts
- src/composables/trade/useTokenApproval.ts
- src/composables/useBlocknative.ts
- src/composables/useEthers.ts
- src/composables/useNotify.ts
- src/composables/useWeb3.ts
- Add a useEthers composable with simple tx listener function similar to our blocknative equivalent.
- If network is polygon handle tx confirmations with ethers tx listener.
This is a stop-gap solution until we role our own tx handler which is also needed to support the Gnosis integration.
> Handle tx events on polygon

- src/services/web3/web3.plugin.ts
Fixes the issue of no TradeCard when no wallet is connected.
> fix: create a fallback provider if connector does not give one

- package-lock.json
- package.json
- src/composables/useDarkMode.ts
Correctly store dark mode boolean as string in local storage so that os default is respected.
> Hotfix: dark mode default

- package-lock.json
- package.json
- src/composables/useTokensStore.ts
Having large / multiple tokenlists toggled is causing extremely slow page interaction speeds and freezing. This PR removes the setting of active lists via local storage so that anyone who refreshes the app will revert back to just the default list which  doesn't cause any page speed issues.
This is temporary fix whilst we work on a broader refactor that should fix this.
> Hotfix: slow page hack

- package-lock.json
- package.json
- src/App.vue
- src/services/balancer/subgraph/service.ts
- src/services/ipfs/ipfs.service.ts
- src/services/rpc-provider/rpc-provider.service.ts
- src/services/token-list/token-list.service.ts
- src/services/token/token.service.ts
- src/services/web3/useVueWeb3.ts
We were initiating a block number websocket connection every time useVueWeb3 was being imported. This only needs to be done once and was [already happening in the root component](https://github.com/balancer-labs/frontend-v2/blob/develop/src/App.vue#L57-L64) and the blockNumber was being stored and kept up to date in the vuex store.
This fix reverts to fetching the block number from the vuex store.
We could move the state into the composable later. But we need to be careful not to init listeners on every import.
> Hotfix: too many ws connections

- package-lock.json
- package.json
- src/composables/trade/useSor.ts
Inputs for the SOR manager were referencing the user's network config which, if disconnected, doesn't exist. We should be using the app network for those inputs.
> Hotfix: SOR manager inputs

- src/components/_global/BalTable/BalTable.vue
This fixes a bug where the sticky column has lost it's background on horizontal scroll.
This also introduces some subtle translucency behind the sticky column.
> pk Fixes the fully transparent sticky column bug

- src/composables/trade/useSor.ts
- src/lib/utils/balancer/helpers/sor/sorManager.ts
Change sorManager to only use SOR V1 functions when on supported network. Should fix Sentry issue thrown when attempting to fetch V1 supgraph data.
Uses isV1Supported from useVueWeb3() to determine support. 
Fixes #UI-652
> Added check for V1 support in sorManager.

- src/components/cards/TradeCard/TradeRoute.vue
Original work by @pkattera in #654
Fixes Trade Route layout issue.
Fixes #UI-654
While here, I also fixed a new layout issue introduced in dark mode where the triangles on each hop was becoming misaligned by 2px on each hop, because there's border on dark mode (but not in light mode).
Go to the Trade UI page and trade between two tokens (like WETH -> WBTC) and put in a super high amount, like 1000 WETH. This should display the trade route with multiple hops. Open the 'Uses V2 liquidity' accordion.
From this:
and this when no previous layout issue:
To this:
> Trade route fix

- src/components/forms/pool_actions/InvestForm.vue
- src/components/forms/pool_actions/WithdrawForm.vue
- src/components/forms/pool_actions/utils.ts
- src/components/navs/AppNav/AppNavActivityBtn/ActivityRows.vue
- src/components/navs/AppNav/AppNavActivityBtn/AppNavActivityBtn.vue
- src/components/navs/AppNav/AppNavClaimBtn.vue
- src/components/notifications/Notification.vue
- src/composables/pools/useTokenApprovals.ts
- src/composables/trade/useGnosis.ts
- src/composables/trade/useSor.ts
- src/composables/trade/useTokenApproval.ts
- src/composables/trade/useTokenApprovalGP.ts
- src/composables/useNotifications.ts
- src/composables/useNumbers.ts
- src/composables/useTransactions.ts
- src/locales/default.json
- src/services/pool/pool.helper.ts
Notification tweaks as requested by @pkattera 
1. "Clear all transactions" => "Clear all"
2. Recent transactions time limit - 7 days instead of 1 day.
3. Capitalize only the first letter for notifications.
4. Notification progress bar - green for success, red for failure, and yellow for pending.
5. Increase the size of the notification widget and the spacing between the close button.
6. For invest/withdraw - include pool weights.
7. Activity indicator stays as a spinning circle even when its the popover is opened.
8. Show final values on trades (currently works for Gnosis)
Others:
1. "Clear all" footer is hidden for now.
2. Added translations.
> Notification system tweaks

- package-lock.json
- package.json
WalletConnect is trying to push projects to upgrade to 1.5.1 as previous versions are suffering from latency issues due to high load. I've bumped us up to this version.
See: https://twitter.com/WalletConnect/status/1419999849068564505
Interestingly, there seems to be some features for connecting to a Gnosis Safe included in this but it doesn't seem to be functional (checked on some other sites as well).
Check that you can still make a transaction through Walletconnect
> build: update to @walletconnect/web3-provider@1.5.2

- src/composables/trade/useSor.ts
The `txHandler` function needs to be called prior to the success callback because the new behaviour after a successful trade is to reset the inputs (which causes the notifications to appear as `0` value). This fixes it.
> [Gnosis]: Fix notifications when using trades via Balancer

- package-lock.json
- package.json
- src/lib/utils/liquidityMining/MultiTokenLiquidityMining.json
Co-authored-by: bakamoto20 <85693860+bakamoto20@users.noreply.github.com>
Ballers vote link: https://snapshot.org/#/ballersvote.eth/proposal/QmTiBKhkWVxJU4v1y8nZhbZeYyf4ghNuCznAx6e8RSvLfW
None.
WMATIC/USDC/QI/BAL/MAI pool moved from T3 to T4. This now receives 1,000 BAL per week. 
WMATIC/USDC/WETH/BAL pool given an extra T3 slot, had a T4 slot removed. This now receives 7,500 BAL per week.
> Liquidity Mining, week 62

- src/components/_global/BalTable/BalTable.vue
- src/components/tables/LMTable/LMTable.vue
- src/composables/queries/usePoolsQuery.ts
- src/constants/queryKeys.ts
- src/pages/LiquidityMining.vue
- src/plugins/router.ts
This pull request introduces the liquidity mining table under a new route. Shows a breakdown of the distribution of tokens to each pool for that week and well as the totals and the fiat usd value.
On both polygon and ethereum environments, navigate to the `/liquidity-mining` route and verify that the table works and shows the correct info in regards to the distributions for that week. Can be found in `MultiTokenLiquidityMining.json`.
Verify the totals.
Verify mobile compatibility.
> UI 678 Liquidity mining table

- src/components/modals/TradePreviewModalGP.vue
- src/composables/trade/useGnosis.ts
- src/composables/trade/useSor.ts
- src/composables/trade/useTrading.ts
- src/locales/default.json
1. Show price update alert error if it shifts by 2% in the trade preview.
2. Fix a bug related to using the `trading` prop, added a new `confirming` prop (its used to wait for user wallet approval of the trade)
3. Fetch SOR pools on every block (the interval wasn't actually working properly) - thinking that every block is a better approach. This is just for Balancer trades.
4. Some cleanups relating to state reset (cleaning up errors/warnings)
> [Gnosis]: More UI Tweaks

- src/components/navs/AppNav/AppNavActivityBtn/AppNavActivityBtn.vue
- src/composables/useTransactions.ts
- src/lib/utils/index.ts
- src/locales/default.json
Added persistence to notifications by adding a version `version` prop to `lsGet` and `lsSet`.
> Persist transactions

- src/components/cards/TradeCardGP/TradeCardGP.vue
- src/components/modals/SelectTokenModal/SelectTokenModal.vue
- src/components/modals/TradePreviewModalGP.vue
- src/composables/trade/useGnosis.ts
- src/composables/trade/useTrading.ts
- src/providers/tokens.provider.ts
Various bug fixes from testing:
1. `FiatCurrency` enum typo.
2. Clear state after a trade.
3. Pass token address to `balanceFor` method
4. Update SOR when liquidity source changes
5. Disable loading indicator when the trade has a quote (it still fetches it in the background on every block)
Refactor:
1. Add a new "wrapUnwrap" to simplify logic (instead of doing "isBalancerTrade && !isWrapOrUnwrap"
> [Gnosis]: Various bug fixes

- src/constants/tokenlists.ts
Enabling the Coingecko token list atm currently breaks balance/allowance fetching. I believe this is a result of some bad tokens but would take quite a bit of investigation to know for sure. For now, this PR removes that list from the options.
> Disable Coingecko list for now

- src/composables/useTransactions.ts
- src/composables/useWeb3Watchers.ts
- src/locales/default.json
Adds support for transaction speed ups and cancellations
> Add support for transaction speed ups / cancellations

- src/composables/trade/useGnosis.ts
Following Gnosis team feedback, it was noted that the amount estimate shown upon trade confirmation does not include slippage/fees - this PR solves this.
> [Gnosis]: Show a better price estimate on transactions

- package-lock.json
- package.json
- src/services/rpc-provider/rpc-provider.service.ts
The alchemy provider that we're using for logging is not supported on polygon, this PR introduces a temporary fix for this exception.
> Hotfix 1.12.1

- package-lock.json
- package.json
- src/services/coingecko/api/price.service.ts
Fixes price fetching when no price information is available from coingecko. The registry refactor introduced a bug where by the prices map would return an empty object for a token it couldn't fetch the price for. Instead it shouldn't inject that token into the prices map at all.
> Hotfix 1.12.6

- package-lock.json
- package.json
- src/lib/config/polygon.json
The current maticvigil websocket rpc doesn't work correctly on polygon and therefore we were unable to track block number updates. This PR replaces maticvigil with an Alchemy websocket rpc for polygon.
> Hotfix 1.12.7

- package-lock.json
- package.json
- src/components/cards/TradeCard/TradeCard.vue
- src/components/cards/TradeCard/TradeRoute.vue
- src/components/modals/TradePreviewModal.vue
- src/composables/trade/useSor.ts
- src/composables/trade/useTrading.ts
- src/constants/tokenlists.ts
- src/constants/tokens.ts
- src/lib/utils/liquidityMining/index.ts
- src/pages/LiquidityMining.vue
- src/services/web3/useWeb3.ts
- src/services/web3/web3.plugin.ts
Cleans up references to chainId. We have a few exceptions being thrown in Sentry where chainId is missing. It's not easy to see exactly where this is happening so this PR is cleaning up all references. In particular, we should be using the `appNetworkConfig.chainId` everywhere except where it's a user action that explicitly needs to know the user's current chainId, for example when checking if they're on the wrong network.
> Hotfix 1.12.8

- src/composables/trade/useSor.ts
- src/lib/utils/balancer/helpers/sor/sorManager.ts
Small change to use to greater type safety of enums over strings for swap types.
> refactor: use enum over string for swapType selection

- src/lib/utils/liquidityMining/MultiTokenLiquidityMining.json
This marks the 13th week of liquidity mining on Balancer v2. The Ballers propose the following changes which will go into effect 00:00 UTC Monday, August 16th, 2021.
Remove a Tier 4 slot from GRT/USDC 50/50. This pool will now receive 0 BAL per week.
Allocate a Tier 4 slot to GNO/WETH 80/20. This pool will now receive 1,000 BAL per week.
Remove a Tier 3 slot from AAVE/WETH 80/20. This pool will now receive 10,000 BAL per week.
Allocate a Tier 3 slot to WstETH/WETH stable pool. This pool will now receive 2,500 BAL per week.
There are no changes to Polygon’s Liquidity Mining this week.
> Liquidity Mining, week 64

- src/lib/config/homestead.json
- src/providers/tokens.provider.ts
Coingecko doesn't support price queries for wstETH so I've made a quick hacky fix to just return a scaled version of the stETH price.
I realise this is ugly as sin.
> feat: show prices for wstETH

- src/services/balancer/subgraph/entities/pools/query.ts
- src/services/balancer/subgraph/types.ts
The priceRate attribute is breaking polygon subgraph requests. This PR conditionally includes that attribute in requests based on supported networks.
> Make priceRate conditional on network

- src/composables/queries/useTokenPricesQuery.ts
- src/lib/utils/balancer/price.ts
- src/providers/tokens.provider.ts
Inject wstEth price into prices map rather than in the priceFor helper function.
> Fix wstEth price injection

- package-lock.json
- package.json
- src/composables/trade/useSor.ts
When trade output tokens are being wrapped in the background we need to account for the now wrapped token value in the price impact calculations.
> Hotfix 1.13.6

- .github/workflows/cache.yml
Users have consistently run into issues where cached versions of the site are loaded and have to hard refresh to fix bugs. This adds a github action that waits on a new vercel deployment and then purges the cloudflare cache.
This is hard to test locally
> Purge cloudflare cache after vercel deployment

- package-lock.json
- package.json
- src/lib/utils/balancer/lido.ts
If stETH address isn't set in config it can't be a stETH trade.
> Hotfix 1.13.7

- package-lock.json
- package.json
- src/services/pool/calculator/stable.ts
Fixes price impact calculation for withdrawals in all non-metastable pools. There is an issue with how to scale balance inputs for the SOR. For metastable pools it needs to scale all tokens to 18 decimals, for everything else it needs to be scaled to the token decimals. We will need to refactor how all this works so it's consistent.
> Hotfix 1.13.8

- src/components/_global/icons/IntercomIcon.vue
- src/components/btns/DarkModeToggle.vue
- src/components/btns/IntercomToggle.vue
New script setup vue syntax doesn't work in production, we'll probably need to update some package versions. For now I'm reverting to the old setup function in the one component where I used the new syntax.
> Revert to setup function

- src/components/navs/AppNav/AppNavSettings.vue
Initial hotfix hid the Gnosis toggle everywhere, including the staging apps. This PR allows it on apps with APP_ENV set to `staging`
> Show Gnosis toggle on staging apps

- src/components/cards/TradeCardGP/TradeCardGP.vue
- src/components/modals/TradePreviewModalGP.vue
- src/composables/trade/useGnosis.ts
- src/composables/trade/useSor.ts
- src/composables/trade/useTrading.ts
- src/locales/default.json
- src/services/gnosis/error.ts
- src/services/gnosis/operator.service.ts
Adds support for submission errors (could come from MetaMask/SOR/Gnosis API).
Here is an example of a user rejection of a tx:
EIP 1559 error (using Ledger):
Note - currently it does not work for approvals.
> [Gnosis]: Add support for error messages

- package-lock.json
- package.json
- src/services/coingecko/api/price.service.ts
There have been reports on Discord of the pool returns charts looking off. Seems to have originated in 1.14.3
> Pool returns charts

- src/components/images/Avatar.vue
- src/components/navs/AppNav/AppNavAccountBtn.vue
- src/components/navs/AppNav/AppNavSettings.vue
- src/composables/useWeb3Watchers.ts
- src/services/web3/useWeb3.ts
If the user's wallet is connected to a network that we don't have a config for a few bugs existed:
- The warning and request to switch network banner didn't appear
- The user's account btn in the nav disappeared.
This PR fixes these bugs.
> Fix unsupported network bugs

- src/components/navs/AppNav/AppNavSettings.vue
Langer reported strange behavior with the trade switch (being visible on Polygon deployment). This fix replaces the `chainId` check to the app network one instead of the user one.
> Fix trade interface switch

- package-lock.json
- package.json
- src/services/claim.ts
Fleek has been having stability issues. We now have a copy of the liquidity mining manifest ("snapshot") on GitHub. [claim.balancer.fi](claim.balancer.fi) was updated last week to use that instead of fleek. This does the same for the app's UI.
> Hotfix: get LM manifest from GitHub

- src/services/balancer/subgraph/entities/pools/query.ts
This PR removes the patch around the Polygon subgraph not returning `pricesRates` which resulted in the main page blowing up as this issue with the subgraph has been fixed.
Check that pools load on main page of Polygon app
> Remove patch for Polygon subgraph not returning pricerates

- package-lock.json
- package.json
- src/lib/config/arbitrum.json
Adds a public rpc connection for Arbitrum to allow users to add it to Metamask
Check that "Switch Network" button in banner works in situations where Metamask doesn't have the Arbitrum network details.
> Hotfix: add Arbitrum public rpc

- package-lock.json
- package.json
- src/services/balancer/subgraph/types.ts
- src/services/pool/calculator/stable.ts
The subgraph returns nulls for stable pool price rates however the frontend is expecting to get undefined. This means that null price rates were slipping through and blowing up the maths.
Attempt to join/exit a stable pool. (just being able to add an input is enough)
> Hotfix: Properly handle null price rates in stable pool maths

- package-lock.json
- package.json
- src/services/balancer/subgraph/types.ts
- src/services/pool/calculator/stable.ts
- src/services/web3/connectors/portis/portis.connector.ts
> Hotfix 1.17.4

- src/lib/utils/liquidityMining/MultiTokenLiquidityMining.json
- Turned 2xTier 2 slots into the "Flexible Bal Allocation" - 10k BAL / week to be allocated as per the proposal which passed last weekend. 
- Reduced UMA/USDC, DPI/WBTC/WETH, MATIC/WETH to 500 BAL/week (flexible BAL) from Tier 4. 
- Reduced YFI/WETH from Tier 3 to Tier 4. 
- Added new LDO/WETH pool to Tier 4. 
- Added Tier 3 & Tier 4 slot for BAL/WETH 60/40 on Arbitrum.
- Added 2,500 BAL/week (flexible BAL) to BTC/WETH/USDC on Arbitrum. 
- Added 3,000 BAL/week (flexible BAL) to USDC/WETH. 
- Added 3,000 BAL/week (flexible BAL) to USDT/WETH.
> Liquidity Mining, week 67

- src/constants/tokens.ts
Fixes Arbitrum and Polygon not having a set value for the ETH key in the AddressMap resulting in broken link when clicking "Wrap ETH into WETH" on invest page. (https://arbitrum.balancer.fi/#/trade/undefined/0x82aF49447D8a07e3bd95BD0d56f35241523fBab1)
Click "Wrap ETH into WETH" on invest page and see that ETH is selected in trade card
> fix: add missing ETH keys to AddressMap

- src/App.vue
- src/locales/default.json
- src/providers/tokens.provider.ts
Adds error alerts for token balances/allowances - these are considered pretty major (can't really trade) which is why they are "app level" alerts. (obviously these will only be shown when a wallet is connected)
Here's how it looks:
> Token balances/allowances error alerts

- package-lock.json
Just getting rid of these annoying errors:
```
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
```
> chore: update caniuse-lite

- src/assets/css/global/typography.css
- src/components/_global/BalTable/BalTable.vue
- src/components/_global/BalTextInput/BalTextInput.vue
- src/components/cards/TradeCard/GasReimbursement.vue
- src/components/cards/TradeCard/TradePair.vue
- src/components/cards/TradeCard/TradeRoute.vue
- src/components/cards/TradeCardGP/TradeCardGP.vue
- src/components/cards/TradeCardGP/TradePairGP.vue
- src/components/forms/AppSlippageForm.vue
- src/components/forms/pool_actions/InvestForm.vue
- src/components/forms/pool_actions/shared/FormTypeToggle.vue
- src/components/heros/AppHero.vue
- src/components/lists/TokenListItem.vue
- src/components/modals/TradePreviewModal.vue
- src/components/modals/TradePreviewModalGP.vue
- src/components/navs/AppNav/AppNavClaimBtn.vue
- src/components/pages/pool/PoolActivitiesCard/Table.vue
- src/components/pages/pool/PoolBalancesCard.vue
- src/components/pages/pool/PoolStatCards.vue
- src/components/tables/LMTable/LMTable.vue
- src/components/tables/PoolsTable/PoolsTable.vue
- src/components/tables/PoolsTable/TokenPills/WeightedTokenPill.vue
- src/components/tooltips/LiquidityMiningTooltip.vue
- src/composables/trade/useTrading.ts
- src/pages/LiquidityMining.vue
- src/pages/Pool.vue
Pon requested that we use the tabular (monospaced) for all numbers. I have tried to cover it all, hopefully I haven't missed :)
> feat: add `font-numeric` to all numeric usages

- package-lock.json
- src/composables/usePool.ts
- src/constants/pools.ts
- src/lib/utils/balancer/price.ts
- src/locales/default.json
- src/services/balancer/contracts/contracts/vault.ts
- src/services/balancer/subgraph/types.ts
Adds a whitelisted InvestmentPool to the UI + updates relevant checks to treat `InvestmentPools` as `WeightedPools` as they use the same underlying maths.
Check that you can access the pool `0x4fd63966879300cafafbb35d157dc5229278ed23000100000000000000000169` on Kovan.
> Add Investment pool support

- src/lib/utils/liquidityMining/MultiTokenLiquidityMining.json
ETHEREUM CHANGES
- Introduced dual incentives on eth for VITA/WETH - 80/20, VITA/WETH - 50/50 pools. They will receive 140 BAL/week each, and 2,350 VITA/week each. 
- No other changes.
POLYGON CHANGES
- No changes.
ARBITRUM CHANGES
- No changes.
> Liquidity Mining, week 68

- package-lock.json
- package.json
- src/components/navs/AppNav/AppNavClaimBtn.vue
We're having some issues with the underlying dataset used to compute LM estimates on Arbitrum. This hides the estimates on the frontend until we can fix that. 
Version bump assumes this will be merged after #804
> Hide LM estimate on Arbitrum

- src/components/cards/TradeCardGP/TradeCardGP.vue
- src/components/forms/pool_actions/InvestForm.vue
- src/components/inputs/TokenSearchInput.vue
- src/composables/usePool.ts
- src/constants/tokens.ts
Our links to wrap ETH/MATIC were broken on a couple of networks. This was stemming from us using a parallel mapping in the `TOKENS.ADDRESSMAP` causing some confusion. I've changed most references to this to rely on the `appNetworkConfig` directly instead.
This mapping remains as we need it to get the BAL address in a couple of places. I'd be inclined to move this to the config json file as well though. Thoughts on this?
Go to a MATIC/WETH pool on each network and click the "Wrap ETH into WETH" button. Check that correct tokens are selected in the trade UI.
> Fix links sending users to wrap native assets

- package-lock.json
- package.json
- src/constants/tokens.ts
Add ChainMap entry for the Indexed Finance NDX token, mapping its Arbitrum address to its Ethereum address:
0xB965029343D55189c25a7f3e0c9394DC0F5D41b1 -> 0x86772b1409b61c639EaAc9Ba0AcfBb6E238e5F83
The address pairing used above can be found in Arbitrum's official token list: https://bridge.arbitrum.io/token-list-42161.json
> Hotfix: Add mapping for NDX token price on Arbitrum

- src/components/_global/BalAsset/BalAssetSet.vue
- src/components/tables/PoolsTable/TokenPills/HiddenTokensPills.vue
- src/components/tables/PoolsTable/TokenPills/TokenPills.vue
- src/locales/default.json
Adds support for displaying 8+ tokens - see design for reference https://www.figma.com/file/sGuETamvER4ifrs4VqnDxE/Investment-pools?node-id=11%3A2080
Note - I'm still waiting for Pon's tweaks for dark mode and how the stable pool pills handle this.
> Add support for 8+ tokens display

- src/lib/utils/liquidityMining/MultiTokenLiquidityMining.json
- Remove 2600 BAL from the Flexible BAL allocation from USDT/WETH 50/50. This pool will now receive 120 BAL per week.
- Remove 1500 BAL from the Flexible BAL allocation from USDC/WETH 50/50. This pool will now receive 1500 BAL per week. 
- Remove a Tier 3 slot from SNX/WETH – 50/50 & COMP/WETH - 50/50. Add a Tier 4 slot to SNX/WETH -50/50 & COMP/WETH – 50/50. These pools will now each receive 1,000 BAL per week. 
- Remove a Tier 4 slot from REN/WETH – 50/50 & YFI/WETH – 50/50. Allocate 500 BAL from the Flexible BAL allocation to each of REN/WETH – 50/50 & YFI/WETH – 50/50. These pools will now each receive 500 BAL per week. 
- Remove 500 BAL from the Flexible BAL allocation from DPI/WBTC/WETH – 33/33/33. This pool will now receive 0 BAL per week.
- Allocate 500 BAL from the Flexible BAL …
> Liquidity Mining, week 69

- src/components/tables/PoolsTable/TokenPills/TokenPills.vue
Fixes an issue with token pills being broken, just needed a default.
> fix: token pill rendering in LMTable

- package-lock.json
- package.json
- src/components/inputs/TokenInput/TokenInput.vue
TokenInput was preventing decimal inputs as part of the HTML number input validation. It requires the `step` attribute to be set to `any` to allow for decimals.
> Hotfix 1.20.1

- package-lock.json
- package.json
- src/components/forms/pool_actions/WithdrawForm.vue
With new TokenInput, because we hook into the amount update event for single asset withdrawals to set the other inputs to zero, when a user inputs a number it just uses that event handler and sets the amount to max again. It should allow for using the input amount if it's passed.
> Hotfix 1.20.2

- package-lock.json
- package.json
- src/services/balancer/subgraph/entities/pools/index.ts
If subgraph hasn't indexed the block we're querying at then return empty data rather than throwing.
Open on Arbitrum and see if pools load
> Prevent subgraph from blowing up app when it is behind.

- package-lock.json
- package.json
- src/composables/trade/useSor.ts
This hotfix removes some incorrect scaling which was resulting in us treating the gas fees for V2 as orders of magnitude greater than they are.
Check that trade ui correctly routes trades through V2.
> Hotfix 1.20.6

- src/lib/utils/liquidityMining/MultiTokenLiquidityMining.json
- Reduce USDC/WETH to 1,100 BAL/week. 
- Reduce VITA/WETH - 80/20 to 110 BAL/week, 2855 VITA/week
- Increase VITA/WETH - 50/50 to 170 BAL/week, 1845 VITA/week
- Remove USDC/USDT stablepool from Tier 3, this will now receive 0 BAL/week. Add USDC/USDT/DAI to Tier 3, this will now receive 2,500 BAL/week.
- Allocate 400 BAL/week from Flexible BAL allocation to PICKLE/WETH. This pool will also receive 1,023 PICKLE/week.
> Liquidity Mining week 70

- src/constants/pools.ts
Factory address needs to be lowercase; add other Investment Pool networks
Should see this pool with the proper type (Investment Pool):
0xe7b1d394f3b40abeaa0b64a545dbcf89da1ecb3f00010000000000000000009a
> Lowercase InvestmentPool factory; add factories for other networks

- src/composables/trade/useTrading.ts
Adds a "route" param that forces the trade router to go through it (currently its only "balancer").
Why is this needed?
LBPs sometimes link to our trade interface and with the upcoming Gnosis interface becoming the default, it's essential to somehow tell the interface to route the pair via Balancer. By adding the `route=balancer` the trade will now go through Balancer. 
I think this is a good solution for now, but probably not the best because the route will cause all other trades to go through Balancer. Perhaps we could have some JSON that has a list of tokens we route through Balancer, so when an LBP launches he adds a PR for it.
We could also have a banner telling the users that they should switch to Gnosis if they trade other pairs, etc.
Note - the intention here is not to switch a …
> [Gnosis]: Add "route" param to force the trade route

- package-lock.json
- package.json
- src/constants/tokens.ts
- src/lib/utils/liquidityMining/MultiTokenLiquidityMining.json
Pending Baller's vote https://snapshot.org/#/ballersvote.eth/proposal/QmcNcVz2JubjrX3DL1hL2cgoUZjCqWTK4rqQ8jETpvZWay
- Reduce USDC/WETH to 1,100 BAL/week. 
- Reduce VITA/WETH - 80/20 to 110 BAL/week, 2855 VITA/week
- Increase VITA/WETH - 50/50 to 170 BAL/week, 1845 VITA/week
- Remove USDC/USDT stablepool from Tier 3, this will now receive 0 BAL/week. Add USDC/USDT/DAI to Tier 3, this will now receive 2,500 BAL/week.
- Allocate 400 BAL/week from Flexible BAL allocation to PICKLE/WETH. This pool will also receive 1,023 PICKLE/week.
> Liquidity Mining, week 70

- package-lock.json
- package.json
- src/composables/trade/useTokenApproval.ts
- src/providers/tokens.provider.ts
Approval checking for v1 swaps was using the approvalRequired function provided by the tokens provider incorrectly. This PR fixes the inputs and ensures that the token address passed to the function is always in the correct format when checking the allowance map.
> Hotfix 1.21.2

- src/lib/utils/liquidityMining/MultiTokenLiquidityMining.json
None proposed this week.
None proposed this week.
Marks first week with no tiers on Polygon, entirely flexible. 
Proposed changes: 
- Reduce USDC/WETH/BAL/MATIC from 7,500 BAL/week to 6,500 BAL/week.
- Reduce USDC/WETH/LINK/BAL/AAVE from 5,000 BAL/week to 4,500 BAL/week.
- Reduce USDC/WETH/WBTC from 2,500 BAL/week to 2,250 BAL/week. 
- Reduce WETH/LINK/BAL/AAVE from 2,500 BAL/week to 2,250 BAL/week. 
- Reduce WMATIC/MTA/WETH from 1,000 BAL/week to 450 BAL/week. 
- Reduce USDC/WETH/SNX/GRT from 1,000 BAL/week to 750 BAL/week.
- Reduce QI/WMATIC/USDC/MAI/BAL from 1,000 BAL/week to 300 BAL/week.
- Allocate 500 BAL/week & 750,000 TEL/week to TEL/BAL - 50/50. 
- Allocate 500 BAL/week & 750,000 TEL/week to TEL/BAL/USDC - 60/20/20.
- Allocate 1,250 BAL/week to WBTC/WETH 50/50.
- Allocate 1,250 …
> Liquidity Mining, week 71

- package-lock.json
- package.json
- src/components/cards/TradeCard/TradeCard.vue
- src/components/forms/AppSlippageForm.vue
- src/components/modals/TradePreviewModalGP.vue
- src/composables/trade/useTrading.ts
- src/composables/useSlippage.ts
- src/providers/user-settings.provider.ts
- src/store/modules/app.ts
The custom slippage input wouldn't let you input numbers that matched the preset options. e.g. you couldn't input 1.5 because on typing 1 it would select the preset 1% option then on typing 5 it would set the custom amount to 5%.
This PR refactors the AppSlippageForm component to allow for any type of custom input even if it matches a preset. I have also refactored where we store the user's slippage state into the user-settings provider instead of the Vuex store.
> Hotfix 1.22.1 - Fix custom slippage input

- src/components/cards/TradeCard/TradeRoute.vue
Fixes the issue of the `arbitrum` subdomain not being applied to links from a displayed trade route resulting in being redirected to mainnet.
Check that clicking a pool from a displayed route on the trade UI routes you to a valid pool on arbitrum.
> fix: add missing entry for Arbitrum in network prefix map

- package-lock.json
- package.json
- src/lib/utils/liquidityMining/MultiTokenLiquidityMining.json
Pending Ballers [vote](https://snapshot.org/#/ballersvote.eth/proposal/0x1a863469b799b5fa09bdc6f3000e51aba0c546b4d8fa4b108c87a5e336220e9c)
- Start incentives for BANK/WETH 80/20. 480 flexible BAL per week, 85,000 BANK per week. 
- Reduce LINK/WETH 80/20 to 420 flexible BAL per week.
- Reduce NDX/WETH 80/20 to 250 flexible BAL per week.
- Reduce MCB/WETH 60/40 to 875 MCB per week. BAL allocation remains the same.
- No proposed changes this week.
> Liquidity Mining, week 75

- package-lock.json
- package.json
- src/services/claim/MultiTokenClaim.json
PICKLE started using the merkle orchard for their distributions. This adds the relevant metadata so that LPs can claim PICKLE on the app's UI.
- Using https://apoorvlathey.com/impersonator/ with `0x0154d25120Ed20A516fE43991702e7463c5A6F6e` on Arbitrum should see ~22 PICKLE available to claim
> Add PICKLE to the claim UI

- package-lock.json
- package.json
- src/components/contextual/pages/pool/MyPoolBalancesCard.vue
We are displaying pool weights in the 'My pool balance' card on pool pages for stable pools. This PR hides them.
> Hotfix 1.26.1 - Hide weights for stable pools

- package-lock.json
- package.json
- src/constants/pools.ts
Add iROBOT InvestmentPool to allowlist for display on Invest UI. This pool is essentially an LBP, but it will outlast its gradual weight change and have public LPs, so it must be an InvestmentPool instead. It is very similar to the ROBOT/WETH smart pool on V1 and managed by the same entity.
> Hotfix: Add iROBOT InvestmentPool (mainnet) to allowlist

- package-lock.json
- package.json
- src/composables/trade/useGnosis.ts
If a wallet is disconnected and you enter values in the trade ui you get a very generic error message. This is due to the inputs for fetching the gnosis fee quote relying on the user's addresses. In this hotfix I am passing in the zero address if no wallet is connected.
> Hotfix - gnosis fee quote

- package-lock.json
- package.json
- src/lib/utils/balancer/helpers/sor/sorManager.ts
- Add flag to fetchPools to ensure only one fetch is done at once
This fixes issues when fetchPools is running slower than the block time which causes many fetches to be done at once causing CPU usage to spike and the browser to lag. Most noticeable on Kovan test network where it has 4s block times. 
- Run app
- View Trade page
- Ensure sor fetches are happening and that only one is being performed at a time, others should finish in <1s.
> Hotfix 1.26.4

- package-lock.json
- package.json
- src/pages/pool/_id.vue
In cases where pools have no initial liquidity we should not allow access to the invest/withdraw flow. This PR takes the first step towards this by hiding the pool actions card which links to the invest/withdraw flow from the pool page. The next step is to add some router middleware to prevent access to the invest/withdraw flow via the URL. That will come in a subsequent PR.
> Hotfix 1.26.5 - Hide pool actions if no init pool liquidity

- package-lock.json
- package.json
- src/composables/contextual/pool-transfers/usePoolTransfers.ts
- src/composables/contextual/pool-transfers/usePoolTransfersGuard.ts
- src/composables/usePool.ts
- src/pages/_layouts/PoolTransferLayout.vue
- src/pages/pool/invest.vue
- src/pages/pool/withdraw.vue
The PR prevents access to the invest/withdraw flow if any blocking criteria is met. To start with, the only thing that cause a redirect back to the pool page is if the pool has no initial liquidity.
> Hotfix 1.26.6 - Invest/withdraw flow guard

- src/components/navs/AppNav/AppNavSettings.vue
- src/locales/default.json
Adds an "Unsupported network" text with a red circle to indicate the network is unsupported. (For example Celo, BSC, Harmony, etc). Previously we were not showing anything.
> Fix unsupported networks on App Nav Settings

- src/composables/useNumbers.ts
Shows `< 0.0001` when numbers of the `token` preset are passed to `fNum`.
Without this fix, this row would basically show nothing since it will be treated as `0`.
Other examples:
> fix: show small number indication

- package-lock.json
- package.json
During the pkg upgrades for the SOR v2, a combination of vue/vue-compiler-sfc minor version upgrades caused issues with boolean props not being compiled properly in the new script setup syntax components. This PR locks vue/vue-compiler-sfc pkg versions for now until we can investigate why this happens.
> Fix vue template compiling

- src/constants/tokenlists.ts
Add Tracer token list to Arbitrum so that is easier for people to buy and sell pool tokens. I am in the process of setting up tokens.tracer.eth to match existing protocols but thought I'd open the PR to make sure this is allowed / all good.
> Add TCR token list

- src/services/web3/utils/helpers.ts
Metamask allows loading a block explorer when adding a new chain:
https://docs.metamask.io/guide/rpc-api.html#wallet-addethereumchain
This PR adds the block explorer for the new network to the payload.
Delete Polygon/Arbitrum from your metamask and then reload it from the app. Under "View all details" you should see the url.
> feat: add block explorer url to metamask when importing chain

- package-lock.json
- package.json
- src/components/cards/TradeCard/TradePair.vue
- src/components/cards/TradeCardGP/TradeCardGP.vue
If you input values to the trade interface too quickly, i.e. before the `trading.isLoading` flag is true then you get validation errors that don't reactively change when the trading data is ready. This is a temporary patch to prevent input before loading is finished.
At some point we need to refactor how this works. Ideally, you should be able to enter whatever you want while the data loads in the background, and once the data is ready it checks if the trade is valid again and presents the trade or errors.
> Hotfix 1.27.2 - Trade input validation patch

- package-lock.json
- package.json
- src/components/cards/TradeCard/TradePair.vue
- src/components/cards/TradeCardGP/TradeCardGP.vue
Previous hotfix caused trade inputs to disabled on input 🤦‍♂️
> Hotfix 1.27.3 - Revert previous hotfix

- package-lock.json
- package.json
- src/lib/utils/balancer/swapper.ts
Prepending 0x to a toHexString string seems to result in a double 0x0x... this PR removes that prepending for transaction values.
> Hotfix 1.27.4 - Fix ETH trades

- src/components/cards/TradeCard/TradePair.vue
- src/components/cards/TradeCardGP/TradeCardGP.vue
This is a follow to https://github.com/balancer-labs/frontend-v2/pull/1065
The problem was that Gnosis didn't really need this check since its "loading" state is more like "refreshing". For Balancer routed trades - this is a good solution.
> fix: trade input validation fix for Balancer routed trades

- src/components/_global/BalProgressBar/BalProgressBar.vue
- src/components/cards/TradeCard/TradeCard.vue
- src/components/cards/TradeCardGP/TradeCardGP.vue
- src/components/forms/pool_actions/InvestForm/composables/useInvestMath.ts
- src/components/forms/pool_actions/WithdrawForm/WithdrawForm.vue
- src/components/inputs/TokenInput/TokenInput.vue
- src/constants/queryKeys.ts
- src/constants/transactions.ts
- src/lib/config/arbitrum.json
- src/lib/config/docker.json
- src/lib/config/homestead.json
- src/lib/config/index.ts
- src/lib/config/kovan.json
- src/lib/config/polygon.json
- src/lib/config/rinkeby.json
- src/lib/config/test.json
- src/locales/default.json
- src/providers/tokens.provider.ts
- src/services/pool/calculator/calculator.sevice.ts
- src/types/TokenList.ts
Adds a little buffer for the progress bar to accommodate for a recommended minimum gas fee along with a warning.
Added a new `minTransactionBuffer` to the `nativeAsset` config to have custom values for each network.
> feat: add progress bar buffer

- src/composables/queries/usePoolQuery.ts
Currently if someone deploys a `ManagedPool` they're unable to view it within the official frontend unless it's allowlisted. I've updated `usePoolQuery` so that we skip checking the allowlist if the user has connected with the address which deployed the pool.
We should potentially show a warning flagging up that other addresses won't be able to see this pool but I'll leave that up to you guys.
Impersonate an address which is the owner of a managed pool which is not on the allowlist and navigate to its page. It should load properly.
> Always allow pool owner to view their own pools

- package-lock.json
- package.json
- src/lib/utils/liquidityMining/MultiTokenLiquidityMining.json
- src/lib/utils/liquidityMining/index.ts
Pending Ballers vote
- Allocate 30,000 NOTE per week to NOTE/WETH 80/20. This pool will receive 0 BAL per week. 
- No proposed changes this week. 
- Reduce USDC/WETH/BAL/WMATIC 25/25/25/25 to 5,500 flexible BAL per week. 
- Reduce WETH/LINK/BAL/AAVE 25/25/25/25 to 650 flexible BAL per week. 
- Reduce USDC/WETH/SNX/GRT 25/25/25/25 to 350 flexible BAL per week. 
- Increase TUSD/USDC/DAI/USDT stablepool to 2,500 flexible BAL per week. This pool will also receive 55,000 TUSD per week and 27,500 WMATIC per week.
> Liquidity mining, week 77

- src/composables/queries/usePoolQuery.ts
`getAddress(account.value)` will throw if no wallet is connected. This PR adds a safety check to prevent this.
Load up a pool page without connecting a wallet. It should display correctly.
> fix: prevent pool ownership check throwing if no wallet is connected

- package-lock.json
- package.json
- src/pages/pool/_id.vue
We currently display a Copper card for every LBP pool page. This PR hard codes the Fei pool id so that this card doesn't appear on their pool page. Longer term solution needed to distinguish LBP platforms.
> Hotfix 1.28.1 - Hide Copper module for Fei pool

- src/components/cards/TrendingPairs/TrendingPairs.vue
The `tradePairSnapshots` are stored using UTC start of day, but the query is currently using the user's start of day. This results in the Trending Pairs card being blank for certain timezones.
> Fix tradePairSnapshots query, use UTC start of day

- src/components/_global/BalAsset/BalAssetSet.vue
When an asset is missing an icon, the rendering of the "My Wallet" component breaks down.
Apply a `display: flex` to the row so that it properly inlines the div component that gets rendered when the asset has no icon image.
Tested the fix with assets only with icons, a mixture, and all without. Every combination renders properly now.
> Fix asset row rendering issue when an asset is missing an icon

- package-lock.json
- package.json
- src/lib/utils/liquidityMining/MultiTokenLiquidityMining.json
Pending Ballers [vote](Link TBD)
* Allocate 500 flexible BAL per week to NOTE/WETH - 50/50. This pool will now receive 500 BAL per week and 30,000 NOTE per week. 
* Allocate 300 flexible BAL per week to NEXO/WETH - 80/20. This pool will now receive 300 BAL per week and 2,000 NEXO per week. 
* No proposed changes this week.
* Remove 300 flexible BAL per week from TCR/WETH - 80/20. This pool will now receive 700 BAL per week. 
* Remove 500 flexible BAL per week from BAL/WETH - 60/40. This pool will now receive 3,500 BAL per week.
> Liquidity Mining, week 78

- src/components/cards/CreatePool/InitialLiquidity.vue
- src/composables/pools/usePoolCreation.spec.ts
- src/composables/pools/usePoolCreation.ts
- src/locales/default.json
- src/services/balancer/pools/weighted-pool.service.spec.ts
Adds a toggle to the set liquidity step of create pool.  When toggled, if the user changes any of the token values all other
tokens are automatically set to the same value.
- Create a new pool. 
- On step 3, set the auto-optimise toggle to true
- Ensure other values are changing when any value is set
- Set auto-optimise toggle to false
- Ensure other values are not changing automatically.
> Add auto-optimize toggle to Create Pool

- src/components/cards/CreatePool/InitialLiquidity.vue
- src/components/cards/CreatePool/PreviewPoolModal.vue
- src/composables/pools/usePoolCreation.ts
- src/services/balancer/pools/weighted-pool.service.ts
Add the ability to invest in pools which take a wrapped native asset (such as WETH) using the native asset. 
I made it so the token address in global state is always kept as the wrapped asset to not cause state issues. On create the wrapped native asset is used, then on join it is changed to `AddressZero` and `value` is passed along with the transaction. 
- Go through create pool flow. Create a pool with WETH as an asset
- On initial balances page, switch WETH to ETH and set a value
- Complete creation and join pool with ETH
- Repeat the above with WETH to ensure that also works correctly.
> Add ability to initJoin WETH pools with ETH

- src/components/_global/BalActionSteps/BalActionSteps.vue
- src/components/_global/BalHorizSteps/BalHorizSteps.vue
- src/components/cards/CreatePool/ChooseWeights.vue
- src/components/cards/CreatePool/PreviewPool.vue
- src/composables/pools/usePoolCreation.ts
- src/pages/pool/create.vue
- src/services/balancer/pools/weighted-pool.service.spec.ts
- Remove error box when re-trying an action in action steps
- Sort tokens when preview is loaded 
- Token weights need to be in a specific order for create/join. Best to sort them on the preview page so that the pool name/symbol can be auto-generated in the correct order and so they don't re-order as the create button is clicked.
- Fix issue with a large amount of steps causing them to go off screen, lower space between them as there are more
- Don't allow proceeding with create with only one token set to 100%. 
- Rename PreviewPoolModal file because it's no longer a modal
- Go through create flow and ensure they are fixed
> Create pool small fixes

- package-lock.json
- package.json
- src/components/forms/pool_actions/InvestForm/composables/useInvestMath.ts
- src/components/forms/pool_actions/WithdrawForm/composables/useWithdrawMath.ts
If prices are missing the from validation check hasAmounts was failing because it was checking via the fiatTotal prop. This PR fixes the hasAmount check by checking if the fullAmounts array contains a non-zero value.
> Hotfix 1.29.2 - Fix invest/withdraw if missing prices

- package-lock.json
- package.json
- src/components/navs/AppNav/AppNavClaimBtn.vue
- src/composables/useTransactionErrors.ts
- src/locales/default.json
- src/services/claim/MultiTokenClaim.json
There is an issue with handling non 18 decimal tokens in the claims flow. This PR simply removes NOTE from the MultiTokenClaim json file so it doesn't appear in our UI.
Additionally, the PR includes a fix to handle `UNPREDICTABLE_GAS_LIMIT` errors more gracefully.
> Hotfix 1.29.3 - Remove NOTE from claims

- package-lock.json
- package.json
- src/composables/usePool.ts
Managed pools are showing that swaps are disabled when they aren't - blocking all non-proportional investments in Managed Pools.
Managed pools with swaps enabled should not show the "Trading disabled" banner:
0xccf5575570fac94cec733a58ff91bb3d073085c70002000000000000000000af (MetaFactory)
0x3b40d7d5ae25df2561944dd68b252016c4c7b2800001000000000000000000c2 (WSB)
> Hotfix 1.29.4: Correct logic for determining managed pool halted state

- src/services/coingecko/api/price.service.ts
The historical price end time is currently getting rounded to the start of day UTC, regardless of interval. Fix to not round the end time when the interval is `hourly`, this allows it to show up to date pricing on the 1 day chart.
Both of the screenshots below were taken at the same time:
Before:
After:
> Fix the 1 Day price chart

- src/components/cards/TrendingPairs/TrendingPairs.vue
For the TrendingPairs card, map WETH to ETH. It was a request from our users, but makes sense. Most people hold the native asset, not the wrapped asset. 
> TrendingPairs: Map WETH to ETH

- src/composables/queries/usePoolQuery.ts
- src/lib/abi/StaticATokenLM.json
- src/services/balancer/contracts/balancer-contracts.service.ts
- src/services/balancer/contracts/contracts/vault.ts
- src/services/balancer/subgraph/types.ts
Adds "unwrappedTokenAddress" to linearPool data.
> feat: add unwrapped token address to linearPools

- src/constants/tokenlists.ts
- src/providers/tokens.provider.ts
Currently when searching for tokens we only look in the currently active tokenlists. This hampers discoverability as it requires us to have listed a token in order for it to show up when the user is looking for it (without the user having to go out of their way to enable the 3rd party tokenlists first).
This PR means that as long as the token exists _somewhere_ in one of our tokenlists then the user will be able to find and inject it.
As a result of this I've removed some of the larger tokenlists as they included a lot of dross and weren't generally helpful. In future we want to add a semi-greyed-out state for tokens which are being loaded from external token lists until the user has injected them to show the distinction.
Search for the name of a token which is not included in the main …
> Search for tokens through all tokenlists

- package-lock.json
- package.json
- src/components/images/Avatar.vue
- src/components/navs/AppNav/AppNavAccountBtn.vue
- src/components/navs/AppNav/AppNavSettings.vue
- src/services/web3/web3.service.ts
I've made a [small package](https://github.com/TomAFrench/ens-avatar-resolver) to resolve the avatar attached to ENS names. This has been added to the web3 service alongside the ENS name lookup so that we can show the user's avatar nav bar.
Impersonate brantly.eth or nick.eth and check that you get a cryptopunk showing up in the nav bar.
> feat: add support for ENS avatar resolution

- package-lock.json
- package.json
- src/components/cards/TradeCard/TradeCard.vue
- src/components/cards/TradeCardGP/TradeCardGP.vue
We already show if the user has exceeded their balance in the input, there is no need to show an alert as well. Also, for some reason showing the alert seems to prevent the result of the trade being presented so the user is unable to test trade amounts and returns if they don't have the balance.
This PR removes the alerts but not the validation.
> Hotfix - remove no balance alert

- package-lock.json
- package.json
- src/components/forms/pool_actions/InvestForm/components/InvestFormTotals.vue
Fixes regression, price impact row in investment form used to have a red background when above 1%.
> Hotfix - price impact warning

- package-lock.json
- package.json
- src/pages/pool/_id.vue
Additional LBP projects are going to be adding pools soon, this PR temporarily hides the Copper module that links through to the Copper website for all LBPs until we can distinguish between projects via the subgraph.
> Hotfix - remove copper module

- package-lock.json
- package.json
- src/constants/tokenlists.ts
Switch to use raw github URLs for our tokenlists instead of the fleek storage API urls.
> Hotfix - use GitHub tokenlists

- src/services/aave/aave.service.ts
Previous implementation failed because it couldn't find the price of the wrappedToken
> Fix AAVE APR breakdown

- src/components/forms/pool_actions/InvestForm/components/InvestPreviewModal/components/InvestSummary.vue
- src/locales/default.json
Adds support boosted pools and third party breakdown.
Also, I've switched the icon to be consistent with what we currently have.
Star icon - Liquidity mining / third part rewards / other future rewards.
Info icon - Swap fees.
> Fix weekly yield calc for boosted pools

- package-lock.json
- package.json
- src/lib/config/arbitrum.json
- src/lib/config/homestead.json
- src/lib/config/kovan.json
- src/lib/config/polygon.json
- src/lib/config/rinkeby.json
- src/services/balancer/contracts/contracts/batch-relayer.ts
We didn't add batch relayer addresses for polygon or arbitrum which results in an exception being thrown in the console. This PR uses the zero address as a placeholder until those addresses are available.
> Hotfix - missing batch relayer address

- src/components/_global/BalVerticalSteps/BalVerticalSteps.vue
- src/components/cards/CreatePool/ChooseWeights.vue
- src/components/cards/CreatePool/InitialLiquidity.vue
- src/components/cards/CreatePool/PoolFees.vue
- src/components/cards/CreatePool/PoolSummary.vue
- src/components/cards/CreatePool/PreviewPool.vue
- src/components/cards/CreatePool/SimilarPools.vue
- src/pages/_layouts/FocusedLayout.vue
- src/pages/_layouts/index.ts
- src/plugins/router.ts
- Adds a focused layout modelled off PoolTransferLayout and nestles the pool creation UI inside it
- Match shadow/elevation of main card in pool creation with invest UI
- Match pool creation UI baseline headings
- Test that pool creation works fine on mobile and desktop inside the new layout
- Test that the shadows match invest UI
- Test that the headings of side modules and main card on pool creation have the same baseline heading
- [] I have performed a self-review of my own code
> Pool creation adjustments

- package-lock.json
- package.json
- src/components/tables/LMTable/LMTable.vue
The liquidity mining table duplicates the logic for the pool token pills. This PR copies the filtering of the StablePhantom BPT token from the pool tokens used on the home page.
> Hotfix - Remove BPT from table LM

- Dockerfile
Change the Dockerfile to use npm ci to install packages from package-lock.json instead of package.json for more safety for users. 
Tested with running `docker build .` and running the new Dockerfile and it loaded
> Use npm ci for Dockerfile

- package-lock.json
- package.json
- src/constants/pools.ts
LBPs from the new factory are showing up as unknown. I've added the new factory address to the list
These pools should display as expected for previous LBPs
https://app.balancer.fi/#/pool/0xf659abd8bc89590389e4f8c0959285677128232a00020000000000000000010c
https://app.balancer.fi/#/pool/0xc065798f227b49c150bcdc6cdc43149a12c4d75700020000000000000000010b
> Hotfix: Add zero protocol fee LBP factory address

- src/services/claim/MultiTokenClaim.json
Polygon started distributing from a new address.  This adds a second WMATIC entry for their new distribution channel
They say they will use this distributor for subsequent distributions.
> WMATIC switched between distributor addresses

- package-lock.json
- package.json
- src/lib/utils/liquidityMining/MultiTokenLiquidityMining.json
Pending [Baller Vote](https://snapshot.org/#/ballersvote.eth/proposal/0xf7f768c821fdaafe62907e309fbcf7340c61b05e81839dbfa416118adabc1e0d)
* Allocate 5000 BAL (one T2 slot) per week to the [bb-a-USD boosted pool](https://app.balancer.fi/#/pool/0x7b50775383d3d6f0215a8f290f2c9e2eebbeceb20000000000000000000000fe). This pool will now receive 5000 BAL per week.
* Remove 5000 BAL (one T2 slot) per week from BAL/WETH - 80/20. This pool will now receive 25000 BAL per week total.
* No proposed changes from the LM committee this week.
* 66.66 BAL from [Alchemist](https://vote.balancer.fi/#/proposal/0x00305705cf9c57b648729494c07224c5902bda5f1db5d2f95cf6ff510d7d850c) allocated to the [THX/USDC pool](https://polygon.balancer.fi/#/pool/0xb204bf10bc3a5435017d3db247f56da601dfe08a0002000000000000000000fe) …
> Liquidity Mining, week 82

- src/components/contextual/pages/pool/PoolBalancesCard/components/AssetRow.vue
The pool composition table abstracts the notion of wrapped Aave tokens away. We show the aToken logo and symbol in the rows for example, not the wrapped token's
The balance, however, currently displays the amount of **waTokens** held by the pool.
This PR proposes we convert that balance into the equivalent in aTokens, using the same logic used for the fiat value. As with the fiat value, this logic only works for the case of Aave, where the waToken<>aToken rate is the same as the waToken<>Token rate (ie, the Token<>aToken rate is 1).
Balances of aTokens in the bb-a-USD pool should show increased amounts, in line with the fiat value (eg 1 aUSDC = $1). Other pools should not be affected.
> Show aToken balance in pool composition table

- src/components/contextual/pages/pool/PoolTransactionsCard/BoostedPoolActivities/Table.vue
The pool transactions table in the bb-a-USD pool displays the symbols of the underlying linear pool's main tokens, but the amounts of the bb-a tokens.
Ideally we would be able to detect if the underlying operation invested/withdrew from the linear pool using aTokens or main tokens, but that would require implementing a much more sophisticated logic.
This PR proposes we simply remove the inconsistency, by displaying the bb-a-token symbols instead of the main underlying one.
Because the price of the bb-a-tokens isn't available, we compute the value based on the equivalent balance, computed from the bb-a-token priceRate and the price of the main token.
Pool transactions table in bb-a-USD pool should display the bb-a-DAI symbol where it now displays the DAI symbol. Same for USDC and USDT. …
> Show bb tokens in pool transactions table

- package-lock.json
- package.json
- src/components/contextual/pages/pool/PoolChart.vue
The Boosted pool chart is broken. After investigation, it looks like the first element in the chart history array had a zero value for liquidity which was causing a NaN value. This PR simply filters out history elements if their liquidity value is zero. This may not be the best fix, but it seems to fix the chart.
> Hotfix - boosted pool chart

- package-lock.json
- package.json
- src/composables/pools/usePoolCreation.ts
Curently tokens are being sorted using the string representation of their address, however checksum addresses results in this not always agreeing with sorting based on the numerical value (as is used on the actual blockchain).
I've removed the checksums to ensure that both sortings match.
Try to create a pool with RPL and rETH (just need to get metamask to appear, no need to send the tx).
This should succeed with this hotfix whereas it will fail in prod.
> Hotfix: fix pool creation form token sorting

- package-lock.json
- package.json
- src/components/contextual/pages/pool/PoolChart.vue
The pool chart for the bb-a-USD boosted pool is incorrect. As a temporary fix until we can fix the chart values, this PR hides the pool chart for this pool.
> Hotfix - hide boosted chart

- src/components/contextual/pages/pool/PoolStatCards.vue
- src/components/tooltips/LiquidityAPRTooltip.vue
- src/composables/useNumbers.ts
- src/constants/poolAPR.ts
When looking at the N/A pool symbol/name issue, I noticed the APRs for completed LBPs are huge and nonsensical (arising from very small balances). This is suppressed in some parts of the code, but not others. This fixes the APR display of completed LBPs (and other similar cases).
This pool has a huge APR:
0x053f3c35d557a76e9cb6c13a4842d9cfcddac8330002000000000000000000cd
It should display '-' after the fix: and not have a tooltip.
> Suppress nonsensical APRs

- package-lock.json
- package.json
- src/composables/watchers/useExploitWatcher.ts
- Disconnecting a wallet is currently broken because after disconnecting
the exploit watcher attempts to check against an empty account address
string. If account.value is not set, skip running the watcher.
- Connect a wallet to Balancer
- Disconnect wallet, ensure that wallet disconnects correctly.
> Hotfix: Don't run exploit watcher when no wallet is connected

- package-lock.json
- package.json
- src/lib/config/polygon.json
Polygon subgraph is failing. This points the polygon subgraph queries to the beta version of the subgraph where minimal app behaviour is working. Will need to point back to the main url after everything is stable again.2
Test that polygon app works 
None for this one
> tempfix: point polygon subgraph to balancer beta

- src/components/navs/AppNav/AppNavAlert.vue
Fixes the alert banner so that when you click the close button it doesn't also click the banner.
Currently if you click the cross on the boosted pools banner it takes you to the pool instead, ignoring the close button, which is not intended. 
Add a `!` to `if (!isMainnet.value) {` in App.vue to test on Kovan. 
Close the banner, ensure that it closes and doesn't redirect you to the boosted pool
> Fix close button on alert banner

- src/services/rpc-provider/__mocks__/rpc-provider.service.ts
- src/services/rpc-provider/rpc-provider.service.ts
- src/services/web3/web3.service.ts
We're currently trying to resolve ENS names using the provider for whichever network we're on even if ENS isn't deployed there. This PR maintains a mainnet provider for the purposes of querying ENS.
Load an address with an ENS name/avatar (nick.eth, brantly.eth) on Polygon/Arbitrum:
N/A
> Resolve ENS names/avatars on Polygon/Arbitrum

- package-lock.json
- package.json
- src/lib/utils/liquidityMining/MultiTokenLiquidityMining.json
Pending Ballers [vote](https://snapshot.org/#/ballersvote.eth/proposal/0x32e2372f1b8533ed6a3751a0c2d974b136f7a5d6e33cb8fe548ddffd92c6965a)
This marks the 38th week of liquidity mining on Balancer v2. The Liquidity Mining Committee proposes the following changes, which will go into effect 00:00 UTC Monday, January 31st, 2022.
No Changes this week
* Reduce 1250 BAL per week from USDC/TUSD/DAI/USDT pool. This pool will now receive 1250 BAL per week
* Add 1250 BAL per week to USDC/DAI/miMATIC/USDT pool. This pool will now receive 3650 BAL a week
No Changes this week
> Liquidity Mining, Week 88

- src/components/cards/CreatePool/ChooseWeights.vue
- src/components/forms/pool_actions/WithdrawForm/components/ProportionalWithdrawalInput.vue
- src/components/lists/TokenListItem.vue
- src/components/modals/TradePreviewModal.vue
- src/components/modals/TradePreviewModalGP.vue
- src/components/navs/AppNav/AppNavClaimBtn.vue
- src/components/tables/PoolsTable/PoolsTable.vue
- src/pages/liquidity-mining.vue
After merging #1321 I discovered there were a few templates where FNumFormats was used but not imported. This imports it to all files correctly. 
Test each page of the app and ensure there are no errors about missing FNumFormats in console.
> Add missing FNumFormat requires

- src/services/balancer/subgraph/entities/pools/index.ts
I forgot to update the excluded addresses path to the prod one.
> fix: use production path for excluded addresses for LM

- package-lock.json
- package.json
- src/components/cards/CreatePool/PoolFees.vue
- src/components/contextual/pages/pool/MyPoolBalancesCard.vue
- src/components/contextual/pages/pool/PoolChart.vue
- src/components/forms/AppSlippageForm.vue
- src/components/forms/pool_actions/WithdrawForm/components/ProportionalWithdrawalInput.vue
- src/components/inputs/TokenSelectInput/TokenSelectInput.vue
- src/components/tables/PoolsTable/TokenPills/TokenPills.vue
- src/composables/useNumbers.spec.ts
- src/composables/useNumbers.ts
- src/composables/usePool.ts
- src/pages/pool/_id.vue
- src/services/pool/pool.helper.ts
- style: 'unit' isn't supported by iOS mobile browsers (see https://sentry.io/share/issue/68705b2059ae4056a301b7ea9171acc3/)
- I updated the unit tests and it looks like 'percent' works exactly the same, so changed all instances of `style: 'unit', unit: 'percent'` to `style: percent`.
- Add a fix if 'NaN' is passed into fNum2, it should default to 0 to be equivalent to fNum. 
- Look through all changes and ensure that they are changed from `style: 'unit', unit: 'percent'` to just `style: 'percent'`
- Load website on mobile safari / chrome browser and ensure no errors occur.
> Change all style 'unit' to 'percent' in fNum2 usage

- src/components/animate/AnimatePresence.vue
- src/components/cards/CreatePool/ChooseWeights.vue
- src/pages/pool/create.vue
Right now the accordion which contains the Pool Summary and Token Prices cards for pool creation is animated based on a couple different factors and alerts showing etc, just so the accordion can always remain in place during layout changes. This is REALLY inefficient as I've come to realise and there was a super simple and obvious solution that I didn't realise.
TLDR: Just make the main content a relative element once its finished animating.
Also included: Cleanup the create.vue page and lessen the lines of code.
This test is mainly for mobile but:
1. Test the pool creation flow on desktop. Nothing should be different
2. Test the pool creation flow on mobile, the accordion should …
> Remove animation of BalAccordion for mobile on pool creation

- src/components/heros/AppHero.vue
- src/components/lists/TokenListItem.vue
- src/composables/useNumbers.spec.ts
- src/composables/useNumbers.ts
- src/pages/pool/_id.vue
fNum2 is currently returning -0 when the percent `-0.0000443` was passed into it and then rounded. This ensures that the return value from fNum2 is never -0
Also added a lot of other negative number tests and fixed fNum2 to return the same results as fNum for them. 
- Ensure that negative numbers work correctly across the app.
> Make fNum2 handle negative numbers correcetly, don't show -0

- src/components/forms/pool_actions/WithdrawForm/WithdrawForm.vue
- src/components/forms/pool_actions/WithdrawForm/composables/useWithdrawMath.ts
- src/components/forms/pool_actions/WithdrawForm/composables/useWithdrawalState.ts
- src/components/inputs/TokenInput/TokenInput.vue
- src/locales/default.json
- src/services/pool/calculator/weighted.ts
- src/types/index.ts
If the user trying to withdraw from a pool is a significant LP, i.e. they can withdraw more than 30% of the BPT in a pool, then currently the withdrawal form fails on selecting a single asset to withdraw.
This PR fixes the call to fetch the single asset max withdrawal by using the minimum of either the user's full balance or 30% of the BPT in the chosen token as the max value. It also adds a warning to explain why the maximum withdrawable amount is less than the user might be expecting.
This issue was less relevant before we launched pool creation. However, with pool creation live it's likely more users will run into this problem.
[Demo](https://www.loom.com/share/10c507663a504503990065c20f82acbe)
> Handle withdrawal abs max

- src/components/tables/PoolsTable/PoolsTable.vue
- src/composables/trade/useSor.ts
- src/composables/useNumbers.spec.ts
- src/composables/useNumbers.ts
- src/lib/config/kovan.json
- Remove decimals from tables 
- When trading, limit values to 6 significant digits
I originally changed `FNumFormats.token` to have 6 significant digits, but I'm not sure if any part of Balancer is supposed to have more and didn't want to accidentally break anything. 
- Look at the pools table and ensure values look correct.
- Perform a trade with various assets and ensure values look correct
Loom Demo: https://www.loom.com/share/80feb37d026641d6a459968285f1f84c
> Numbers Improvements - Remove Decimals, 6 Significant digits

- package-lock.json
- package.json
- src/services/claim/MultiTokenClaim.json
Ballers have taken over the process of seeding the merkle orchard for TUSD and PICKLE incentives. This adds their safe address to the list of distributors used by the claim UI.
> Add PICKLE, TUSD liquidity mining distributors

- package-lock.json
- package.json
- src/constants/pools.ts
Adds Arbitrum LBP factory addresses.
> Add Arbitrum factory addresses

- src/components/forms/pool_actions/MigrateForm/components/MigratePreviewModal/MigratePreviewModal.vue
- src/components/forms/pool_actions/MigrateForm/composables/useMigrateMath.ts
This refactor removes the previous patch I've done to "freeze" the preview screen by moving the `bptBalance` from being a `computed` to being a `ref`.
> minor refactor to useMigrateMath

- package-lock.json
- package.json
- src/components/contextual/pages/pool/PoolChart.vue
The array of values used to generate the pool chart seems to be coming out of the subgraph in the opposite order which caused a function guard to return 0 for all values. This PR reverses the order of the chart history so that they are in the same order as before.
> Fix pool chart display

- package-lock.json
- package.json
- src/services/pool/calculator/stable.ts
To support cases where the LP owns a majority of a pool and tries to withdraw a single asset some changes were made to the weighted pool math. This involved passing in a scaled BPT balance rather than a normalised value. Since the pool calculator acts as an adapter for the same function in the weighted & stable pool math, the scaling was missed for stable pools. This PR fixes scaling issues in the stable math class.
n/a
> Fix stable single asset withdrawals

- package-lock.json
- package.json
- src/components/contextual/pages/pool/PoolChart.vue
- src/services/balancer/subgraph/entities/poolSnapshots/query.ts
The `isPolygon` variable used to decide whether or not to request the `liquidity` attribute from the poolSnapshots subgraph entity was changed to a computed property but the `.value` attribute was not used.
n/a
> Fix boosted pool chart values

- src/components/cards/TradeCardGP/TradeCardGP.vue
Adds logic so that if a localStorage `alwaysShowRoutes` key is set, the Trade Route card can be seen on the main page even if the wallet doesn't have enough balances. No need to allow users to set this flag in the UI, this is just a nice to have that can be shared with pro users.
> always show trade route if storage key is set

- package-lock.json
- package.json
- src/services/gnosis/explorer.service.ts
Gnosis has moved their explorer domain to https://explorer.cow.fi, without redirection from the old domain, so all transaction links are just going to the explorer homepage at the moment. 
Example of old link: https://gnosis-protocol.io/orders/0xaea6aee87af7c77b96855aaa26459f89a2771a67e6c84836ce199d46a5202389ad66946538e4b03b1910dade713febb8b59cff606219c21c
Notice when you go to it it redirects to the new domain homepage
New link for same transaction: https://explorer.cow.fi/orders/0xaea6aee87af7c77b96855aaa26459f89a2771a67e6c84836ce199d46a5202389ad66946538e4b03b1910dade713febb8b59cff606219c21c
I couldn't find the development domains to replace them, not sure what they should be. 
- Perform a trade on Balancer
- Click the activities link in the top right
- Click the link on the transaction …
> Hotfix: Fix gnosis / cowswap explorer link

- src/App.vue
- src/composables/useAlerts.ts
Adds conditional to Alert schema, `rememberClose`, which uses local storage to remember if an alert was closed and prevents it from being shown again. This has then been applied to the boosted pools banner.
n/a
> Remember alert closure

- src/pages/_layouts/ContentLayout.vue
Fixes warnings thrown about deprecated CSS combinator in vue compiler.
> Fix css deep combinator deprecation warnings

- src/services/token/concerns/metadata.concern.ts
When fetching metadata for tokens in the registry, if the metadata can't be found we try to fetch it onchain. Unfortunately, the addresses passed to the onchain fetching function was passing all addresses we want metadata for and not just the subset of addresses we can't find data for in the tokenlists.
n/a
> Fix onchain meta data fetching

- src/components/cards/StatCard/StatCard.spec.ts
- src/components/cards/StatCard/StatCard.vue
- src/locales/default.json
- src/pages/claim.vue
- src/plugins/router.ts
Adds skeleton for claim page under dev/staging guard in routes. Will only be accessible via beta apps or locally.
n/a
> Tokenomics - Add skeleton claims page

- package-lock.json
- package.json
- src/components/_global/BalActionSteps/BalActionSteps.vue
- src/components/cards/CreatePool/ChooseWeights.vue
- src/components/cards/CreatePool/PreviewPool.vue
- src/composables/pools/usePoolCreation.ts
On polygon for some reason the blocknative library reflects the create transaction as confirmed before it actually is. The fix was to simply explicitly ask the transaction to go through 7 confirmations before proceeding to the fund step. 
Another issue was the name for the pool not being reflected or set correctly, adjusting a watcher should fix that.
Go through pool creation with no problems
None applicable, prod issue.
> Fix pool creation name issue and fund issue on polygon

- src/components/cards/PairPriceGraph/PairPriceGraph.vue
- src/components/cards/TradeCardGP/TradeCardGP.vue
- src/composables/trade/useTradeState.ts
- src/services/coingecko/api/price.service.ts
Loading the trade page with a fresh state (localstorage cleared etc) results in a bunch of console errors coming from the `PairPriceGraph` component's query being run before the initial trade state pair has been set. This PR adds a conditional `initialized` to the trade state and sets the pair price query enabled flag to wait for this conditional to be true.
n/a
> Fix console errors on trade page

- src/components/_global/BalActionSteps/BalActionSteps.vue
- src/components/forms/pool_actions/InvestForm/components/InvestPreviewModal/components/InvestActions.vue
- src/components/forms/pool_actions/WithdrawForm/components/WithdrawPreviewModal/components/WithdrawActions.vue
At the moment when an investment or withdrawal is successful the transition to the success state is really janky. This PR makes that transition a bit smoother for a nicer UX.
Old transition - https://www.loom.com/share/8a57ff0f1d674b0994c8d90dc63f0729
New transition - https://www.loom.com/share/8bdb07e2d5e8421ba3919744f68a68f1
> Smoother success transition

- src/pages/liquidity-mining.vue
Sort week numbers before selecting the last 3, to avoid issues like #1454
Even if the weeks in the JSON are not sorted, the /liquidity-mining page should still display them in the right order
> LM page improvement

- package-lock.json
- package.json
- src/components/forms/pool_actions/WithdrawForm/WithdrawForm.vue
- src/components/forms/pool_actions/WithdrawForm/composables/useWithdrawMath.ts
- Update SOR. Fixed limit in Linear Pool BPT>wrapped. This should allow bbausd exit with unwrapped aTokens via Relayer.
- SDK changed to make Relayer throw errors. SDK should not be handling error cases for consumer but will exit and throw early. Updated `useWithdrawMath` to catch error and set returnAmounts to 0 which will trigger relayer exit flow as before.
bbausd exit functionality should be same as before.
Should allow exit via Relayer - hard to test as Kovan pools are unbalanced. Tested by artifically forcing `getBatchSwap()` to throw error which triggers flow via `getBatchRelayerSwap()`.
> Update SOR. Changed to handle SDK Relayer error throwing.

- src/components/contextual/pages/claim/LegacyClaims.vue
- src/locales/default.json
- src/pages/claim.vue
Moves all the functionality from the navbar claims widget to the 'Legacy incentives' section of the new claim page.
> Add legacy claims to claim page

- src/components/_global/BalActionSteps/BalActionSteps.vue
Currently `<BalActionSteps>` doesn't support the list of actions being supplied to it, changing. This pull request changes that by allowing the component to receive a changing list of actions, if needed. Use cases where this is needed are where one of the steps (or all) rely on an async call while the component is mounted - for this, the component will show the loading flag and then when the action steps are ready: the steps.
This is mainly a code change. However this should be tested by re-testing the invest and other flows which rely on `<BalActionSteps>`
https://www.loom.com/share/ab22d8f2b6344135a64b9e99f832bd2f
> <BalActionSteps> to accept dynamic actions

- src/components/contextual/pages/vebal/LMVoting/LMVoting.vue
- Add a new method that calculates when the current vote period should end by finding next thursday and getting the UTC time of 00:00. 
- Tested by changing my system clock to various timezones and it always shows the same time remaining. 
- Open `/#/vebal` 
- Check the Voting Period Ends time, it should be the time remaining until 00:00 on next Thursday morning UTC time.
> Fix countdown timer to vote period end time

- package-lock.json
- package.json
- src/components/modals/TradePreviewModalGP.vue
Fixes token approvals actions not showing when trading via Gnosis. 
In #1415 in https://github.com/balancer-labs/frontend-v2/pull/1415/files#diff-9ba385aaaa1dd79048d5b04f24c55f3519dd75890e2770596abd620e7fa3dad7L680 The logic for approving tokens was changed from:
```
return props.trading.isBalancerTrade.value &&
props.trading.sor.sorReturn.value.isV1swap
? !tokenApproval.isUnlockedV1.value
: !tokenApproval.isUnlockedV2.value;
```
to
```
return (
props.trading.isBalancerTrade.value &&
!tokenApproval.isUnlockedV2.value
);
```
The bug was that when `props.trading.isBalancerTrade.value` is false, when doing a gnosis trade, in the old code it would return `!tokenApproval.isUnlockedV2.value` while in the new code it always returns false. 
This removes the isBalancerTrade check because we always …
> Hotfix: re-add token approval

- src/components/_global/BalLink/BalLink.vue
The current implementation wasn't very flexible. This PR allows for the BalLink component to also be a router-link and also disables the 'correct' way.
n/a
> Refactor BalLink

- src/components/_global/BalLoadingBlock/BalLoadingBlock.vue
This PR is to describe how the gauge voting flow can be tested and to collect feedback.
Pre-condition: To be able to vote you need to have veBAL by locking the BPT of the 80/20 pool.
First navigate to the [veBAL page in the kovan preview URL](https://beta-kovan-git-testing-voting-balancer.vercel.app/#/vebal).
Demo: [https://www.loom.com/share/67271b990989411d9c6b9e3848077772](https://www.loom.com/share/67271b990989411d9c6b9e3848077772)
> Gauge vote testing

- package-lock.json
- package.json
- src/constants/pools.ts
With the recent update to the subgraph to index the creation of ERC4626 Linear Pools, [this pool](https://polygon.balancer.fi/#/pool/0x1aafc31091d93c3ff003cff5d2d8f7ba2e7284250000000000000000000003b3) is displayed on the UI as "Unknown Pool Type". This PR will exclude this pool type from subgraph queries so as to prevent that.
> Add ERC4626Linear pool type to the exclusion list

- src/components/_global/BalHorizSteps/BalHorizSteps.vue
- src/components/_global/BalTooltip/BalTooltip.vue
- src/components/contextual/pages/vebal/LMVoting/GaugeVoteInfo.vue
- src/components/contextual/pages/vebal/LMVoting/GaugeVoteModal.vue
- src/components/contextual/pages/vebal/LMVoting/GaugesTable.vue
- src/components/contextual/stake/StakePreview.vue
- src/composables/useTime.ts
- src/lib/abi/GaugeController.json
- src/locales/default.json
- src/services/balancer/gauges/gauge-controller.decorator.ts
- Add new vue for Vote Information in the Gauge Voting table. 
- Open Gauge Voting table at `/#/vebal`
- Check that tooltip looks correct and has this week + next weeks votes + change in votes, and is the correct color. 
https://www.loom.com/share/19a19f4ecea34d4995326db09e15c883
> Change votes to show next period. Add tooltip with further info

- package-lock.json
- package.json
- src/services/balancer/contracts/contracts/balancer-minter.ts
The BalancerMinter contract was instantiating an ethers contract instance on all networks despite not having an address on any but Kovan for now. This instance also wasn't used at all so I have removed completely.
n/a
> Hotfix - console error

- src/components/contextual/pages/pools/StakedPoolsTable.vue
- src/components/contextual/pages/pools/UnstakedPoolsTable.vue
- src/providers/staking.provider.ts
Makes the staked/unstaked tables always visible.
Fixes tables not loading when user has no investments.
Pools should load when no investments are present.
Both tables should be visible and load appropriately.
https://www.loom.com/share/1095079deef44aab9a67b3b6e341574f
> Tokenomics- Staking tables always visible

- src/components/contextual/pages/pools/UnstakedPoolsTable.vue
- src/components/contextual/stake/StakePreview.vue
- src/components/contextual/stake/StakePreviewModal.vue
- src/components/heros/AppHero.vue
- src/components/tables/PoolsTable/PoolsTable.vue
- src/composables/staking/useStaking.ts
- src/pages/_layouts/DefaultLayout.vue
- src/providers/local/staking.provider.ts
- src/services/balancer/subgraph/types.ts
Fixes: #1559 & #1533 
- The 'My balance' number in 'Unstaked pools' table. It shouldn't include the staked balance for that pool.
- The 'My balancer investments' total value to include all staked balances.
More work could be done in the future to clean up here. We don't need to change the pool schema to include staked and unstaked balances. We also no longer need to know anything about the percentage of a pool that's staked an unstaked.
See related issues.
> Fix staking values

- src/composables/trade/useSor.ts
Fixes: #1527 
The `updateTradeAmounts` function is called whenever a new block is received. It re-calculates the swap value and updates the numbers in the trade view. It is currently calling `formatAmount` on these values before re-writing them to the page. This is causing issues because it re-formats the number the user just entered to only have 6 significant digits. 
This fix makes it only reformat + display the value that the user did not enter. 
@evgenyboxer This also means `formatFixed` with the deltas is not run on the number the user entered, does that seem fine to you? 
Refer to issue #1527 and attempt to replicate
- Load the Trade UI
- Perform a trade between any two assets. 
- Specify a large number or a number with a large number of decimals 
- Ensure that the number you are …
> Don't format numbers the user entered into trade

- package-lock.json
- package.json
- src/pages/claim.vue
Some data relied on tokenlists being loaded and was throwing console errors but not breaking the page. This PR waits for the global appLoading flag to be true before displaying some claim tables.
n/a
> Hotfix - claims loading states

- package-lock.json
- package.json
- src/pages/pool/_id.vue
It should not be possible to stake in a pool via our UI if the pool ID is not on the allowlist. This PR inforces that condition on the pool page.
n/a
> Hotfix - respect staking allowlist

- package-lock.json
- package.json
- src/components/forms/lock_actions/LockForm/components/LockPreviewModal/components/LockActions.vue
- src/composables/pools/useTokenApprovals.ts
- src/composables/useTokenApprovalActions.ts
Lock approvals should only approve the exact amount about to be locked. This PR refactors the token approval composables to allow this.
n/a
> Hotfix - lock approvals

- package-lock.json
- package.json
- src/components/tooltips/LiquidityAPRTooltip.vue
- src/lib/utils/liquidityMining/MultiTokenLiquidityMining.json
This is a hacky workaround to get an approximate APR of GNO/COW incentives to be displayed on the app for the COW/GNO and COW/WETH pools. The tokens will not be distributed via the merkle orchard. APRs computed with this hack assume all BPT have been staked.
> COW pool incentives APR

- package-lock.json
- package.json
- src/pages/claim.vue
- src/services/balancer/gauges/entities/gauges/query.ts
We had limited the liquidity gauge subgraph query to 20 which was cutting off some new gauges. This PR increases that limit to 999 for now and additionally hides reward tables for gauges where the connected account does not have rewards.
n/a
> Hotfix - claims missing rewards

- src/components/contextual/pages/vebal/MyVeBAL/components/MyVeBalCards.vue
- src/composables/useReturnRoute.ts
- src/pages/_layouts/FocusedLayout.vue
- src/pages/_layouts/PoolTransferLayout.vue
Fixes #1569 
- When navigating to the invest flow from the veBAL page, should redirect back to veBAL page on clicking to close
- Refactors handling of return route into it's own composable
n/a
> Fix return route for veBAL investment

- package-lock.json
- package.json
- src/components/_global/BalTable/BalTable.vue
- src/components/contextual/pages/vebal/LMVoting/GaugesTable.vue
- src/composables/useTime.ts
- src/lib/config/arbitrum.json
- src/lib/config/homestead.json
- src/lib/config/index.ts
- src/lib/config/kovan.json
- src/lib/config/polygon.json
- src/lib/config/rinkeby.json
- src/lib/config/test.json
- src/services/balancer/gauges/gauge-controller.decorator.ts
Because the total_weight value is not yet set gauge voting weights cannot be calculated using it. @markusbkoch realized we can use points_sum to calculate relative gauge weights in #1620. This PR improves upon that using points_sum and points_weight to calculate the relative weights of each gauge for this week and next, which should be correct for both this first week and future weeks. 
In Markus's PR he used a type_weight of 0.56 however when adding up the percentages this way they don't add up to a full 100%, so I'm not sure if that is correct or maybe all percents on mainnet should only add up to 56% total? The weight for each chain is expected to change so they all add up to 100% so I've added this value to the config file for each. 
- Visit the gauges page on mainnet Ethereum
- …
> Hotfix: Calculate gauge weights manually

- src/components/forms/pool_actions/InvestForm/InvestForm.vue
- src/components/forms/pool_actions/InvestForm/components/InvestPreviewModal/InvestPreviewModal.vue
- src/components/forms/pool_actions/InvestForm/components/InvestPreviewModal/components/InvestActions.vue
- src/components/forms/pool_actions/InvestForm/components/InvestPreviewModal/components/TokenAmounts.vue
- src/components/forms/pool_actions/InvestForm/composables/useInvestMath.ts
- src/components/forms/pool_actions/MigrateForm/composables/useMigrateMath.ts
- src/components/forms/pool_actions/WithdrawForm/composables/useWithdrawMath.ts
- src/constants/poolAPR.ts
- src/constants/poolLiquidity.ts
- src/locales/default.json
Adds a couple of warnings/errors for low liquidity pools - according to "quick wins" design here: https://www.figma.com/file/S5p30cxomV6gIyRZJMrvb3/Add-liquidity?node-id=802%3A6347
1. Added a "low liquidity" warning if the total liquidity is less than 50K.
2. Added "zero amount" assets to be shown in the preview screen (along with sorting them by their fiat value).
3. Added a new "rekt" error that disallows the user to continue.
> Invest flow tweaks for low liqudity protection

- src/composables/queries/useRelayerApprovalQuery.ts
- src/lib/utils/balancer/lido.ts
- src/services/balancer/contracts/contracts/balancer-minter.ts
I've come across a heisenbug on Polygon - in lido.ts the `isStETH` function is returning true for all trades, even though the value of `stEthAddress` is an empty string, so it should return false from the first if statement. When running development using Polygon chain the bug doesn't happen, it returns false from `isStETH` as expected. It may be something to do with source code compilation and `stEthAddress` being brought in from a closure instead of passed into the function. 
This bug causes the lidoRelayerApproval to trigger which calls useRelayerApproval with a relayer of an empty string (because the lido relayer is not set on Polygon). Which is causing this error: https://sentry.io/organizations/balancer-labs/issues/2862170362/?project=5725878&referrer=weekly-email because …
> Fix relayApproval and minter errors on Polygon

- package-lock.json
- package.json
- src/plugins/router.ts
The liquidity mining page was removed from all network apps but it should still exist on L2s. This PR re-introduced the LM page on L2s with a conditional route injection.
n/a
> Hotfix - Conditional LM page access

- package-lock.json
- package.json
- src/constants/voting-gauges.ts
LINK/WETH was described as 80/20 instead of 50/50
> Fix LINK/WETH description in voting page

- package-lock.json
- package.json
- src/services/balancer/gauges/gauge-controller.decorator.ts
Fixes a divide by zero error when the total weight for this week or next is still 0. Only happens at the very start of a new veBAL period, noticed today when refreshing just after UTC midnight. 
> Fix div by zero

- src/components/forms/lock_actions/LockForm/components/LockPreviewModal/LockPreviewModal.vue
- src/components/forms/lock_actions/LockForm/components/VeBalForm/VeBalForm.vue
Turns the lock preview modal to static so that you can trigger a refresh of the values.
> fix: turn lock preview modal to static

- package-lock.json
- package.json
- src/components/contextual/pages/pools/types.ts
- src/providers/local/staking/userUserStakingData.ts
- src/services/staking/staking-rewards.service.ts
In the current code, we're making the assumption that gaugeWorkingSupply ~= zeroBoostWorkingSupply which breaks down for larger LPs. This PR fixes the boost calculation.
n/a
> Fix boost calculation

- src/components/forms/pool_actions/InvestForm/components/InvestPreviewModal/components/TokenAmounts.vue
When investing the preview modal shows all the amounts - even when they are `0`. On pools with a large number of tokens this could lead to taking up too much space.
This PR introduces a compact mode and triggers it only when there is more 3 tokens that have `0` amount. Otherwise it will default to its original behaviour.
Here's how it looks with > 3 tokens that have `0` amounts.
There was also a small visual change (moved amounts and % to the right)
Here's the preserved behaviour (only 1 token with `0` amount)
> feat: add compact view for there are multiple tokens with zero amounts

- src/components/forms/lock_actions/UnlockForm/components/UnlockPreviewModal/UnlockPreviewModal.vue
- src/components/forms/lock_actions/UnlockForm/components/UnlockPreviewModal/components/UnlockActions.vue
- src/locales/default.json
When unlocking - it should be behave like the lock (refetch info + being static).
Fixes #1694
> fix: refetch lock preview + turn props to static

- package-lock.json
- package.json
- src/components/forms/pool_actions/InvestForm/components/InvestPreviewModal/components/TokenAmounts.vue
If the user tried to invest with all tokens the computed property `shouldShowCompactViewForZeroAmounts` would fail because there is no `zeroAmounts` property in the grouped amounts. This PR ensures that computed doesn't fail be defaulting to 0 in this case.
n/a
> Hotfix - fix no zero amounts bug

- package-lock.json
- package.json
- src/components/contextual/stake/StakePreview.vue
- src/locales/default.json
- src/services/balancer/contracts/contracts/gauge-controller.ts
- Forgot to change back the hardcoded timestamp for the gauge relative weights. 
- Fixes (again) the tooltips for stake preview.
- 
Proper APRs. 
Stake preview proper tooltips
> Hotfix - fix gauge relative weights

- package-lock.json
- package.json
- src/lib/utils/liquidityMining/MultiTokenLiquidityMining.json
The vote to decide on gauge unexpected behavior has reached quorum, meaning we can count on BAL being minted to cover the past 2 weeks of liquidity mining on Polygon and Arbitrum. 
We still have 3 days worth of incentives minted before the activation of the veBAL system. This PR extends the allocation of BAL defined on week 98, with the understanding that it will only be displayed on the frontend for 3 days (Apr18-Apr20).
/liquidity-mining route should display the same values as in week 98 (BAL only)
> Liquidity Mining, week 99

- package-lock.json
- package.json
- src/plugins/router.ts
#1722 adds LM data for Polygon and Arbitrum for week 99. However, that's only valid for 3 days. The /liquidity-mining page would indicate it would be valid for the entire week. This removes the route so that the only information displayed to users is the pools APRs, which is consistent.
/liquidity-mining route should redirect to main page of the app
> Remove /liquidity-mining route

- src/components/forms/lock_actions/LockForm/components/VeBalForm/VeBalForm.vue
Title. This is because on mobile and some platforms it allows you to bypass the date picker change event. So check on submit too.
Enter invalid lock end date on mobile, shouldn't allow you to get to the preview modal
n/a
> Disable lock preview from appearing if the lock end date is invalid

- package-lock.json
- package.json
- src/components/contextual/pages/vebal/LMVoting/GaugeVoteModal.vue
The vote form had a rule preventing an input of 0. This PR simply removes that validation rule.
Fixes: #1749
n/a
> Hotfix - Remove vote gt 0 rule

- package-lock.json
- package.json
- src/lib/abi/GaugeController.json
- src/services/balancer/gauges/gauge-controller.decorator.ts
Change fetching of gauge weights to use the function `gauge_relative_weight_write` which does a checkpoint on the gauge first to ensure it's weight is accurate for the week. Without the checkpoint weights aren't updated until a user votes on that specific gauge. 
View the veBAL gauges page, it should be similar to production but with many more of the gauge weights filled in instead of being 0. 
Production on left, local testing against mainnet on right
> Hotfix: Fetch gauge weights in a more accurate way

- src/components/contextual/pages/vebal/MyVeBAL/components/MyVeBalCards.vue
- src/locales/default.json
Adds secondary text / aligns behaviour with https://github.com/balancer-labs/frontend-v2/issues/1699
> feat: add secondary text to vebal cards

- src/components/forms/lock_actions/LockForm/composables/useLockEndDate.ts
It should be possible to lock for 365 when its a Thursday. This PR checks this condition and will allow to have a year lock.
Also - I've changed the date to UTC.
> fix: allow for a year lock when its Thursday

- src/components/contextual/pages/pool/StakingIncentivesCard/StakingIncentivesCard.vue
Loading condition broken for staking incentives card when wallet not connected.
When wallet not loaded, the card should not be visible
N/A
> fix: staking incentive card infinite loading bug

- package-lock.json
- package.json
- src/components/_global/BalTable/BalTable.vue
Table sorting was broken after an update to BalTable that allowed for pinning. This PR fixes the composable that computes unpinned data sorting.
n/a
> Hotfix - table sorting

- package-lock.json
- package.json
- src/components/contextual/pages/vebal/LMVoting/GaugesTable.vue
Following the BalTable refactor it looks like something broke the click.stop event handler when you use the :link prop BalTable. This PR removes that link prop from the GaugesTable so that the vote button opens the modal rather than redirecting to the pool page.
n/a
> Hotfix - table vote btn

- package-lock.json
- package.json
- src/services/gas-price/providers/blocknative.provider.spec.node.ts
- src/services/gas-price/providers/blocknative.provider.ts
The underflow errors we're seeing when transacting are because of Javascript floating point rounding issues when multiplying numbers together. Specifically when we're converting the gwei gas estimations to wei values. 
Added a test to reproduce the issue with certain gas values and a fix for it. 
Fixes #1687
> Fix underflow/overflow rounding errors when transacting

- src/pages/pool/_id.vue
We get a lot of requests for how to find the pool address on the website in the discord. Having to explain to nontechnical users that they need to take the first bit of the url and then paste that into a block explorer is not great, ideally we'd have a simple button like we do in the pool tokens table.
Please feel free to tweak CSS as it looks a teensy bit wonky.
Go to a pool page on each network and click the arrow button next to the pool title.
> Add explorer link for pools

- src/components/contextual/pages/vebal/MyVeBAL/MyVeBAL.vue
- src/components/contextual/pages/vebal/MyVeBAL/components/MyVeBalCards.vue
- src/locales/default.json
Speeds up loading of the "My veBAL" cards for unconnected wallets by hardcoding the pool name in the translation file.
> feat: remove loading for unconnected wallets

- package-lock.json
- package.json
- src/composables/trade/useSor.ts
On the trading screen when changing the input value sometimes the output was snapping to either 0 or the return value for the previous inputted amount. See: https://www.loom.com/share/639dc0d752d44fc7b65304704e41a2f2 /cc @zekraken-bot 
This is a race condition between:
- A new block comes in, which calls https://github.com/balancer-labs/frontend-v2/blob/develop/src/composables/trade/useSor.ts#L196
- While that async call is processing the user changes the value. This causes... 
- SOR recalculates the swap amount here: https://github.com/balancer-labs/frontend-v2/blob/develop/src/composables/trade/useSor.ts#L335 
- This sets the output value to the new amount. 
- Then the async call finishes and sets the value to the old sor return here: …
> Hotfix: Fix trade value snapping

- package-lock.json
- package.json
- src/components/contextual/pages/vebal/LMVoting/LMVoting.vue
- src/composables/queries/__mocks__/useGaugeVotesQuery.ts
- src/composables/useVotingGauges.spec.ts
- src/composables/useVotingGauges.ts
Fix issue where the countdown timer was showing 7d on the countdown page on wednesday's. Moved it to a composable and added tests to reproduce and ensure it's fixed. 
Fixes #1800
> Hotfix: Fix countdown timer

- src/services/rpc-provider/rpc-provider.service.ts
- src/services/rpc-provider/static-json-rpc-batch-provider.ts
Reducing number of chainId calls by caching current network on a provider.
Open a website on localhost and see if all the data loads correctly.
Special thanks to [@kyzia551](https://github.com/kyzia551) for sharing modified provider.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1202191812281001
> feat: reducing chain_id calls

- package-lock.json
- package.json
- src/components/_global/BalTable/BalTable.vue
Fixes table sorting breaking after the BalTable refactor. Just needed to return the sorted data for the `unpinnedData` computable when no data was pinned. 
- Load Any Balancer Table
- Check that it sorts when clicking column headers
- Ensure pools are sorted by TVL when first loaded
> Hotfix: Fix Table Sorting

- package-lock.json
- package.json
- src/composables/useNumbers.spec.ts
- src/composables/useNumbers.ts
I accidentally set the percentage formatting for very small numbers to the unscaled target cutoff of 0.01 for 0.01% instead of 0.0001. This PR reverts that mistake.
n/a
> Hotfix - percentage formatting

- package-lock.json
- package.json
- src/services/aave/aave.service.ts
- src/services/multicalls/erc20.multicaller.ts
Currently, the Aave boosted APRs are only being displayed onm the pool page and not in the pool list. This is because the existing calculation for the boosted APR was dependent on onchain pool data which we only fetch for individual pools and not for every pool in the pools list.
This PR refactors the Aave boosted APR calculation so it's not reliant on that external onchain data being fetched. Unfortunately, this means we need to do onchain calls just to fetch this additional info in the APR calculation. However, each linear pool APR calculation should be as isolated as possible anyway so that we can migrate to a more generic solution soon so it would need to be refactored in a similar way anyway.
n/a
> Hotfix - aave aprs

- package-lock.json
- package.json
- src/composables/queries/useProtocolRewardsQuery.ts
- src/composables/useClaimsData.ts
- src/pages/claim.vue
Fixes some console errors on the claims page around trying to fetch protocol rewards data on L2s where they don't exist.
n/a
> Hotfix - claims page console errors

- package-lock.json
- package.json
- src/components/images/Avatar.vue
The original Jazzicon hotfix (#1868) only partially fixed the problem. The Jazzicon also needs to be rendered after the parent component is mounted for some reason.
n/a
> Hotfix - Jazzicon fix 2

- package-lock.json
- package.json
- src/composables/trade/useSor.ts
- src/lib/utils/balancer/lido.ts
Currently if you were trading from or too stETH, after inputting amounts when the next block was mined the stETH amount would reset to zero. This is because for the initial amounts we're using the SOR and then to update amounts on each block we're using the queryBatchSwap, since it's a more efficient call. However, the return from the query batch swap only includes a reference to wstETH in the path addresses and so it's impossible to map the tokenOut address which is stETH to the query batch swap amount out index.
This PR adds a crude hack that checks if the token in/out is stETH and in this specific function for updating amounts on each block, replaces it with wstETH for finding the mapped amount values from the query batch swap results.
n/a
> Hotfix - fix steth trades

- package-lock.json
- package.json
- src/composables/trade/useGnosis.ts
When user was choosing to trade via cow swap and trade amounts weren't set yet, useGnosis.handleAmountChange function was asking for undefined input amounts.
Open trade UI choose "Trade gasless". Changing trade direction with empty input amounts shouldn't be causing errors.
> fix: useGnosis requests undefined values from useTrading

- package-lock.json
- package.json
- src/components/contextual/stake/StakePreview.vue
Hides incorrect yield information until we can implement the correct calculations.
n/a
> Hotfix - hide staking preview yield

- package-lock.json
- package.json
- src/composables/queries/useQueryStream.ts
- src/composables/queries/useStreamedPoolsQuery.ts
- src/pages/index.vue
Filtering was all sorts of messed up on the pools list on the home page. 
This was due to one main reason. The fact that the useQueryStream composable did not account for changes in query hash for both success states and internal data.
This means that success states for new query hashes (e.g. when you filter by a token, the hash changes) relied on the old hash (unfiltered), so it'd be relying on a state success state. Same for internal data.
Fix was to make it keyed by the query hash.
Test pools list.
N/A
> Hotfix - Pool list volumes

- src/services/web3/connectors/metamask/metamask.connector.ts
- src/services/web3/useWeb3.ts
Adds coinbase 1 click connect support. Doesn't affect UX much, if there is no injected connector it opens the modal.
Test that if you have an injected connector (any wallet extension) it auto connects. Otherwise, with none installed it should show the modal.
> Coinbase 1 Click

- package-lock.json
- package.json
- src/services/staking/utils.ts
Reward tokens which were no longer being seeded were still being included in the APR calcs. This PR removes that.
Test using COW/WETH pools, the APR should be lower.
N/A
> Fix - Account for reward token periods

- package-lock.json
- package.json
- src/services/pool/calculator/stable.ts
The original fix in #1924 used `scaleInput` which assumed token decimals of 18 since until now it was only dealing with BPT. This PR refactors to allow the `scaleInput` function to handle different token decimals.
n/a
> Hotfix - Stable pool price impact

- package-lock.json
- package.json
- src/constants/tokens.ts
Was not possible to invest in the kovan veBAL pool because the BAL address was different from the config. This PR changes the kovan config to use the BAL address associated with the veBAL pool.
n/a
> Hotfix - kovan bal address

- src/components/cards/CreatePool/PreviewPool.vue
- src/components/cards/CreatePool/TokenPrices.vue
- src/components/forms/pool_actions/MigrateForm/components/PoolsInfo/components/PoolInfoBreakdown.vue
- src/components/forms/pool_actions/WithdrawForm/components/WithdrawalTokenSelect.vue
- src/components/inputs/TokenSearchInput.vue
We consolidated token fetching in #1941 so that we didn't have to worry about if addresses were lower case or checksummed. There were a few locations where the old tokens array was used causing missing symbols/details. This PR fixes them. 
The main one noticed was when withdrawing from the 80/20 pool the BAL and WETH tokens were missing their symbols. See Image. 
Also fixes a bug where the invest form disappears if you switch from WETH to ETH. 
- Try withdrawing from the 80/20 BAL/ETH pool or other pools and ensure all token symbols/images load. 
- Try investing in a pool with WETH and switch to ETH and make sure the form doesn't disappear.
> Use getToken insead of tokens array in a few locations

- src/components/contextual/pages/pool/PoolTransactionsCard/TradeTransactions/Table.vue
In the trade table users ens avatars were being loaded but passed to the `address` field of BalAsset instead of iconSRC. This caused this error to be thrown since we started sanity checking addresses: https://sentry.io/organizations/balancer-labs/issues/3347571815/?project=5725878&referrer=slack
Fixes the issue by correctly passing the avatar to the iconURI. 
Look at pool `/#/pool/0x805ca3ccc61cc231851dee2da6aabff0a7714aa7000200000000000000000361` on Polygon in the trades table you should see a trade from timjrobinson.eth with my Rocketeer avatar. There should be no error in console. On current mainnet you'll see a generic jazzicon avatar and an error in the console
> Hotfix: Fix avatar icon being passed to 'address' in trade table

- src/lib/config/kovan.json
Address from monorepo, added in https://github.com/balancer-labs/balancer-v2-monorepo/commit/5bb5a56a8dd0988ce11a41d424e5c8822e3477aa 
Fixes error `Failed to fetch claimable protocol balances Error: resolver or addr is not configured for ENS name (argument="name", value="", code=INVALID_ARGUMENT, version=contracts/5.4.1)` seen on Kovan claim page. 
- Visit Claim page
- Ensure there are no errors about fetching claimable protocol balances. 
- Ensure claiming works correctly (I don't think there is any protocol fee claiming on Kovan, but other staking rewards should still work correctly).
> Add Kovan feeDistributor

- package-lock.json
- package.json
- src/composables/usePool.ts
In the token list for the Boosted Pool the BPT token was showing because it wasn't being filtered out correctly as the token address was checksum styled while the pool address was lowercase. Using the correct comparison function fixes the issue. 
- Load Balancer Homepage
- Ensure Boosted pool only shows 3 tokens, not 4. 
Incorrect:
Correct:
> Hotfix - Don't show boosted pool BPT token in token list

- package-lock.json
- package.json
- src/constants/pools.ts
Adds the new stable pool factories so that pool page can correctly display the title instead of "Unknown Pool Type"
tetuBAL and auraBAL pages should display "Stable Pool" in the title
We want to avoid this
> add stable pool v2 factories

- package-lock.json
- package.json
- src/constants/tokens.ts
- src/providers/local/staking/userUserStakingData.ts
- src/services/pool/calculator/calculator.sevice.ts
Due to refactoring of checksum address usage a case where we were using an address map but not transforming the address was not caught. This caused an exception in the single asset max withdrawal case which crashed the form. This PR fixes a couple of references to that address map.
Reference bug: https://discord.com/channels/638460494168064021/829044997202378852/989072431467614229
n/a
> Hotfix - Single asset max withdrawals

- src/composables/queries/useGraphQuery.ts
- src/lib/config/homestead.json
- src/lib/config/index.ts
- src/pages/index.vue
- src/services/balancer/subgraph/balancer-subgraph.client.ts
- src/services/config/config.service.ts
Reverts balancer-labs/frontend-v2#1898
The new graph endpoint stopped working on all environments (this vercel deployment, beta, and local testing) an hour or so ago. Reverting until we find the cause.
> Revert "use the decentralized graph endpoint"

- src/components/tooltips/APRTooltip/components/YieldBreakdown.vue
- src/composables/pools/usePools.ts
- src/composables/queries/usePoolQuery.ts
- src/composables/queries/usePoolsQuery.ts
- src/composables/queries/useStreamedPoolsQuery.ts
- src/composables/queries/useTokenPricesQuery.ts
- src/composables/queries/useUserPoolsQuery.ts
- src/composables/usePool.ts
- src/pages/index.vue
- src/pages/portfolio.vue
- src/services/aave/aave.service.ts
- src/services/balancer/subgraph/entities/pools/index.ts
- src/services/pool/concerns/liquidity.concern.ts
- src/services/pool/decorators/onchain-data.formater.ts
- src/services/pool/decorators/pool.decorator.ts
- src/services/pool/decorators/pool.multicaller.ts
- src/services/pool/pool.service.ts
- src/services/pool/types.ts
- src/services/staking/staking-rewards.service.ts
Various refactorings of coupled and messy code in pool queries,  i.e. usePoolQuery, usePoolsQuery & useUserPoolsQuery.
TODO before merge:
- Test changes to stream query doesn't break any functionality on home page.
Next steps for refactoring pool decoration/schema (in a new PR)
- Deep dive into all the additional fetching we're doing around linear pools and generalise. i.e. fetch additional sub-pool data for any pool token that happens to be a pool, not just linear pools of StablePhantom pools.
- Fix weird cyclic dependency in [staking-rewards.service.ts](https://github.com/balancer-labs/frontend-v2/pull/1963/files#diff-ec494d6f45c6897a66b89ac170e96d4aac13d3cc8f71e52133e4ef226475478dR183-R184) where we need accurate total liquidities to calc those APRs, but also we call this function in …
> Refactor pool queries

- package-lock.json
- package.json
- src/lib/config/arbitrum.json
Today Alchemy had issues with their Arbitrum RPC endpoint and even though they say it has recovered it still seems to be returning incorrect data as most of the time when trading it is reporting that there is no liquidity available even for common pairs like ETH/USDC. 
Until we figure out what the origin of this is temporarily switching the main RPC endpoint for Arbitrum to use Infura as it is working correctly. 
Test viewing pools + making trades on Arbitrum. Ensure all are working correctly. 
From Discord support:
From my own testing:
> Hotfix: Use infura for arbitrum RPC endpoint

- src/components/inputs/TokenSearchInput.vue
- src/pages/index.vue
- src/providers/tokens.provider.ts
- Removed extraneous loading prop
- First keypress on search input caused UI to freeze for ~3 seconds. Removed nested loops from `mapTokenListTokens`.
1. Go to home page
2. Click "Filter by token" button
3. Start typing to token search
4. Token list should update immediately
| Before | Now |
| ------ | ---- |
| <img width="640" alt="Screen Shot 2022-07-01 at 12 39 44" src="https://user-images.githubusercontent.com/28311328/176871207-48c30ad9-14f9-4434-8187-4c62871fe40e.png">   | <img width="640" alt="Screen Shot 2022-07-01 at 12 37 41" src="https://user-images.githubusercontent.com/28311328/176871265-b7017e02-cf89-47d8-bf56-3472385b6616.png">  |
> Improve token search performance

- src/pages/index.vue
This variable was being read wrongly so it would never be set to `loading`. This makes the pools table show "No pools" while price is done loading but pools are still loading from the graph. Fixed so that the pools table now correctly shows the loading animation while reading from the graph. 
- Load pools table on any network, you should never see "No pools" only a loading animation before the pools are shown.
> Make pools table show loading animation while waiting for graph data

- src/components/cards/PairPriceGraph/PairPriceGraph.vue
Add blank state instead of chart for equal trade pairs on trade page.
> Fix trade chart

- src/components/_global/BalTooltip/BalTooltip.vue
All attributes passed to `BalToolTip.vue` was bound to activator button, and to tooltip content elements.
Popperjs gave warnings if said attributes contained margin styles for the tooltip content.
**Solution:** Bind the attributes only to activator button.
Go to `/vebal` page and open browser console. You should not see these warnings anymore:
> Remove Popperjs warnings from console

- src/services/pool/pool.service.ts
We should always prefer to compute the value of a pool with information derived from Coingecko's price feeds.
When that's not possible, we can fall back to the subgraph's `totalLiquidity` estimate.
> Fallback to totalLiquidity from the subgraph if missing Coingecko prices

- package-lock.json
- package.json
- src/App.vue
Transaction notifications on the bottom left went missing. This fixes that
Make any sort of transaction, the modal should appear in the bottom left
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1202582526081309
> Fix missing transaction notifications

- package-lock.json
- src/services/pool/concerns/liquidity.concern.ts
Due to the restructuring of the pool queries we no longer rely on / assume that the pool's tokens will be injected into the registry before the pool is decorated. Therefore the liquidity calc was failing on Kovan when trying to fetch the decimals of the boosted pool's sub tokens since they're not in the registry when that calc happens. This is not a problem on mainnet since the boosted pool's sub tokens are included in the tokenlist.
This PR conditionally accesses the token decimal attribute. This will break the total liquidity calc for boosted pools on kovan but it's not a major issue since it will resort back to the subgraph value.
n/a
> Fix kovan boosted pool

- src/composables/useNetwork.ts
- src/composables/usePool.ts
Currently, we block all stable pools unless they've been added to the Allowlist array for their network. I think we can remove that auto-blocking on testnets for quicker testing, as requested by @mikebmikeb.
n/a
> Unblock testnet pools

- src/components/cards/CreatePool/PoolFees.vue
Pool creation page was rejecting swap fees equal to the MIN_SWAP_FEE_PERCENTAGE. Removing the `=` as a criteria for this being invalid solves this issue.
View [relevant pool code](https://github.com/balancer-labs/balancer-v2-monorepo/blob/master/pkg/pool-utils/contracts/BasePool.sol#L174) to see how fee can equal min fee.
> allow swap fee to equal _MIN_SWAP_FEE_PERCENTAGE

- src/components/pool/PoolPageHeader.vue
- src/components/tables/PoolsTable/PoolsTable.vue
- src/constants/pools.ts
Use "friendly names" for pools - that is a custom name that is different to pool composition or type.
Closes https://github.com/balancer-labs/frontend-v2/issues/2097
In pools table and pool page header, certain pools should now have a custom name instead of default pool composition/type. Also, in pool table, a custom icons are being used.
Check pool id "0x7b50775383d3d6f0215a8f290f2c9e2eebbeceb20000000000000000000000fe" which now has a name "Balancer Boosted Aave USD".
Custom icons in pools table.
- [n/a] I have commented my code where relevant, particularly in hard-to-understand areas
- [n/a] If package-lock.json has changes, it was intentional.
> Feature: friendly pool names

- src/constants/pools.ts
I spoke with Fernando & Markus – a decision was made to keep the BAL 80 / WETH 20 pool as is currently live.
> Removed friendly name & icon for BAL 80 / WETH 20 pool

- package-lock.json
- package.json
- src/components/cards/TradeCard/TradeCard.vue
A watcher was added to trigger swap calculation in the case of user inputting the data before the page dependencies have been loaded. This is unnecessary and causes a loop after dependencies are loaded -> then swap calculation gets triggered -> isLoading is set to true again.
Attempt to swap currency on "Trade" page.
N/A
- [n/a] I have commented my code where relevant, particularly in hard-to-understand areas
> hotfix: Removed watcher for isLoading

- .vscode/settings.json
Eslint is disabled as formatter by default, this enables it so you can run `Format document` command with eslint in VSCode.
> Fix chore: Enable eslint as formatter in settings

- src/composables/queries/usePoolQuery.ts
- src/pages/pool/_id.vue
- src/services/pool/decorators/pool.decorator.ts
On pool page we fetch aprs separately from other pool information for optimisation reasons, and this pr https://github.com/balancer-labs/frontend-v2/pull/2037 affected other places where we use usePoolQuery composable (aprs were not fetched). 
This pr fixes this issue. 
- Go to any page where aprs should be shown
- aprs are correctly shown
> Fix problem with downloading aprs (Closes #2118)

- src/components/modals/TradePreviewModalGP.vue
Closes #1913 
- Trade modal now shows correct token information when the trade is `wrap-unwrap`
- Open Trade UI
- Trade from wstETH to stETH
- Modal correctly shows "Amount before fees" and "Total to receive"
- [n/a ] If package-lock.json has changes, it was intentional.
> fix: unwrap trade summary token info

- package-lock.json
- package.json
- src/composables/queries/usePoolQuery.ts
- src/services/pool/pool.service.ts
For pool pages we override a default subgraph query attribute that ensures very low liquidity pools don't appear in our lists. This PR reduces the totalShares threshold to fix an Arbitrum subgraph bug where totalShares are -18 for some pools.
n/a
> Hotfix: total shares bug

- package-lock.json
- package.json
- src/composables/queries/usePoolQuery.ts
- src/services/pool/pool.service.ts
Reverts balancer-labs/frontend-v2#2137
We've resynced the Arbitrum subgraph and the problem went away
> Revert "Hotfix: total shares bug"

- src/components/contextual/stake/StakePreview.vue
- src/composables/useTransactions.ts
- src/locales/default.json
#2117 
- Show staking and unstaking toast
- Add staking and unstaking transactions to Recent activity menu
1. Launch app in Goerli
2. Go to stakable pool: http://localhost:8080/#/pool/0x16faf9f73748013155b7bc116a3008b57332d1e600020000000000000000005b 
3. Try staking and unstaking
| Toast | Recent activity |
| ----   | --------------- |
|     ![Screen Shot 2022-08-12 at 14 53 52](https://user-images.githubusercontent.com/28311328/184350353-c929d4db-6b59-4f83-88df-ae52446484f5.png)     |               ![Screen Shot 2022-08-12 at 14 53 37](https://user-images.githubusercontent.com/28311328/184350397-1537b7ae-97e3-4faa-9d9e-6dff1066c84e.png)             |
> Show staking and unstaking notifications

- src/constants/pools.ts
We're close to deploy to production a new version of the Subgraph that indexes the Gyroscope pools. This PR prevents the front-end from displaying those pool types.
> exclude gyro pools from ui

- package-lock.json
- package.json
- src/lib/config/arbitrum.json
- src/lib/config/docker.json
- src/lib/config/goerli.json
- src/lib/config/homestead.json
- src/lib/config/index.ts
- src/lib/config/kovan.json
- src/lib/config/polygon.json
- src/lib/config/rinkeby.json
- src/lib/config/test.json
- src/services/rpc-provider/rpc-provider.service.spec.ts
- src/services/rpc-provider/rpc-provider.service.ts
Currently most of our alchemy bill is from listening for new blocks through the websocket connection. The only thing we use from these new blocks is the block number. 
This PR switches this to only listen for one block, then set an interval of the chains cadence to update the current block number, which should lower our costs while providing essentially the same service to the rest of the app. 
- Test the app on Polygon and Arbitrum and ensure all functionality is working as expected.
- Test trading and ensure SOR is pulling in new data and updating prices on an interval. 
- After merging, ensure our Alchemy usage has dropped.
> Hotfix: Use an interval for new blocks instead of constantly listening to the websocket

- src/composables/watchers/useWeb3Watchers.ts
https://github.com/balancer-labs/frontend-v2/issues/1464
Connect the wallet which is on a wrong network then disconnect - the alert should disappear.
N/A
- [n/a] I have commented my code where relevant, particularly in hard-to-understand areas
- [n/a] If package-lock.json has changes, it was intentional.
> Fix: hide 'Network mismatch' alert after disconnecting from the wallet

- src/components/cards/PairPriceGraph/PairPriceGraph.vue
> Pair price chart is not in USD

- package-lock.json
- package.json
- src/components/_global/BalTable/BalTable.vue
- src/pages/index.vue
@zekraken-bot reported that since the last weekly release the investments / trades list on a single pool page is no longer showing the "load more" button. This is because of the change in #2156 that made all BalTable's not show load more with <10 results. 
I've moved the logic to the main pools page only for now, to solve the original issue (#1989) while not changing the logic of BalTable. 
This does have an edge case if there are exactly 10 pools that match a token, the load more button will show but not do anything. I'll be fixing this in #2093 when we rework pool fetching. I'll make this variable be based on if the vue-query reports there is more to load. 
- On the homepage, ensure load more works
- When filtering by a token on the homepage, load more should only show if there are >= …
> Hotfix: Fix load more not appearing for trade / investment tables

- src/components/tables/PoolsTable/PoolsTable.vue
This fixes the UI bug where the 'new' label lost its alignment to the pool token pills.
View a 'new' pool and check that the alignment has been corrected. There's a 'new' pool on Goerli – search for `DRGIV3`
Current UI:
Proposed UI:
> Fixed alignment of 'new' label in pools table.

- src/composables/contextual/pool-transfers/usePoolTransfers.ts
In invest/withdraw flow, keep the pool data up to date by refetching it on every block.
> Refetch poolQuery when blocknumber changes

- src/composables/queries/usePoolAprQuery.ts
- src/composables/useSnapshots.ts
- src/lib/config/arbitrum.json
- src/lib/config/docker.json
- src/lib/config/goerli.json
- src/lib/config/homestead.json
- src/lib/config/index.ts
- src/lib/config/kovan.json
- src/lib/config/optimism.json
- src/lib/config/polygon.json
- src/lib/config/rinkeby.json
- src/lib/config/test.json
- src/services/block/block.service.ts
- src/services/block/subgraph/block-subgraph.client.ts
- src/services/block/subgraph/block-subgraph.service.ts
- src/services/block/subgraph/entities/block-number/index.ts
- src/services/block/subgraph/entities/block-number/query.ts
- src/services/block/types.ts
- src/services/pool/decorators/pool.decorator.ts
- src/types/index.ts
Currently to calculate fees/volume we find a block 24 hours in the past by doing (secondsInDay / 13). This isn't very accurate and is currently off by about 300 blocks from the actual block 24 hours ago. 
This PR uses a subgraph request to find the exactly block number from 24 hours ago instead of doing this rough calculation. This is what the SDK is also using in the [APRs Update](https://github.com/balancer-labs/balancer-sdk/pull/98) so it will be easier to compare Prod APR/fees/volume numbers to that PR. 
- View pools page and individual pools, they should show volume / fees correctly.
> Fetch a more accurate time travel block for fees/volume

- src/components/contextual/pages/pool/PoolChart.vue
Pool snaphot timestamps are created on the base of utc day timestamps:
```
const currentTimestamp = Math.ceil(Date.now() / 1000);
const dayTimestamp = currentTimestamp - (currentTimestamp % DAY);
```
That is why in certain timezones (western ones), there is a problem of date delation, this pr fixes this. 
> Fix pool charts current date bug

- src/plugins/router.ts
- vue.config.js
Currently webpack automatically generates prefetch hints for all JavaScript files of our async routes.
Downloading all that chunks at start is not necessary + it leads to additional load on server, so this pr enables prefetching only for certain most common routes.
> Enable prefetch for certain routes

- src/composables/pools/usePoolCreation.spec.ts
- src/composables/pools/usePoolCreation.ts
- src/constants/topics.ts
- src/services/balancer/pools/weighted-pool.service.spec.ts
- src/services/balancer/pools/weighted-pool.service.ts
The pool creation form recovery mechanism relies on decoding the transaction data to recover the arguments sent to the pool factory (and so the config of the pool). This works from EOAs but if the pool is deployed using a contract wallet (such as a Safe) then this will fail as the call to the factory is wrapped in a call to the Safe. Instead we should read the pool's address through the emitted event and query the pool for it's config.
I've improved the `retrievePoolIdAndAddress` function to a method which uses the factory's interface to decode the event logs so we don't have to look for a hardcoded topic hash anymore. There was also a type issue in `PoolSeedToken` which I fixed.
Connect to the polygon app and attempt to recover the pool creation form using tx hash …
> Safe friendly pool creation recovery

- package-lock.json
- package.json
- src/composables/useTime.ts
- src/services/block/block.service.ts
The subgraph query to fetch the block number at a particular timestamp was taking a long time. This was due to the structure of the query, using a range to search for the block number drastically reduces the query time.
n/a
> Hotfix: block number fetching

- src/composables/trade/useTrading.ts
On page load, if I enter a value before the SOR loads I get a not enough liquidity error. It should refetch the swap. This is because SOR needs to be loaded to calculate trade amounts and if both are not present, not enough liquidity is assumed.
Load Trade page and enter amount before SOR has been loaded. If there is liquidity, it should allow you to preview/trade.
N/A
- [n/a] I have commented my code where relevant, particularly in hard-to-understand areas
- [n/a] If package-lock.json has changes, it was intentional.
> fix: Make sure SOR is used as soon as pools have been loaded

- package-lock.json
- package.json
- public/data/vebal-gauge.json
- public/data/voting-gauges.json
- src/components/contextual/pages/vebal/LMVoting/GaugesTable.vue
- src/components/icons/IconLimit.vue
- src/constants/voting-gauges.ts
- src/lib/scripts/voting-gauge.generator.ts
- src/locales/default.json
[edits by Markus]
With the introduction of capped gauges, the voting UI needs to be able to handle multiple the fact that a single pool can have more than one gauge associated with it added to the GaugeController.
https://github.com/balancer-labs/gauges-subgraph/pull/9 introduced support for this on the subgraph
#2175 introduced support for multiple liquidity gauges
This introduces support for multiple root gauges, introduces the notion of relativeWeightCap and updates voting-gauges.json
veBAL page should display the 19 new gauges introduced in [BIP-57](https://vote.balancer.fi/#/proposal/0x9158743a0be0705169d0b3dc6ea7297c8d2245f48fbfdfdf53d5f0b00968d1b6), in addition to the other gauges found in the production app
> add weight cap to voting gauges json

- package-lock.json
- package.json
- src/services/staking/staking-rewards.service.ts
The staking reward service is running through all gauges to generate a list of APRs here: https://github.com/balancer-labs/frontend-v2/blob/develop/src/services/staking/staking-rewards.service.ts#L116 and creating a map of poolIds > APR range. Now that we may have two gauges per pool, it was overriding the first apr result with the second. If the second result happened to be the new one it would set BAL rewards APRs to zero.
This PR introduces a temporary fix that checks for the gauge with the highest totalSupply and uses that one.
n/a
> Hotfix: fix multiple gauges apr bug

- package-lock.json
- package.json
- src/services/balancer/gauges/entities/gauges/query.ts
- src/services/balancer/gauges/types.ts
- src/services/staking/staking-rewards.service.ts
Maxis noticed the frontend shows a non-zero APR for pools that have had their gauges killed.
CREAM and FEI pools should not display any liquidity mining APR
> Fix BAL APR for killed gauges

- package-lock.json
- package.json
- src/composables/useVeBAL.ts
When refactoring the remaining time calculation into its own function for some reason the operation was reversed from plus to minus. This PR reverts that change. Fixes issue with incorrect remaining lock time being displayed in UI.
n/a
> Hotfix: gauge vote remaining time

- src/providers/tokens.provider.ts
- src/services/coingecko/api/price.service.ts
Sometimes pool IDs end up being used by accident to find tokens in the search input or via the trade UI URL params. At the moment we don't handle that and it causes errors like this one: https://sentry.io/organizations/balancer-labs/issues/3348522771/?project=5725878
This PR checks all passed token addresses in case they are a pool ID and extracts the substring in the case that it is.
n/a
> Always check if an address is actually a poolID

- src/components/contextual/stake/StakePreview.vue
- src/locales/default.json
> Add button to claims page on staking success

- src/services/web3/useWeb3.ts
- src/services/web3/web3.plugin.ts
Fixes `underlying network changed` Metamask errors. See https://github.com/ethers-io/ethers.js/issues/866
n/a
> Fix Ethers network changed bug

- src/constants/pools.ts
Adds `ComposableStable` to `ExcludedPoolTypes` in all networks to prevent UI from showing unsupported pools.
> hotfix: exclude composables from ui

- package-lock.json
- package.json
- src/constants/pools.ts
Adds the factory addresses so that the pool title is properly displayed on the pool page
0x0fd5663d4893ae0d579d580584806aadd2dd0b8b000200000000000000000367 should be labeled as a weighted pool on the pool page
Production
This PR
> add weigthed v2 factories addresses

- package-lock.json
- package.json
- public/data/hardcoded-gauges.json
- public/data/vebal-gauge.json
- public/data/voting-gauges.json
- src/components/contextual/pages/vebal/LMVoting/GaugesTable.vue
- src/constants/voting-gauges.ts
- src/lib/scripts/voting-gauge.generator.ts
Adds `addedTimestamp` - time the gauge was added to the controller - to the voting JSON and displays BalChipNew if it's less than 2 weeks ago.
Visit veBAL page and check if the recently created gauges (e.g. bbaUSD, maticX, and stMATIC) are labeled with the new tag.
> hotfix: add chip to new gauges

- package-lock.json
- package.json
- src/services/staking/staking-rewards.service.ts
Bug: Some pools are missing staking APR's in prod when they should have them. 
Reason: Gauges that were not preferential had no inflationRate or had `isKilled` set to true and so were returning nilApr which meant those pools had 2 staking APR's returned and the nilApr over-wrote the real gauges APR in the Object.fromEntries at the end of this function. 
By moving the isPreferentialGauge check higher the extra gauges are removed from the array instead.
This fixes the APR not being shown for pools such as `0xa7ff759dbef9f3efdd1d59beee44b966acafe214000200000000000000000180` and `0x27c9f71cc31464b906e0006d4fcbc8900f48f15f00020000000000000000010f`
- Check that APR's are showing for all pools the same as in production. 
- Check that for the pools above they are now showing staking APR's (they …
> Hotfix: Fix Missing APR's for pools with 2 gauges

- src/components/contextual/pages/vebal/LMVoting/GaugeVoteModal.vue
- src/locales/default.json
When voting on gauges which have voting limits, warn users in the modal that their vote might be wasted. They might still proceed with the vote.
Find a gauge which has a limit and votes above the cap. Click Vote button. In the modal, you should see a warning.
Check Figma for context.
- [n/a] If package-lock.json has changes, it was intentional.
> feat: Show warning that the user might be wasting their gauge vote

- package-lock.json
- package.json
- src/lib/config/arbitrum.json
- src/services/lido/lido.service.ts
Current stETH APR calculation assumes all pools with wstETH were WETH/wstETH stable pools. This causes the stETH APR on weighted pools to be overestimated.
This PR implements a check for the weight of wstETH in the pool and uses this weight as the ratio if it exists.
It also adds the address of wstETH on Arbitrum so that stETH APR is displayed for pool in that network.
- Check the stETH APR [here](https://stake.lido.fi/api/apr)
- On the app's Invest tab (mainnet and arbitrum), search for a weighted pool containing wstETH
- Check the APR breakdown tooltip:
- it should be equal to `50% * wstETH_weight_in_the_pool * stETH_APR_from_Lido`
> Fix stETH apr for weighted pools

- package-lock.json
- package.json
- src/constants/tokens.ts
- src/pages/claim.vue
- src/services/balancer/contracts/contracts/fee-distributor.ts
We support two versions of bb-a-USD token. On claims page, only v1 is showing up. After this merge request, both versions of the token are visible.
Go to claims page and you should see both versions of bb-a-USD and be able to claim them.
N/A
> Hotfix: bb-a-usd v2 added to feeDistrubutor token list

- package-lock.json
- package.json
- src/components/forms/pool_actions/WithdrawForm/components/ProportionalWithdrawalInput.vue
- src/components/forms/pool_actions/WithdrawForm/components/WithdrawPreviewModal/components/WithdrawActions.vue
- src/components/forms/pool_actions/WithdrawForm/components/WithdrawalTokenSelect.vue
- src/components/forms/pool_actions/WithdrawForm/composables/useWithdrawMath.ts
- src/constants/pools.ts
- src/services/balancer/subgraph/entities/poolShares/query.ts
- src/services/pool/calculator/calculator.sevice.ts
Adds support for proportional exits from shallow ComposableStable pools using the `BPTInForExactTokensOut` exit type.
Shallow ComposableStable pools for testing:
- Goerli - https://beta-goerli-git-hotix-proportional-composable-stable-balancer.vercel.app/#/pool/0x98087bf6a5ca828a6e09391ace674dbabb6a4c5600000000000000000000019b
- Polygon - https://beta-polygon-git-hotix-proportional-composable-stable-balancer.vercel.app/#/pool/0x8159462d255c1d24915cb51ec361f700174cd99400000000000000000000075d
- Polygon - https://beta-polygon-git-hotix-proportional-composable-stable-balancer.vercel.app/#/pool/0xb20fc01d21a50d2c734c4a1262b4404d41fa7bf000000000000000000000075c
> Hotfix: Add proportional exits for ComposableStable pools

- src/composables/queries/useUserPoolsQuery.ts
There was a duplicate calculation of total liquidity for boosted pools happening in the useUserPoolsQuery that was also being done in the decorate call just before it. This PR simply removes that duplicate calculation.
n/a
> Remove totalLiquidity calc that's done in the decoration step

- src/components/contextual/pages/pool/PoolChart.vue
- src/composables/queries/useHistoricalPricesQuery.ts
- src/composables/queries/usePoolSnapshotsQuery.ts
- src/constants/queryKeys.ts
- src/pages/pool/_id.vue
- src/services/balancer/subgraph/entities/poolSnapshots/index.ts
If coingecko is down there will be blank state instead of pool charts, this happens because of fetching prices in `usePoolSnapshotsQuery`. 
This pr adds new composable to fetch historical prices and use `snapshot.liquidity` from subgraph if there are no prices. 
> Divide snapshot and prices queries

- src/components/contextual/pages/pool/PoolContractDetails.vue
`loading` prop removed from `PoolContractDetails` because it is not actually being used. 
It clears this warning when rendering `_id.vue`
> Remove orphan loading prop

- src/components/_global/BalAccordion/BalAccordion.vue
- src/components/cards/TrendingPairs/TrendingPairs.vue
This pr fixes BalAccordion component bug  which was mentioned in [#2346](https://github.com/balancer-labs/frontend-v2/issues/2346)
> Fix BalAccordion component bug (Closes: #2346)

- src/plugins/router/nav-guards.ts
Subdomain format urls result in infinite loop redirect. This fixes it by not using router.go(0).
> Fix: subdomain redirect loop

- src/plugins/router/nav-guards.ts
When redirecting pages using subdomain network names, we now retain fullPath in the redirection url, even when it doesn't have networkSlug.
> Fix: subdomain redirection now supports legacy paths

- src/components/contextual/pages/pool/invest/WrapStEthLink.vue
- src/composables/usePool.ts
There's an existing component that shows the user an option to swap between wsteth and steth. On Arbitrum steth doesn't exist since wsteth is bridged. Renamed check to `isMainnetWstETHPool`
> no steth on arbitrum, fix tooltip

- src/lib/config/arbitrum.json
- src/lib/config/goerli.json
- src/lib/config/kovan.json
- src/lib/config/rinkeby.json
- src/pages/index.vue
- src/plugins/router/nav-guards.ts
If url requested doesn't have networkSlug, and it is using pool route, then always redirect to ethereum mainnet url.
Also, on main page, show network name in pools heading.
> Fix: always redirect pool urls to mainnet

- src/components/cards/PairPriceGraph/PairPriceGraph.vue
Fix week/month charts on trade page. They are not working currently on production.
- Go to trade page
- Open charts
- Choose week/month filter and chart should be visible
There may be 429 error from coingecko. Please pay attention to it.
> Fix week/month charts on trade page

- src/components/modals/VeBalRedirectModal.vue
Currently, "Proceed" button on VeBAL redirect modal uses href to take user to ethereum page. This sometimes doesn't work. Changed to vue router.
Change to non-ethereum network. Go to vebal page. Click Proceed.
> fix: Vebal redirect modal routing

- src/components/contextual/pages/vebal/LMVoting/GaugesTable.vue
On veBAL page, vote button wasn't working because of row click event. Added preventDefault to stop bubbling.
Go to veBAL page and open vote modal for a pool.
> Fix: veBAL pool voting button not working

- package-lock.json
- package.json
- src/services/config/config.service.ts
- src/services/web3/connectors/trustwallet/walletconnect.connector.ts
Original #2400
The app was throwing lots of errors whenever a wallet connect user switched network. The `WalletConnectProvider` is supposed to be initialized with all of the RPCs. Let me know if there's a cleaner way to use the `ConfigService` here
n/a
> Hotfix: wallet connect provider needs all rpcs used

- src/components/navs/AppNav/AppNavNetworkSelect.vue
- src/plugins/router/nav-guards.ts
On network change we hide what's on the page to prevent content flash (e.g. pools reloading). This causes errors in Sentry. Changed document.write('') to document.body.style.display = 'none'. Considered using visibility, takes too many resources.
Changing networks, sentry logs.
> Fix: DOM errors on network change due to document hiding

- src/composables/contextual/pool-transfers/usePoolTransfers.ts
- src/pages/pool/invest.vue
- src/pages/pool/withdraw.vue
We are re-fetching pool data on every block in the join/exit flows. The reason for adding this in the first place is to keep balances up to date for when the user submits a transaction. However, on L2s like Polygon this results in heavy data fetching every couple of seconds because of the block time.
I think we should remove this logic and accept that if the user is on the join/exit flow for a long time balances may go stale and the transaction may revert. I don't think this will be a common case.
In the future, we should only fetch new balances every 30s or so. i.e. only fetch the limited data we need to keep up to date and at a suitable interval.
n/a
> Remove pool fetching on every block

- src/components/cards/TradeCard/TradeCard.vue
The app was allowing users to submit trades when the wallet provider didn't match the network being used in the app. This was failing silently with the metamask simulated tx fail.
Confirm preview button is disabled and an error shown if the networks don't match on the swap interface
> Prevent trade preview and submission if network mismatch

- package-lock.json
- package.json
- src/components/_global/BalTable/BalTable.vue
- src/components/_global/BalTable/BalTableRow.vue
- src/components/contextual/pages/vebal/LMVoting/GaugesTable.vue
veBAL table allows user to click or middle click on the row which opens pool page. However, Optimism pools use external explorer. This merge requests turns row into `a` element if the pool url is external.
> Hotfix: handle Optimism external urls on veBAL page

- package-lock.json
- package.json
- src/components/contextual/stake/StakePreview.vue
- src/components/pool/PoolPageHeader.vue
- src/providers/local/staking/userUserStakingData.ts
Allow users to unstake if a preferential gauge is not set. Removes restake pool page header if the pool is affected by a vulnerability.
Replaces: #2419
Test old bb-a-usd staking form shows correctly with a staked address
> Hotfix: issue with preferential gauges for unstake

- src/components/modals/TradePreviewModalGP.vue
Since fee number on Trade Preview modal is always zero for default swaps (non gassless) - we have removed this front-end element altogether until a more accurate calculation can be displayed.
Preview trade modal on Trade page - check gassless and standard swaps and calculated fees.
> Fix: removed trade preview fee overview since it's hardcoded as zero

- src/components/forms/pool_actions/InvestForm/components/InvestPreviewModal/InvestPreviewModalV2.vue
- src/constants/queryKeys.ts
- src/providers/local/join-pool.provider.ts
Replaces `debounceQueryJoin` with `queryJoinQuery` that uses useQuery.
n/a
> Refactor: use query for query instead of debounce

- jest.config.js
- src/providers/token-lists.provider.spec.ts
- src/tests/msw/handlers.ts
- src/tests/tokenlists/tokens-5.json
This is a new unit test that covers `token-lists.provider`. I added it to better understand this provider during the vite migration spike. 
As pointed in [this PR](https://github.com/balancer-labs/frontend-v2/pull/2375), this kind of tests could be simplified by refactoring the current Root providers pattern. This test can be helpful until we have that discussion.
> Add test to cover token lists provider

- src/components/_global/BalTable/BalTable.vue
- src/components/_global/BalTable/BalTableRow.vue
- src/components/contextual/pages/vebal/LMVoting/GaugesTable.vue
- src/components/tables/PoolsTable/PoolsTable.vue
Adds support for cmd+click on rows in pool table so that pool pages open in new tab.
n/a
> Fix cmd+click pool row functionality

- src/components/btns/ClaimRewardsBtn/ClaimRewardsBtn.vue
- src/lib/abi/LiquidityGaugeHelperAbi.json
- src/lib/config/arbitrum.json
- src/lib/config/goerli.json
- src/lib/config/index.ts
- src/lib/config/polygon.json
- src/services/balancer/contracts/contracts/gauge-reward-helper.ts
- src/services/balancer/gauges/gauges.decorator.ts
Currently gauge rewards shown on our front-end for alternate chains are not accurate. This change changes the pending rewards figures to come from the helper contract as well as claiming through the helper contract.
Claiming and pending rewards behaviours should remain unbroken.
N/A
> Use gauge reward helper contract to claim rewards on layer 2s

- package-lock.json
- package.json
- src/services/web3/web3.plugin.ts
- src/tests/msw/handlers.ts
Changing check-wallet to take the wallet address as a query parameter instead of a path parameter (see https://github.com/balancer-labs/balancer-api/pull/129) so that it can be cached with Cloudflare. 
- Load the frontend and perform a transaction, it should connect to the check-wallet endpoint and return a 200 status code with `{is_blocked: false}`
- Load the frontend with a malicious wallet (using impersonator), it should connect to the check-wallet endpoint and return a 200 status code with `{is_blocked: true}`
> Hotfix: Pass check-wallet address as a query param

- package-lock.json
- package.json
- src/services/pool/exchange/serializers/ExitParams.ts
In the exit params, for amountsOut, we were defaulting to 18 decimals if no decimals for the token could be found. For certain tokens where the decimals were `0` this meant the resulting conditional `0 || 18` which in JS resolves to `18`.
The fix, we should not use defaults in the exit params and throw and error if we can't access the decimals.
n/a
> Hotfix: no default decimals

- src/providers/local/join-pool.provider.ts
For generalized joins, it's possible to have an amountsIn array where one of the amountsIn have a value of 0 or ''. i.e. the user adds values to some tokens but not all and then clicks to Add Liquidity.
This PR prevents those empty amounts in from being submitted to the join functions.
n/a
> Fix: no zero amounts in

- package-lock.json
- package.json
- public/data/hardcoded-gauges.json
- public/data/vebal-gauge.json
- public/data/voting-gauges.json
- src/constants/voting-gauges.ts
- src/lib/scripts/voting-gauge.generator.ts
Adds `isKilled` flag to the `voting-gauges.json` so stakeDAO and other integrations can filter out deprecated gauges easily. 
> add isKilled to voting gauges

- src/components/_global/BalCheckbox/BalCheckbox.vue
- src/components/cards/MyWallet/MyWallet.vue
- src/components/contextual/pages/pool/MyPoolBalancesCard.vue
- src/components/contextual/pages/pool/PoolActionsCard.vue
- src/components/forms/pool_actions/InvestForm/InvestFormV2.vue
- src/composables/pools/useInvestPageTabs.ts
- src/composables/pools/useWithdrawPageTabs.ts
- src/locales/default.json
This change includes:
- Minor UI & UX tweaks for the deep pool flow
- Removed the 'You can add' section on the pool page, which no longer made sense since people can add non-pool tokens as liquidity.
- Updated text in toaster notifications from 'Pool pending' and 'Pool confirmed' to 'Add liquidity pending' and 'Add liquidity confirmed'.
- Minor typography changes to the invest flow.
- Enhanced bal checkbox for high price impact acknowledgment
> Deep pool ui/ux tweaks

- src/components/contextual/pages/pool/PoolChart.vue
Add timestamps in new pools in order to display charts better. 
> Add timestamps in new pool charts

- src/components/contextual/pages/pool/invest/InvestPageInvestBlock.vue
- src/composables/contextual/pool-transfers/usePoolTransfers.ts
- src/lib/balancer.sdk.ts
- src/pages/pool/withdraw.vue
- src/providers/local/exit-pool.provider.ts
- src/providers/local/join-pool.provider.ts
We were doing unecessary fetching of the SOR fetch pools function every time the user entered the join/exit flows. This PR moves SOR.fetchPools() to the global level so that it's fetched in the background as soon as the app loads. 
n/a
> Cleanup join/exit flow loading states

- src/composables/useTransactionErrors.ts
- src/services/web3/transactions/concerns/contract.concern.ts
- src/services/web3/transactions/concerns/raw.concern.ts
- src/services/web3/transactions/transaction.builder.spec.ts
- src/services/web3/web3.plugin.ts
See title.
1. Load app and connect wallet.
2. Make sure wallet and app network are the same.
3. Switch to a different network in the app.
4. Try to stake or unstake an investment.
5. You should see an error message about a network mismatch in the modal.
n/a
> Add gaurds to TxBuilder to protect against wallet/app network mismatch

- package-lock.json
- package.json
- src/components/forms/pool_actions/InvestForm/composables/useInvestMath.ts
This pool on Arbitrum (0x64541216bafffeec8ea535bb71fbc927831d0595000100000000000000000002) was throwing a SUB_OVERFLOW error when loading the invest page. It was triggered by `exactTokensInForBPTOut` being called with zero values. This doesn't usually trigger this error but for some reason in this pool it was. The fix is simply to not call this function if the form has no input values.
Fixes https://sentry.io/organizations/balancer-labs/issues/3788917839
n/a
> Hotfix: sub overflow bug

- package-lock.json
- package.json
- src/services/web3/transactions/concerns/contract.concern.ts
- src/services/web3/transactions/concerns/raw.concern.ts
We should only trigger guards if tx gas settings have been fetched successfully and we are ready to trigger the tx.
n/a
n/a
> Hotfix: Move guards directly before tx

- package-lock.json
- package.json
- src/components/inputs/TokenInput/TokenInput.vue
- src/composables/trade/useSor.ts
- src/lib/utils/balancer/helpers/sor/sorManager.ts
TokenInput used to have this internal state for amount/address. I know it seems like we can just use prop values here but I seem to remember a specific reason it was like this. I believe this might be causing a lot of the exceptions we are seeing in the swap UI after merging the boosted pool work. The changes to the TokenInput seem to be the only thing that could cause this after looking through the diff. So this PR reverts to using internal state for this component.
We should deploy this and see if the exceptions are fixed in Sentry. If not we can investigate further.
n/a
> Hotfix: revert token input changes

- src/components/links/BridgeLink.vue
- src/pages/trade.vue
Somehow this got reverted in the boosted pool work, re-adding functionality back in.
n/a
> Re-add BridgeLink to trade page

- src/pages/claim.vue
"Claim on Polygon" and "Claim on Arbitrum" buttons were pointing to old urls. This fix updates to the new ones.
> Fix polygon and arbitrum hrefs in claim buttons

- .eslintrc.js
- src/components/cards/CreatePool/PoolFees.vue
- src/components/contextual/pages/claim/LegacyClaims.vue
- src/components/contextual/pages/pool/StakingIncentivesCard/StakingIncentivesCard.vue
- src/components/contextual/stake/StakePreview.vue
- src/components/tables/GaugeRewardsTable.vue
- src/composables/pools/usePoolMigration.ts
- src/composables/queries/useExpiredGaugesQuery.ts
- src/composables/queries/useRelayerApprovalQuery.ts
- src/composables/trade/useSor.ts
- src/composables/usePool.ts
- src/lib/scripts/voting-gauge.generator.ts
- src/lib/utils/apr.helper.ts
- src/lib/utils/balancer/pool.ts
- src/pages/claim.vue
- src/providers/local/staking/staking.provider.ts
- src/providers/local/staking/userUserStakingData.ts
- src/services/balancer/contracts/contracts/gauge-controller.ts
- src/services/balancer/contracts/contracts/liquidity-gauge.ts
- src/services/balancer/contracts/contracts/token-admin.ts
- src/services/balancer/contracts/contracts/vebal-helpers.ts
- src/services/balancer/contracts/contracts/vebal-proxy.ts
- src/services/balancer/pools/joins/handlers/swap-join.handler.ts
- src/services/balancer/pools/weighted-pool.service.ts
- src/services/staking/staking-rewards.service.ts
- src/services/staking/utils.ts
Importing from 'ethers/lib' was causing issues when building with vite (that uses rollup underneath).
This PR adds a new eslint rule to avoid introducing this kind of imports again. 
> Avoid ethers/lib/* imports to avoid vite build issues

- package-lock.json
- package.json
- src/components/tooltips/APRTooltip/components/StakingBreakdown.vue
Some Staking APR's weren't being converted from basis points to decimals correctly
- Check APR Tooltips on Polygon / Arbitrum and ensure they look sane without any 10,000x values.
> Hotfix: Scale staking APR's correctly

- package-lock.json
- package.json
- src/composables/usePool.ts
Fixes scaling of APR when boost is applied, we were missing the bpToDec function.
n/a
> Hotfix: Boosted APR scaling

- src/components/tooltips/APRTooltip/components/StakingBreakdown.vue
- src/composables/queries/usePoolsQuery.ts
- src/composables/useNumbers.ts
- src/composables/usePool.ts
- src/services/balancer/api/entities/pools/index.ts
There were two bugs causing the staked pools list to show every single pool instead of only the ones the user had a stake in
- The first bug was there where the query wasn't being updated when poolIds was of length 0
- Second bug was the Balancer API doesn't accept an empty array for pool id in. So I've added a hack for it to just pass a single empty string instead. It also didn't like if both in and not_in were in the same query so I deleted the not_in. Will fix the API correctly soon.
- Visit your portfolio page, it should show pools you are staking in, or an empty list if you're not staking in any pools.
> Fix portfolio staked pools list

- src/components/contextual/pages/pool/PoolChart.vue
- src/components/contextual/pages/pool/PoolStatCards.vue
- src/components/pool/PoolPageHeader.vue
Change chart shimmer height to prevent block shifting down when data is loaded 
> Change chart shimmer height

- src/components/tooltips/APRTooltip/APRTooltip.spec.ts
- src/components/tooltips/APRTooltip/components/YieldBreakdown.vue
- src/composables/__mocks__/useTokens.ts
- src/locales/default.json
- When there is a single token giving yield show <symbol> APR
- When there are multiple tokens giving yield show a breakdown with a generic header of 'Token APR'
- Removes a bunch of 'is X token in this array' checks that were getting unruly and replaces them with the token symbol + APR
- Look at the APR tooltips of pools with token yield, ensure they look correct, include all tokens, and make sense.
> Improve + simplify token yield breakdown in APR Tooltip

- src/components/_global/shapes/BalCircle/BalCircle.vue
- src/components/cards/CreatePool/PreviewPool.vue
- src/components/cards/PairPriceGraph/PairPriceGraph.vue
- src/components/contextual/pages/pool/PoolChart.vue
- src/components/forms/pool_actions/MigrateForm/MigrateForm.vue
- src/components/pool/PoolPageHeader.spec.ts
- src/components/pool/PoolPageHeader.vue
- src/composables/queries/usePoolQuery.ts
- src/composables/queries/usePoolsQuery.ts
- src/main.ts
- src/pages/claim.vue
- src/pages/pool/create.vue
- src/pages/trade.vue
- src/providers/app.provider.ts
- src/providers/tokens.provider.ts
- src/store/modules/app.ts
Since we use api now, it seems that we don't need to wait until app is loaded (`appLoading === true`) in usePoolsQuery composable. Removing this `enabled` condition leads to faster rendering of pools table on main page
> Remove pools query enable condition

- src/components/navs/AppNav/AppNavNetworkSelect.vue
If the user is manually switches networks via wallet to a network the url points to, don't reload the page.
> fix: don't redirect after manual wallet switch if on correct page

- src/components/contextual/stake/StakePreview.vue
Fixes #2244. I couldn't reproduce but tested that all the existing functionality still worked
Confirm staking and unstaking works as expected
> prevent staking before current lp balance is loaded

- package-lock.json
- package.json
- src/components/contextual/pages/vebal/LMVoting/GaugesTable.vue
- src/components/contextual/pages/vebal/LMVoting/LMVoting.vue
- src/composables/usePool.ts
Pool redirecting on the veBAL page hasn't been working because `poolType` wasn't passed to `poolURLFor` function.
Go to veBAL page and click on any Optimism pool and you should be redirected to Beets app.
> hotfix: pool redirect url

- src/lib/config/arbitrum.json
- src/lib/config/homestead.json
- src/lib/config/polygon.json
- src/services/balancer/api/entities/pool/index.ts
- src/services/balancer/api/entities/pools/index.ts
- src/services/pool/pool.repository.ts
- Fetch individual pools using the Balancer API REST endpoint rather than doing a GraphQL call. This mitigates some issues we've had requesting just one item from GraphQL.
- Use https://api.balancer.fi/graphql for GraphQL queries now that this endpoint has been implemented. This is just an API Gateway route that forwards to Appsync. 
I'd been debugging an issue where the Balancer GraphQL API wasn't returning certain pools that were in the database. Turns out it was caused by two things:
- Fetching an individual pool by ID was doing a full table scan for that ID instead of using an index. 
- Appsync can only scan a max of 1MB of DynamoDB data for the information it needs. 
So pools that were beyond that initial 1MB weren't returning. 
This can be fixed by using another index on the API …
> Use Balancer REST API for fetching individual pools

- src/components/navs/AppNav/AppNavAlert.vue
- src/composables/watchers/usePoolCreationWatcher.ts
Closes: #2591 
1. Go to pool creation page
2. Add some new pool parameters and click continue to the 2nd step
3. Navigate back to front page
4. Refresh the page
5. Close the Pool Creation alert.
6. Refresh the page again, and the alert should stay hidden
> Fix: Permanently dismiss pool creation alert if user closes it

- src/composables/queries/usePoolsQuery.ts
- src/lib/utils/balancer/api.ts
- src/services/pool/pool.repository.spec.ts
- src/services/pool/pool.repository.ts
When connected to Goerli, you can see the attached error when loading the index page.
The problem is that [goerli.json](https://github.com/balancer-labs/frontend-v2/blob/870d008f7062e3082cb446c895a8df61f4bab8ba/src/lib/config/goerli.json) does not have an attribute for balancerApi so that the SDK.
This solution will also work for `docker.json`.
> Skip balancer api repository when url is not defined

- src/services/balancer/pools/exits/exit-pool.service.ts
- src/services/balancer/pools/exits/handlers/generalised-exit.handler.ts
- src/services/balancer/pools/joins/handlers/generalised-join.handler.ts
- src/services/balancer/pools/joins/join-pool.service.ts
- Refactors DeepExitHandler and DeepJoinHandler classes.
- Renames DeepExitHandler > GeneralisedExitHandler and DeepJoinHandler > GeneralisedJoinHandler because it better describes what the handler is handling. The fact that it's used for deep pools is just one use case, it may be used for other pool types at some point.
n/a
> Rename and refactor deep join/exit handlers

- src/components/cards/MyWallet/MyWallet.vue
On swap page there is a section called "My wallet". After clicking on token icon in this section, the token clicked with be used as tokenIn.
> Fix: after clicking on token icon on swap page, use it as tokenIn

- .github/workflows/tag.yml
The first step towards automating release notes is to automatically tag any push to master. I have been doing this manually when I created releases.
I've tested on a fork and this definitely works.
n/a
> feat: Add tag Github action

- package-lock.json
- package.json
Update SDK to [0.1.44](https://github.com/balancer-labs/balancer-sdk/releases/tag/v0.1.44)
Fixes Price Impact in Boosted Pools. Price Impact for BoostedPools is currently innacurate and displaying too high. This is a combination of
- incorrect stable maths for invariant
- PriceRates from SG are innacurate and don't exist for Linear Pool wrapped token - these need to be fetched using onchain calls.
Fixed by:
- Update SOR to 4.0.1-beta.17 - Has fixes for stable maths
- Add PoolsSubgraphOnChainRepository. Retrieves pools from SG and updates with onchain values. Important for correct priceRates.
- Join/Exit services use onchain pool data.
- Add subgraphQuery option to help filtering during tests that use onchain data.
- Removes default SpotPrice option as was previously a fix for linear pool …
> Update SDK to 0.1.44. Fixes PI for BoostedPools.

- src/providers/tokens.provider.ts
When searching for ETH on mainnet it always appeared at the bottom of the list, even when searching for 'ETH'. This was because we were injecting ETH into the tokens registry after the tokenlist tokens. Since we only inject ETH on app load we can simply place injected tokens at the top of the list instead.
n/a
> fix: Make injected tokens appear first

- src/composables/pools/usePoolCreation.ts
The scaled balances were using a bignumber toString which is bad and introduces things like 2.5e19.
> Fix number format on pool creation

- src/components/forms/pool_actions/InvestForm/components/InvestPreviewModal/components/InvestActions.vue
- src/components/forms/pool_actions/WithdrawForm/components/WithdrawPreviewModal/WithdrawPreviewModal.vue
- src/components/forms/pool_actions/WithdrawForm/components/WithdrawPreviewModal/components/WithdrawActions.vue
- src/components/forms/pool_actions/WithdrawForm/composables/useWithdrawMath.ts
- Force balances to be refetched after tx success
- https://github.com/balancer-labs/frontend-v2/commit/85fc3c7c185f5547dfbbb59e808f53b9722c04a2
- https://github.com/balancer-labs/frontend-v2/commit/0e8abb8b97bdd9ae45b546afc93adbc0bc4f3499
- [Fetch latest onchain pool data before calc](https://github.com/balancer-labs/frontend-v2/commit/38911fc1b416263f39dba6e68e6732ab7c36b025)
- [Make priceImpact static in preview](https://github.com/balancer-labs/frontend-v2/commit/dc263db620d329ac6cf0788f3b12607a82205ba0)
n/a
> fix: Fixes a variety of small bugs in the join/exit flows

- src/components/contextual/pages/claim/HeroClaim.vue
- src/components/contextual/pages/claim/LegacyClaims.vue
- src/composables/queries/useGaugesDecorationQuery.ts
- src/locales/default.json
- src/pages/claim/index.vue
- src/pages/claim/legacy.vue
- src/plugins/router/index.ts
Moves legacy claims section on claims page to its own page at /claim/legacy
n/a
> Move legacy claims to its own page

- package-lock.json
- package.json
- src/lib/config/arbitrum.json
Temporarily use beta arbitrum endpoint where metastable pools are indexed.
> Arbitrum graph endpoint

- package-lock.json
- package.json
- src/composables/trade/useGnosis.ts
This pr fixes the bug on swap page, when user tries to input, e.g. `0.01` in `gnosis` trade flow. Now this value will automatically set to 0. 
> Hotfix: gnosis zero trade value handle

- src/locales/default.json
We were missing locale key for "drip" which is used when connected to `Goerli`:
> Add drip to locale

- src/components/_global/BalDataList/BalDataList.vue
- src/components/_global/BalDataList/BalDataListRow.vue
- src/components/contextual/stake/StakePreview.vue
- src/components/contextual/stake/StakeSummary.vue
- src/components/forms/pool_actions/InvestForm/components/InvestPreviewModal/components/InvestSummary.vue
- src/components/forms/pool_actions/WithdrawForm/components/WithdrawPreviewModal/components/WithdrawSummary.vue
- src/types/global-components.d.ts
The summary section of the preview modals for join/exit/stake/unstake all had minor differences which made it all feel inconsistent. This PR creates a BalDataList component and has each of the flows use it so that styling is the same in all.
Inconsistent styles in each flow, text size, missing title, background color and border color on dark mode.
Now each flow should look exactly like the Withdrawal Preview version.
> Refactor: make summaries consistent

- package-lock.json
- package.json
- src/__mocks__/boosted-pool.ts
- src/__mocks__/pool.ts
- src/__mocks__/weighted-pool.ts
- src/components/forms/pool_actions/InvestForm/InvestFormV2.vue
- src/components/forms/pool_actions/InvestForm/components/MissingPoolTokensAlert.vue
- src/components/forms/pool_actions/WithdrawForm/WithdrawFormV2.vue
- src/components/forms/pool_actions/WithdrawForm/components/WithdrawTotalsV2.vue
- src/composables/useNumbers.spec.ts
- src/composables/useNumbers.ts
- src/locales/default.json
- src/pages/pool/withdraw.vue
- src/providers/local/exit-pool.provider.ts
- src/services/balancer/pools/exits/exit-pool.service.ts
- src/services/balancer/pools/exits/handlers/exact-in-exit.handler.ts
- src/services/balancer/pools/exits/handlers/exact-out-exit.handler.ts
- src/types/global-components.d.ts
**When exiting deep Weighted pool, limit single asset tokens to high level tokens.**
For details on the functions that are be used for exits see:
- https://github.com/balancer-labs/balancer-sdk/blob/develop/balancer-js/README.md#buildexitexactbptin
- https://github.com/balancer-labs/balancer-sdk/blob/develop/balancer-js/README.md#buildexitexacttokensout
And for price impact:
- https://github.com/balancer-labs/balancer-sdk/blob/develop/balancer-js/examples/priceImpact.ts
- Go to Deep Weighted Pool's withdraw page `http://localhost:8080/#/ethereum/pool/0x25accb7943fd73dda5e23ba6329085a3c24bfb6a000200000000000000000387/withdraw`
- Select "Single token" tab
- Select any pool token to exit to and try inputting different amounts
Please provide any relevant visual context for UI changes or …
> Add single asset exits for Weighted pools in generalised flow

- src/lib/config/arbitrum.json
- src/lib/config/docker.json
- src/lib/config/goerli.json
- src/lib/config/homestead.json
- src/lib/config/index.ts
- src/lib/config/optimism.json
- src/lib/config/polygon.json
- src/lib/config/test.json
- src/services/config/config.service.ts
- src/services/rpc-provider/rpc-provider.service.spec.ts
- src/services/rpc-provider/rpc-provider.service.ts
loggingRpc is a legacy thing we don't use anymore, removing from config.
n/a
n/a
> chore: Remove loggingRpc from config

- src/components/cards/MyWallet/MyWallet.vue
Fix for selecting a token to join with. 
1. Go to invest page of some pool.
2. Clicking one of "Pool tokens" should max the token input
3. Clicking one of "Other tokens" should switch to "Single token" tab and max the input
> fix: Select join token from MyWallet

- src/components/lists/TokenListItem.vue
- src/components/modals/SelectTokenModal/SelectTokenModal.vue
We recently added hotkeys for navigating the token select modal. This PR adds further styling to the selected token and token hover states.
Before:
After:
> style: Style token select choice

- package-lock.json
- package.json
- src/components/forms/pool_actions/InvestForm/InvestFormV2.vue
- src/composables/useMyWalletTokens.ts
- src/providers/local/exit-pool.provider.ts
- src/providers/local/join-pool.provider.ts
- src/providers/tokens.provider.ts
Call queryExit and queryJoin less often to reduce the nmbr of calls to Tenderly api
1. When user is changing input amounts queries are debounced, but first query will not fire immediately (`leading` is off)
2. `refetchOnWindowFocus` for queries is disabled, but queries still refetch in the background if Preview Modal is open.
3. Prevent invest form rerender if user tokens array hasn't changed
> Hotfix: Reduce the number of Tenderly API calls

- package-lock.json
- package.json
- src/components/forms/pool_actions/WithdrawForm/WithdrawFormV2.vue
Disable native asset buffer warning in pool exit form
> Disable native asset buffer warning in pool exit form

- src/composables/useGnosisSafeApp.ts
- src/composables/useNetwork.ts
Gnosis safe always loads our app with root url '/'. This prevents loading correct network. Added chainId check so that it automatically switches to correct network url.
> fix: Redirect if on gnosis safe and wrong network

- package-lock.json
- package.json
- src/components/forms/pool_actions/InvestForm/composables/useInvestMath.ts
- src/services/pool/calculator/stable.ts
In stable math we needed to limit decimal places to the token decimals before parsing units again.
n/a
> Hotfix: Fix scaling decimals

- package-lock.json
- package.json
- src/composables/useClaimsData.ts
We perform a pool query to fetch the pools that correspond to the gauges for the claims page. The number of gauges has past 100 but the default limit for the pools query was 100 so for some gauges we didn't have pool information and so didn't display the claimable balance on the claims page. This PR increases the pool fetch limit to 1000 which fixes the problem for the foreseeable future.
n/a
n/a
> Hotfix: increase gauge pool query limit

- package-lock.json
- package.json
- src/lib/config/arbitrum.json
- src/lib/config/polygon.json
These two endpoints were removed in #2717 and #2720 because the API was returning bad data. 
The API was returning bad data because we use alchemy to notify the API to update the pools when a transaction is made with the Balancer vault. This notification was disabled by someone for Polygon and Arbitrum on the weekend, so the pools hadn't been updated since then. I've re-enabled it and pools are up to date again. 
- Ensure that Polygon and Arbitrum pools are being fetched from the API and have sane volumes and APR's (no negative numbers or 0's)
> Hotfix: Re-enable balancer api on Polygon and Arbitrum

- package.json
> Fix: Set eslint max warnings back to 0

- src/composables/trade/useJoinExit.ts
- src/composables/trade/useTrading.ts
When loading swap page, joinExit composable needs to check if a swap is joinExit. This was done with function handleAmountChange(). It can be simplified by only using function getSwapInfo()
> fix: joinExit mount logic

- package-lock.json
- package.json
- src/composables/trade/useCowswap.ts
Cowswap "ExactIn" swap was showing incorrect predicted swap outcome as it was using "beforeFee" rather than "afterFee" option when getting a quote.
> Fix: cowswap preview modal showing incorrect estimate

- src/components/cards/PairPriceGraph/PairPriceGraph.vue
- src/pages/trade.vue
On swap page, in the right gutter, we display a token pair historic price chart. It's possible to extend this chart into a modal. This is now removed as it's been rarely used.
> Chore: removed historic price graph extended view

- package-lock.json
- package.json
- src/components/contextual/pages/pool/PoolCompositionCard/components/TokenBreakdown.vue
- src/components/pool/PoolPageHeader.vue
- src/components/tables/PoolsTable/TokenPills/TokenPills.vue
The token pill symbols in pool lists were defaulting to the onchain symbol attribute and falling back to tokenlist data. This PR reverses that so that it defaults to tokenlist values.
n/a
> Hotfix: default to tokenlists for pill symbols

- src/composables/usePool.ts
- src/locales/default.json
Sorry, I missed this in the review. We need to add a label for factory keys so the title of the pool page is correct. Also, FX pools are more like stable pools in that they don't seem to have weights, so let's treat them like stables.
n/a
> fix: Render FX pools like stable pools

- .eslintrc-auto-import.json
- auto-imports.d.ts
- package-lock.json
- package.json
- src/App.vue
- src/components/_global/BalAccordion/BalAccordion.vue
- src/components/_global/BalAsset/BalAssetSet.vue
- src/components/_global/BalBtnGroup/BalBtnGroup.vue
- src/components/_global/BalCheckbox/BalCheckbox.vue
- src/components/_global/BalSelectInput/BalSelectInput.vue
- src/components/_global/BalStack/BalStack.vue
- src/components/_global/BalTextInput/composables/useInputStyles.ts
- src/components/_global/README.md
- src/components/_global/icons/CompositionIcon.vue
- src/components/_global/icons/NetworkIcon.vue
- src/components/_global/icons/StarsIcon.vue
- src/components/animate/AnimatePresence.vue
The new version of unplugin autoimport supports auto import for vue TS types such us `PropType` or `Ref`.
This PR also removes some of those autogenerated imports.
> Bump unplugin autoimport to 0.14.2

- src/plugins/router/index.ts
- src/plugins/router/nav-guards.ts
Instead of simply rendering the swap page, also update the url to say 'swap' instead of 'trade'. Also included fix to a problem of 'not-found' route getting stuck in a loop.
> Fix: change url when using old format 'trade' route

- package-lock.json
- package.json
- src/composables/swap/useCowswap.ts
- src/composables/swap/useJoinExit.spec.ts
- src/composables/swap/useJoinExit.ts
- src/composables/swap/useSor.ts
- src/locales/default.json
We were logging error contents to the UI in the swap card, even for user cancelled transactions, which results in a huge error message. This PR makes the error message shown to the user more friendly and prevents errors being shown in the case where a user rejects the transaction.
n/a
> Hotfix: handle swap errors

- package-lock.json
- package.json
- src/components/cards/CreatePool/PoolFees.vue
- src/components/forms/AppSlippageForm.vue
The custom input in the multic choice forms were broken. When you input a custom value the onCustomInput method wasn't being triggered and therefore the value wasn't being used and the input didn't change style to suggest it had been used. This PR fixes that even trigger so that custom inputs are respected. This affects to places:|
- The slippage form in the navbar settings dropdown
- The fee selection in the pool creation UI.
n/a
> Hotfix: multi choice custom input

- src/components/contextual/pages/pool/FxPoolWarning.vue
- src/components/contextual/pages/pool/PoolChart.vue
- src/constants/pools.ts
- src/locales/default.json
There may be a case when there are negative swap fees e.g. in FX pools.
See: https://github.com/balancer-labs/balancer-subgraph-v2/issues/366
https://docs.xave.co/product-overview-1/amm#mechanism
Example pool: `0x726e324c29a1e49309672b244bdc4ff62a270407000200000000000000000702`
> Display negative values in fees chart

- package-lock.json
- package.json
- src/components/cards/CreatePool/CreateActions.vue
- src/components/cards/CreatePool/InitialLiquidity.vue
- src/components/cards/CreatePool/PoolFees.vue
- src/components/cards/CreatePool/PreviewPool.vue
- src/components/cards/CreatePool/SimilarPools.vue
- src/composables/approvals/useTokenApprovalActions.ts
- src/composables/pools/usePoolCreation.ts
- src/pages/pool/create.vue
- Removes a lot of animations that were causing re-render bugs. Try creating a pool on Goerli production and notice how the page constantly re-renders and makes it difficult to know what's happening. This was because of AnimatePresence being triggered everytime dynamic data loaded, e.g. balances re-fetched.
- Refactors loading states so we are awaiting the right things.
- Removes unnecessary try/catch blocks for txs that are handled by BalActionSteps.
- Updates pool creation tx notification labels to be more friendly.
n/a
> hotfix: Pool creation flow

- package-lock.json
- package.json
- src/components/contextual/pages/pool/MyPoolBalancesCard.vue
- src/components/contextual/pages/pools/VeBalPoolTable.vue
- src/composables/useLock.ts
We were passing the fiat value to the veBAL pool table on the portfolio page when it expected the BPT. This PR fixes that and the display of the user's lock pool balance on the actually veBAL pool page.
n/a
> Hotfix: vebal table balance

- package-lock.json
- package.json
- src/components/contextual/pages/pools/VeBalPoolTable.vue
- src/composables/useUserPoolPercentage.spec.ts
- src/composables/useUserPoolPercentage.ts
Calculating the user's pool share as a percentage should be done with the totalShares and the user's BPT. The calculation was mistakenly using the pool's totalLiquidity instead of totalShares, this PR fixes that.
n/a
> Hotfix: my pool share values

- package-lock.json
- package.json
- src/components/contextual/pages/pool/PoolStatCards.vue
Similar to #2847 this hides nonsensical values in pool stat cards.
> Hotfix: Fix nonsensical values in pool stat cards

- package-lock.json
- package.json
- src/components/tables/PoolsTable/PoolsTable.vue
- src/composables/usePool.ts
Show a dash for nonsensical values instead of $0 / 0%. This is more clear to users that the number is missing / broken.
> Hotfix: Show a dash instead of 0 for nonsensical values

- package-lock.json
- package.json
- src/composables/usePool.ts
Euler linear pool tokens needed to be returned from the subgraph ordered by index. A fix for this has been included in the SDK and the API, this update just ensures that the fallback will also work. We were also missing the detection of EulerLinear pools in the isLinearPool conditional which has been fixed too.
n/a
> Hotfix: Fix Euler proportional withdrawals

- package-lock.json
- package.json
- src/constants/pools.ts
Exclue Euler linear pools from displaying in tables. Adds label to bb-e-usd pool
> Hotfix: exclude euler linear, add bb-e-usd label

- src/composables/useLock.ts
- src/composables/usePool.ts
- src/composables/useUserPoolPercentage.ts
In the user share percentage calc we were using the lock fiat value in the sum of all the user's shares (i.e. BPT). We should be using the total locked shares amount instead.
n/a
> fix: Use shares not fiat value

- src/components/tables/PoolsTable/PoolsTable.vue
Currently on certain widths of viewport, there are bugs with pools table display. This pr fixes this.
Fixes this ui bugs:
> fix: composition column width in pools table

- src/providers/user-settings.provider.ts
To help protect users we're going to test setting the default slippage to 0.5% instead of 1%.
n/a
n/a
> chore: Set default slippage to 0.5%

- package-lock.json
- package.json
- src/pages/pool/_id.vue
When loading a pool page the price provider warning flashes and then disappears because the prices.value isn't loaded.
Replaces #2930 as hotfix.
n/a
> Hotfix: price alert notification

- package-lock.json
- package.json
- src/composables/contextual/pool-transfers/usePoolTransfers.ts
- src/composables/queries/usePoolDecorationQuery.ts
- src/constants/queryKeys.ts
- src/pages/pool/invest.vue
- src/pages/pool/withdraw.vue
- src/services/pool/decorators/pool.decorator.ts
- src/services/pool/decorators/pool.multicaller.ts
Replaces #2920
We were refetching the pool query every 1 minute in the join/exit flows. This was using the API, but the API pool data can be up to 5 mins old. This PR replaces that query in the join exit flows for a pool decoration query which takes the existing pool object and simply fetches and updates the onchain values every 20s.
Quite difficult to test without logging out the pool object everytime the query runs and looking for updated onchain values.
n/a
> Hotfix: ensure onchain values uptodate in join/exit flows

- src/components/pool/PoolPageHeader.vue
- src/components/tables/PoolsTable/TokenPills/TokenPills.vue
- src/components/tables/PoolsTable/TokenPills/WeightedTokenPill.vue
- src/composables/usePool.ts
- src/composables/useVotingGauges.ts
- src/pages/pool/_id.vue
Improves information around boosted pools, by using leaf tokens in pools list and on pool page header.
TBD
> Chore: improve boosted UI

- package-lock.json
- package.json
- src/constants/pools.ts
Adds metadata for boosted pools.
Check boosted pools in PR appear with name.
n/a
> Hotfix: add metadata

- package-lock.json
- package.json
- src/services/balancer/pools/joins/handlers/generalised-join.handler.ts
Update generalised-join handler to support SDK update that removes unused `wrapLeafTokens` parameter
> Remove wrapLeafToken parameter from generalisedJoin

- package-lock.json
- package.json
- src/components/contextual/pages/pool/PoolStatCards.vue
- src/components/tables/PoolsTable/PoolsTable.vue
- src/components/tooltips/APRTooltip/APRTooltip.vue
- src/composables/usePool.ts
When deciding if an APR is valid we should only check the swapFee APR against the threshold because that is part of an APR that can be unrealistic, if any reward APR results in a number above the threshold it has to be accurate.
n/a
> Hotfix: Use swapFee APR for threshold

- package-lock.json
- package.json
- src/pages/pool/_id.vue
Missing prices alert was appearing at the top of pool pages on reload because prices are loaded async now. This PR insures the `missingPrices` flag is only true if the price query isn't loading.
n/a
> Hotfix: missing prices alert

- src/components/contextual/pages/pool/PoolChart.vue
See title.
Fraction digits here are removed
> feat: remove fraction digits from pool chart current value

- package-lock.json
- package.json
- src/plugins/router/index.ts
Backlinks to old mainnet pool URLs are broken, e.g `app.balancer.fi/#/pool/0x...` doesn't currently redirect to `app.balancer.fi/#/ethereum/pool/0x...`. This PR adds a route to the router to handle this redirect.
Hard to test without pushing to production.
n/a
> Hotfix: old mainnet pool urls

- package-lock.json
- package.json
- src/plugins/router/index.ts
- src/plugins/router/nav-guards.ts
Previous hotfix #2951 broke L2 redirects, e.g. polygon.balancer.fi/#/pool/0x... -> app.balancer.fi/#/polygon/pool/0x... This PR reverts that fix and implements a new one which should handle mainnet without breaking L2s.
Can't test in preview, has to be tested in production.
n/a
> Hotfix: Pool redirect for l2s

- package-lock.json
- package.json
- src/composables/queries/usePoolDecorationQuery.ts
The onchain data updater in the join/exit flow was trying to modify a readonly pool. This PR fixes that by deep cloning the initial pool before decoration.
n/a
> Hotfix: onchain updates

- src/composables/useVotingGauges.ts
Changing the veBAL table to display only the underlying token icons for deep pools causes and error because the gauge pool object we pass in is not a real pool object and doesn't have a tokensList attribute. This caused an error in the underlying tokenTree parsing where we want to remove the pre-minted address from the tree.
n/a
> fix: Set tokensList on fake Pool type

- package-lock.json
- package.json
- src/composables/queries/usePoolsQuery.ts
- src/services/balancer/api/entities/pools/query.ts
- src/services/balancer/subgraph/entities/pools/query.ts
- Some new pools on Gnosis aren't appearing because their totalShares is < 0.01. This will be a general problem with new pools on chains so changing the totalShares minimum to 0.00001 instead.
- This won't affect the main pools list on any other chains, but will affect the filtered pools if there is only a handful as more very low liquidity pools will show in searches.
- Ensure that this pool shows in the main pool list on gnosis chain: https://app.balancer.fi/#/gnosis-chain/pool/0xf48f01dcb2cbb3ee1f6aab0e742c2d3941039d56000200000000000000000012
> Hotfix: Lower min total shares

- package-lock.json
- package.json
- src/lib/config/homestead.json
Disables using the Balancer API on mainnet as the update pools function is currently throwing errors.
> Disable using API on mainnet while pools aren't updating

- package-lock.json
- package.json
- src/composables/queries/usePoolsQuery.ts
- src/services/pool/pools-store.service.ts
Fixes issue when fetching pools list from subgraph and clicking load more causes duplicate pools in list.
n/a
> Fix: duplicate pools issue

- package-lock.json
- package.json
- src/lib/config/homestead.json
The Balancer API was disabled in #3019 because it was having trouble updating pools. This has been fixed now. 
- Ensure all pool information is roughly the same as production.
> Hotfix: re-enable balancer api

- package-lock.json
- package.json
- src/composables/__mocks__/useUserSettings.ts
- src/composables/useSlippage.spec.ts
- src/composables/useSlippage.ts
- src/providers/__mocks__/user-settings.provider.ts
- Slippage adding and subtracting sometimes turns numbers into scientific notation with e+XX on the end which ethers cannot parse causing errors in the frontend. This fixes it by forcing the output to be fixed and also adds tests for this file.
Fixes https://balancer-labs.sentry.io/issues/4004085182/
- Hard to test this because only certain withdraw values trigger it. If tests are passing it should be good as I did TDD on this bug.
> Hotfix: Fix slippage converting numbers into scientific notation

- package-lock.json
- package.json
- src/components/forms/pool_actions/WithdrawForm/components/WithdrawalTokenSelect.vue
- src/components/forms/pool_actions/WithdrawForm/composables/useWithdrawMath.ts
- src/services/pool/exchange/exchange.service.ts
We originally built in a hack to make proportional exits work for ComposableStable pool types that didn't support the exit type needed for proportional exits. This hack breaks proportional exits from these pools when they go into recovery mode and proportional exits are possible. This PR adds `isInRecoveryMode` to all withdrawal math conditionals relevant to this hack.
n/a
> Hotfix: Recovery exits from old composable stable pools

- src/composables/queries/usePoolQuery.ts
- src/composables/queries/usePoolsQuery.ts
- src/composables/queries/useUserPoolsQuery.ts
- src/constants/pools.ts
There are many new Linear pools and different pool types being created (full list here: https://github.com/balancer/balancer-subgraph-v2/blob/master/src/mappings/helpers/pools.ts#L9-L33), almost all of which we don't want to show. Rather than constantly excluding new types it makes more sense to have an included pool types list. 
- Load each pools list on each network. Ensure the list of returned pools is the same as production. 
- Search for different tokens in the pools list, ensure the list of returned pools is the same.
> Change excluded pool types to included

- package-lock.json
- package.json
- src/lib/balancer.sdk.ts
As reported by Tim, some swaps (on Polygon) were failing with `STABLE_GET_BALANCE_DIDNT_CONVERGE`. This was due to a broken Stable pool. PR makes it easy to filter SDK pools using `poolsToIgnore` config setting rather than having to wait for a new SDK package release.
Filters broken pool causing issue originally reported.
You can try adding other pools to list and making sure they don't appear in swap route selected.
> Hotfix: Bump SDK version

- package-lock.json
- package.json
- src/lib/balancer.sdk.ts
SDK config changes were causing swap exits to fail. The config changes were implemented to allow the frontend to more quickly added pool IDs to ignore for the SOR but the ID in question is now handled by default in the SDK so it is no longer required.
n/a
> Hotfix: revert sdk config change

- package-lock.json
- package.json
- src/components/_global/BalActionSteps/BalActionSteps.vue
- src/components/modals/SwapPreviewModal.vue
- src/composables/approvals/useRelayerApprovalTx.ts
- src/locales/default.json
Because actions steps in the swap preview is a computed property based on many other computed properties, it sometimes triggered a watcher of the actions prop in BalActionSteps despite the actions not actually changing. When that watcher was triggered it reset the state of all the BalActionStep actions, so any completed actions looked like they weren't. This PR ensures the action states are only reset if the length of actions passed via props changes. This is only usually the case once, after initial loading of approvals for example.
n/a
> Hotfix: swap approval states

- package-lock.json
- package.json
- src/components/_global/BalActionSteps/BalActionSteps.vue
Fix BalActionSteps so that action states are only injected if it doesn't exist already. We had a bug where the watcher wasn't injecting a state for new actions or it would overwrite existing states.
n/a
> Hotfix: Fix BalActionSteps state injection

- src/components/links/BridgeLink.vue
- src/composables/useNetwork.ts
- src/lib/config/arbitrum/index.ts
- src/lib/config/docker/index.ts
- src/lib/config/gnosis-chain/index.ts
- src/lib/config/goerli/index.ts
- src/lib/config/mainnet/index.ts
- src/lib/config/optimism/index.ts
- src/lib/config/polygon/index.ts
- src/lib/config/test/index.ts
- src/lib/config/types.ts
- src/pages/swap.vue
- Move bridge URL's to config files. 
- Change check for showing bridge information to show if the bridge URL is set instead of using `isL2`
- Ensure that bridge information is shown on the swap screen for Polygon/Arbitrum/Gnosis Chain
- Ensure that bridge information is not shown on Ethereum / Goerli. 
> Move bridge information to config. Change check from isL2 to hasBridge

- src/components/heros/PortfolioPageHero.vue
- src/composables/useLock.ts
- src/composables/useVeBAL.ts
- Add a new boolean isVeBalSupported that is set based on if a veBal address is set in config.
- Wherever we have a veBAL related page (such as locking veBAL, or seeing rewards) use this boolean instead of `isL2`. 
- Ensure that the veBAL page works correctly on Mainnet and Goerli and redirects correctly on other networks.
- Ensure veBAL locked stats show on portfolio page on Mainnet and Goerli
- Ensure the veBAL locked stats do not show on other networks.
> Add new isVeBalSupported boolean using config data instead of isL2

- src/lib/config/arbitrum/index.ts
- src/lib/config/docker/index.ts
- src/lib/config/gnosis-chain/index.ts
- src/lib/config/goerli/index.ts
- src/lib/config/mainnet/index.ts
- src/lib/config/optimism/index.ts
- src/lib/config/polygon/index.ts
- src/lib/config/test/index.ts
- src/lib/config/types.ts
- src/services/coingecko/coingecko.service.ts
- Move coingecko native asset and platformId settings to config files
- Tested by inspecting in browser and comparing the new list to the old one. They are the same except for the inclusion of networks 10 & 17 and removal of network 42. 
- Ensure that tokens load from Coingecko on each network
- Can inspect `coingecko.service` in browser tools to see the list is the same.
> Chore: Move coingecko settings from the service to config files

- src/components/_global/BalBtn/BalBtn.vue
- src/components/_global/BalStack/BalStack.vue
Fix dark border styles of main pools table and `create a pool button` in main page.
> fix: dark border styles in main page

- src/components/links/ApyVisionPoolLink.vue
- src/composables/external/useApyVisionHelpers.ts
- src/lib/config/arbitrum/index.ts
- src/lib/config/docker/index.ts
- src/lib/config/gnosis-chain/index.ts
- src/lib/config/goerli/index.ts
- src/lib/config/mainnet/index.ts
- src/lib/config/optimism/index.ts
- src/lib/config/polygon/index.ts
- src/lib/config/test/index.ts
- src/lib/config/types.ts
- src/services/coingecko/coingecko.service.ts
- Remove the switch statement from APY Vision and move it to config files instead
- Make the link not show on networks that APY Vision doesn't support yet (like Gnosis Chain)
- Ensure APY Vision link shows and works for pools on Ethereum/Arbitrum/Polygon
- Ensure APY Vision link doesn't show on Gnosis Chain as they don't support Balancer pools on it yet.
> Move APYVision details to config

- src/lib/balancer.sdk.ts
- This switch statement isn't needed as chainId is already of type `Network` 
- Ensure SDK functions such as fetching pools for SOR work correctly.
> Chore: Remove switch statement in balancer.sdk.ts

- src/components/navs/AppNav/AppNavNetworkSelect.vue
- src/lib/config/arbitrum/index.ts
- src/lib/config/docker/index.ts
- src/lib/config/gnosis-chain/index.ts
- src/lib/config/goerli/index.ts
- src/lib/config/mainnet/index.ts
- src/lib/config/optimism/index.ts
- src/lib/config/polygon/index.ts
- src/lib/config/test/index.ts
- src/lib/config/types.ts
- Change the AppNavMenu to be built based on configuration settings instead of hard coded. 
Question: The order of these buttons is now different. Do we want them in a specific order? 
- Ensure that only Ethereum, Polygon, Arbitrum, and Gnosis Chain appear in the navigation menu
- Ensure that Goerli appears in the menu in dev mode
- Ensure that all button names look correct and clicking the buttons takes you to the right network.
> Chore: Make AppNavMenu dynamic and based on config

- src/components/btns/ClaimRewardsBtn/ClaimRewardsBtn.spec.ts
- src/components/btns/ClaimRewardsBtn/ClaimRewardsBtn.vue
- src/composables/queries/useProtocolRewardsQuery.ts
- src/composables/useClaimsData.ts
- src/composables/useNetwork.ts
- src/lib/balancer.sdk.ts
- src/lib/config/goerli/tokens.ts
- src/pages/claim/index.vue
- src/services/balancer/contracts/contracts/bb-a-usd-token.ts
- Wherever protocol rewards are shown or the query is run, check if the network has a configured address for protocol rewards instead of the isL2 check. 
- Ensure that protocol rewards are shown on Ethereum 
- Ensure protocol rewards show on Goerli (Goerli didn't show before because there was an explicit !isGoerli check, but I thought they should show for this network as it has gauges and staking just like mainnet). 
- Ensure claim page loads correctly on L2's and no protocol rewards are shown.
> Change protocol rewards checks to config URLs instead of isL2

- package-lock.json
- package.json
- src/composables/useClaimsData.ts
- src/constants/queryKeys.ts
A gauge in the gauges subgraph started returning a poolId of null which broken the gauges query on the claims page. This PR fixes that and cleans up the loading state of the claims page.
> Fix: claims page infinite loading

- src/composables/useNetwork.spec.ts
- src/composables/useNetwork.ts
- src/services/balancer/gauges/gauges.decorator.ts
- src/services/staking/staking-rewards.service.ts
- There were two places still using `isL2` for gauge checks, change these to `networkHasNativeGauges` to be more explicit about what we're searching for. All logical statements are reversed too. 
- Remove the `isL2` variable as it's no longer used.
- Refactor the `networkFor` function to use networks specified in config instead of its own list. 
- Ensure gauge rewards are shown correctly on claim rewards pages for all networks. 
- Ensure boosted rewards are showing correctly for users that have boosts.
> Change isL2 check to networkHasNativeGauges, remove hard coded network switch

- package-lock.json
- package.json
- src/composables/useDisabledJoinPool.spec.ts
- src/composables/useDisabledJoinPool.ts
Conditional to block joins in weighted pools created after timestamp didn't check if the pool was actually a weighted pool. This PR fixes the relevant conditional.
> Fix: Weighted disable join conditional

- src/lib/utils/prefetch.ts
We discovered that in certain scenarios, the code that JSON.parses vite async import can be failing in local. This PR avoids that problem in local devserver while keeps working in production builds.
> fix: Ignore invalid JSON in link prefetch matches

- package-lock.json
- package.json
- src/lib/config/arbitrum/pools.ts
- src/lib/config/gnosis-chain/pools.ts
- src/lib/config/goerli/pools.ts
- src/lib/config/mainnet/pools.ts
- src/lib/config/polygon/pools.ts
Add label keys for weighted v4 pools.
> chore: Add weighted v4 factory key

- package-lock.json
- package.json
- src/lib/config/gnosis-chain/pools.ts
Description
Adds the newly created AGVE GNO pool on Gnosis Chain to the AllowList. See pool: https://app.balancer.fi/#/gnosis-chain/pool/0x388CAE2F7D3704C937313D990298BA67D70A3709000200000000000000000026
> Adds new AGVE GNO pool to AllowList 

- src/lib/config/polygon/index.ts
- src/lib/config/polygon/tokens.ts
The native asset address on Polygon has always been wrong. This didn't matter previously as when fetching prices the SDK had a check for if it's a native asset and to pull from a different Coingecko API, and the balances code just calls `this.provider.getBalance` for the native asset. The default Coingecko API doesn't work with the 0xEee address:
```
> curl "https://api.coingecko.com/api/v3/simple/token_price/polygon-pos?contract_addresses=0x0000000000000000000000000000000000001010&vs_currencies=usd"
{"0x0000000000000000000000000000000000001010":{"usd":0.971639}}
> curl "https://api.coingecko.com/api/v3/simple/token_price/polygon-pos?contract_addresses=0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE&vs_currencies=usd"
{}                                       
```
This is needed for switching …
> Fix polygon native asset address

- package-lock.json
- package.json
- src/data/voting-gauges.json
- src/lib/scripts/voting-gauge.generator.ts
Updates voting gauge generation script to use tokenlists repo instead of assets repo and re-generates the json list.
> Hotfix: Use tokenlists repo for voting gauge list assets

- package-lock.json
- package.json
- src/components/cards/SwapCard/SwapCard.vue
If an invalid asset or address is passed to the swap page it errors and stops working. This also caused the page to become permanently unavailable if a bad asset gets stored in  local storage.  
This PR fixes that bug ensuring that the swap assets are valid token addresses.
Example URL that currently crashes the swap page: http://app.balancer.fi/#/polygon/swap/eth/matic
Fixes: https://balancer-labs.sentry.io/issues/4147784240/?project=5725878
- Try adding different words or tokens to the URL of the swap page, or selecting bad assets, and ensure it doesn't throw errors in the console or fail to load.
> Hotfix: Fix swap page crashing with invalid assets

- src/components/contextual/pages/pool/PoolContractDetails.vue
- src/components/contextual/pages/vebal/LMVoting/GaugesTable.vue
- src/components/pool/PoolPageHeader.vue
- src/components/tables/BalClaimsTable.vue
- src/components/tables/PoolsTable/PoolsTable.vue
- src/composables/usePoolHelpers.spec.ts
- src/composables/usePoolHelpers.ts
- src/lib/config/metadata.spec.ts
- src/lib/config/metadata.ts
- src/services/meta/meta.service.ts
This is a preparatory PR to boost app loading time. 
We want to avoid that router handlers like `meta.service.ts `depend on SDK so that we extract metadata logic to make it independent of global Pool logic. 
At the same time, we move metadata logic closer to the config (metadata is defined in config files) so that there's more cohesion. 
> Extract metadata from pool helpers

- src/components/tables/InternalBalancesTable.vue
- src/lib/config/mainnet/tokens.ts
- src/lib/config/types.ts
- src/locales/default.json
- src/pages/balances.vue
This change is specifically to allow for a redirect to the Euler redeem app for eTokens but could cover other cases where we need to do the same thing but to different URLs.
> feat: Allow redirect for other types of balance withdrawals

- src/providers/tokens.provider.ts
Should fix issue with missing icons for some tokens.
> chore: For fetching metadata only use main balancer tokenlist

- package-lock.json
- package.json
- src/components/_global/BalModal/BalModal.vue
Replaces #3294 
Fixes Safari z-index bug affecting the dark mode modals (like the new accept terms on the Connect Wallet modal).
- Test out the Connect wallet modal in dark mode on Safari (and other browsers)
- Test out other modals across the site to see if anything else breaks as a result.
> hotfix: Fixed z-index safari bug affecting dark mode modals

- src/App.vue
- src/pages/_layouts/index.ts
Instead of loading all the layouts from an index, we use dynamic imports to only load the layout that is needed for the current route. 
It prevents the initial bundle from including all the layouts (and their unique dependencies).
The impact in the bundle size is clear (the biggest bundle chunk goes from ` 2634 kB` to `1335 KB`)
Old build: 
New build:
> Refactor to async layout load

- .github/workflows/checks.yml
- package.json
- scripts/buildWithChunkSizeCheck.mjs
- vite.config.ts
Adds a node script enforcing that our build chunk sizes won't go worst (max chunk size should not be bigger than 750kB).
Our current biggest chunk is 735kB. We set the limit to 700kB in a previous commit to enforce a build failure:
> Fail CI build step if chunks bigger than 750kB

- package-lock.json
- package.json
- src/components/_global/BalAsset/BalAsset.vue
Sometimes when on the pool withdraw page (e.g. https://app.balancer.fi/#/arbitrum/pool/0x32df62dc3aed2cd6224193052ce665dc181658410002000000000000000003bd/withdraw/#/) there is a `BalAsset` being loaded with an undefined address, which cases `getToken` to throw an error. 
I can't figure out where this BalAsset is coming from - it seems to be the Pool icon but the debugger is bad at showing where in the vue file the `BalAsset` is being loaded, so I haven't been able to fix the root cause (maybe someone else knows how?)
This ensures that if a BalAsset is loaded with an undefined address that it doesn't attempt to fetch token info. 
Fixes https://balancer-labs.sentry.io/issues/4165680712/?project=5725878
Withdraw tokens from a pool, ensure that no errors are thrown from loading a token with …
> Hotfix - Ignore BalAsset tokens with undefined address

- package-lock.json
- package.json
- src/providers/local/join-pool.provider.ts
- src/providers/user-settings.provider.ts
Currently, the useSignature user setting is being set as a string but treated as a boolean, we need to add some parsing to ensure it's set as a boolean in state. Also, in the join flow, because approval actions are set with a function call, we need to trigger a recall of that function if the userSignature setting changes.
> Hotfix: Fix useSignatures user setting

- src/components/forms/lock_actions/LockForm/components/LockPreviewModal/components/LockActions.vue
We are already sending fatal errors in the main transaction class, however this could fail earlier so send another fatal with additional data.
> Send a fatal exception to sentry if locking veBal fails

- package-lock.json
- package.json
- src/composables/swap/useCowswap.ts
- src/composables/swap/useJoinExit.ts
- Set error level to `fatal` if a CowSwap or JoinExit swap fails. 
- Send additional information to Sentry to make diagnosing what went wrong easier. 
- Hard to test a failure case, but try performing a cowswap swap or a join/exit swap and ensure they are working correctly.
> Hotfix: Make cowswap and joinexit swaps fatal if they fail

- .github/workflows/tag.yml
- package-lock.json
- package.json
We have many hotfixes coming in each day to add new pools / gauges to the allowlist. Each of these currently requires a patch version bump, but this means as soon as one is merged all the remainder have git conflicts. 
Instead of requiring the version bump in the PR, auto-bump the version on merge to master. This way we can easily merge all these hotfixes without constantly having to rebase and fix them. 
This plugin will not bump weekly releases because it ignores bumping if any of the merged commits already include a version bump (it does a regex search for `\d.\d.\d` as the commit message in any of the commits)
I've tested this on a fork of this repo and you can see how it works doing a weekly release and a hotfix patch here: https://github.com/timjrobinson/frontend-v2/commits/master …
> Hotfix: Auto bump master on hotfix merge

- src/components/contextual/pages/pool/staking/StakePreview.vue
- src/components/forms/pool_actions/InvestForm/components/InvestPreviewModal/components/InvestActionsV2.vue
- src/components/forms/pool_actions/WithdrawForm/components/WithdrawPreviewModal/components/WithdrawActionsV2.vue
- src/components/layouts/FocussedLayout.vue
Disable the Add Liquidity, Withdraw and Staking action steps if the user switches network before clicking it. Currently the button to show the preview modal becomes disabled, but the action steps in the preview modal are not.
I looked into fixing this on the swap page and it seems the swap page auto refreshes to the correct network so it's not needed there. 
Fixes: https://balancer-labs.sentry.io/issues/4173315674/events/85eabaedf7e345999ef3796c3676ffac/?project=5725878&referrer=previous-event - this is caused by the user submitting a transaction to the wrong network, you can see the URL is polygon but at the end of the tenderly simulation URL it is connected to 42161 (arbitrum). 
- Attempt to add liquidity to a pool, get all the way to the last action steps 
- Switch your wallet to …
> Disable actions for add liquidity, withdraw, and staking if user is on wrong network

- src/providers/local/exit-pool.provider.ts
- Set bptInValid to only be true if bptIn amount is > 0 so that users can't start a withdraw for 0 tokens. This value was previously always true. 
Fixes: https://balancer-labs.sentry.io/issues/4000665600/?project=5725878&query=is%3Aunresolved+level%3Afatal&referrer=issue-stream&statsPeriod=14d&stream_index=1 (can see in additional info that bptIn is 0.0. 
- Try withdrawing nothing from a pool. The preview button should now be disabled when you set the slider to 0 BPT.
> Don't allow users to withdraw 0 BPT

- package-lock.json
- package.json
- src/composables/queries/usePoolQuery.ts
We need to inject pool addresses into the token registry so we include it in balance fetching. This is how we know if a user has an unstaked balance in a pool.
> Hotfix: BPT balance fetching

- src/components/_global/BalTable/BalTable.vue
- src/components/contextual/pages/vebal/LMVoting/GaugesTable.vue
- src/components/contextual/pages/vebal/LMVoting/LMVoting.vue
New way of intersection observer implementation, based on `BalTable` row index. It fixes the problem of interaction
between table sorting and dynamic rendering
> feat: optimise vebal table render

- package-lock.json
- package.json
- src/App.vue
Adds app-wide alert for hosted graph downtime.
> Hotfix: Add hosted graph app alert

- package-lock.json
- package.json
- src/services/balancer/gauges/gauges.decorator.ts
Some gauges are returning `null` for claimable rewards which makes the `toString` function crash and cause the rewards page to not load. This fixes that issue by setting the value to `0` if it's null/undefined etc. 
- Ensure claim rewards page on Polygon / Arbitrum / Ethereum are loading correctly.
> Hotfix: Fix claimable rewards crash

- package-lock.json
- package.json
- src/lib/config/mainnet/pools.ts
- src/lib/config/polygon/pools.ts
- Include Gyro2, Gyro3, and GyroE pool types in the main pools list so users can search for them and see them. 
- Search for `stMATIC` on Polygon. Ensure https://app.balancer.fi/#/polygon/pool/0xf0ad209e2e969eaaa8c882aac71f02d8a047d5c2000200000000000000000b49 appears in the list. 
- Sort pools by APR. Ensure that pool is near the top of the list (currently 55% APR)
Other Gyro pools that should now appear in search on Polygon:
```
GyroE
0x97469e6236bd467cd147065f77752b00efadce8a0002000000000000000008c0
0x3f6110b9322bc1633d5f63ccdfdf5dd648588b8a0002000000000000000008e3
0xa489c057de6c3177380ea264ebdf686b7f564f510002000000000000000008e2
0xf0ad209e2e969eaaa8c882aac71f02d8a047d5c2000200000000000000000b49
Gyro2
0xfa9ee04a5545d8e0a26b30f5ca5cbecd75ea645f000200000000000000000798 …
```
> Hotfix - add gyro pool types to pools list

- src/__mocks__/weighted-pool.ts
- src/components/contextual/pages/pool/staking/StakePreview.vue
- src/components/contextual/pages/pool/staking/StakePreviewModal.vue
- src/components/contextual/pages/pool/staking/StakeSummary.vue
- src/components/contextual/pages/pool/staking/StakingIncentivesCard.vue
- src/components/contextual/pages/pool/staking/composables/useStakePreview.spec.ts
- src/components/contextual/pages/pool/staking/composables/useStakePreview.ts
- src/composables/__mocks__/useTransactions.ts
- src/dependencies/contract.concern.mocks.ts
- tests/vitest/assertions.ts
This PR extracts useStakePreview composable to make it more testable and adds tests for covering the different staking flows.
This is the last preparatory PR before safely changing `restake` action to use SDK's `gauge2gauge`.   
> refactor: extract and test useStakePreview

- src/providers/local/exit-pool.provider.ts
- src/providers/local/join-pool.provider.ts
When a tx fails before being submitted, e.g. the query function before a join/exit call, we were logging the params for debugging to Sentry as a JS object. This results in un parsable nested params like [Object] in Sentry. This PR uses JSON.stringify to format params before sending to Sentry.
> chore: Stringify params sent to sentry

- package-lock.json
- package.json
- src/services/balancer/api/entities/pools/query.ts
Fetches poolTypeVersion from the Balancer API as it's needed by the frontend. 
- Load the pools page 
- Ensure that each pool has poolTypeVersion set.
> Hotfix - fetch pool type version

- .github/workflows/tag.yml
This fixes and re-adds the BumpTag action removed in #3477 
It failed because the master branch is protected. I changed it to use a personal access token that I created to get around this restriction. The other changes are making it checkout without default Github credentials, and re-checkout at the end to push to the deploy branch. 
The permissions on the personal access token are:
I'm not sure if all of these are necessary. We could create a balancer bot with these permissions instead of using my token too. 
Tested in my personal fork by protecting my master branch in the same way this repo is protected, then making sure this worked.
> Re-add bump tag

- .github/workflows/tag.yml
Only run the script to push to the deploy branch if the last commit is a tag number.
> Hotfix:  only deploy tagged

- src/pages/claim/index.vue
If pool metadata exists for a pool gauge on the claims page, use it. Previously we were just combining token symbols and weights.
> chore: Use pool metadata for claims page tables

- .github/workflows/tag.yml
- package-lock.json
- package.json
Bumptag has a bug where when you specify `''` for a major bump it takes that to mean "Always major bump becuase this empty string is always found". Which made it bump package.json to 2.0.0.
I patched bumptag to fix this (https://github.com/phips28/gh-action-bump-version/pull/216) and switched to using my fork until this is merged into the main repo. 
See: https://github.com/timjrobinson/frontend-v2/actions/runs/5196894274/jobs/9371076804, it does a patch update as expected.
> Hotfix: Fix bumptag always doing major bumps

- src/providers/local/exit-pool.provider.ts
I could also reproduce this problem once and I couldn't record it but, this is my theory: 
We have [this watche](https://github.com/balancer/frontend-v2/blob/f9d4fbdc281bee57a852d7251ebf01cb29603e0a/src/components/forms/pool_actions/WithdrawForm/components/WithdrawPreviewModal/components/WithdrawActions.vue#L170)r to refetch the `queryExit` whenever the blockNumber changes. 
Although we avoid refetching when `txInProgress.value` there could be an edge case when a pending `queryExit` is executed after the transaction has been confirmed. 
This PR would detect and ignore that case, reducing the number of false positives in sentry.
Please provide any relevant visual context for UI …
> Ignore queryExit error once tx was confirmed

- src/components/forms/pool_actions/WithdrawForm/components/WithdrawPreviewModal/components/WithdrawActions.vue
- src/composables/approvals/useRelayerApproval.ts
- src/providers/local/exit-pool.provider.ts
We were using 2 instances of useApprovalRelayerTx which contains local state. My hypothesis is that the state duplication could lead to some intermittent errors related with the approved state of the relayer. 
> refactor: avoid using 2 useApprovalRelayerTx instances

- src/lib/config/arbitrum/pools.ts
- src/lib/config/gnosis-chain/pools.ts
- src/lib/config/mainnet/pools.ts
Add missing factory addresses to fix unknown pools. 
Fixes "**unknown pool type**" in these pools: 
https://beta-app-v2-git-fix-unknown-pool-type-balancer.vercel.app/#/arbitrum/pool/0x542f16da0efb162d20bf4358efa095b70a100f9e000000000000000000000436
https://beta-app-v2-git-fix-unknown-pool-type-balancer.vercel.app/#/gnosis-chain/pool/0xbad20c15a773bf03ab973302f61fabcea5101f0a000000000000000000000034
> Add missing ComposableStable v4 factory addresses to fix unknown pools

- src/components/contextual/pages/vebal/LMVoting/GaugesFilters.vue
- src/components/contextual/pages/vebal/LMVoting/LMVoting.vue
- src/composables/useNetwork.ts
- Refactor the filter list on the veBAL gauge page to use config settings so that it automatically adds new networks that are not test networks and have pools users can vote for.
- This will show zkEVM once we add gauges people can vote for to the list. 
- Load the veBAL page
- Attempt to filter by a network
- See same networks are present as before with same names
> Make veBAL gauge filter run via config

- src/lib/config/polygon/keys.ts
- src/lib/config/zkevm/keys.ts
When setting up zkEVM I somehow switched the keys around for these networks. I think I copied the zkEVM keys from Arbitrum initially then when updating its keys I accidentally updated the Polygon PoS keys file instead. 
Infura doesn't support Polygon zkEVM yet so I removed that, and switched the alchemy keys back to what they should be for each network.
- Check the frontend Polygon PoS and frontend Polygon zkEVM keys in Alchemy. They should corrospond to the ones in this PR.
> Hotfix - switch Polygon PoS/zkEVM keys

- src/components/_global/BalActionSteps/BalActionSteps.vue
Removes the post-action validation as it's causing issues for some users. 
- Perform a swap or join.
- Ensure users are able to successfully swap or join without error.
> Hotfix - remove post validation

- src/lib/config/arbitrum/index.ts
- src/lib/config/gnosis-chain/index.ts
- src/lib/config/goerli/index.ts
- src/lib/config/mainnet/index.ts
- src/lib/config/optimism/index.ts
- src/lib/config/polygon/index.ts
- src/lib/config/types.ts
- src/lib/config/zkevm/index.ts
- src/lib/scripts/voting-gauge.generator.ts
There were some hardcoded networks in the voting gauge generator. I moved this info to config files so that it supports new networks automatically. 
I also found this script doesn't work for me with NodeJS 18. Ethers always complains about no connection. So I've added a check for that so others don't run into issues. 
- Create voting gauges
- Ensure they are generated correctly for all networks
> Move Voting Gauge Generation config to files

- src/components/contextual/pages/vebal/Hero.vue
Updated the veBAL learn more link to point to the correct place in the docs.
Click the learn more link. It should now go to: https://docs.balancer.fi/concepts/governance/veBAL/
> Fixed broken veBAL learn more link

- .github/workflows/allowlist-manual.yml
- .github/workflows/allowlist-webhook.yml
- .github/workflows/allowlist.yml
This adds a webhook so that we can create a pool allowlist request when new pool create transactions come in. These transaction notifications come from Hal.xyz and are sent to a lambda on the Balancer API that then calls this webhook with the correct parameters. 
I've made the allowlist code more generic so it can be called from either the manual workflow or the automatic one. 
- This can be manually tested with curl by forking this repo, creating a personal access token with webhook request, and running the following replacing `myGithubPatToken` with your token, and `timjrobinson` with your github username:
```
curl -X POST -H "Authorization: token myGithubPatToken" https://api.github.com/repos/timjrobinson/frontend-v2/dispatches --data '{"event_type": "allowlist_pool", "client_payload": …
```
> Add webhook to allowlist pools

- src/components/_global/BalActionSteps/BalActionSteps.vue
- src/composables/approvals/useTokenApprovalActions.ts
- src/composables/queries/useAllowancesQuery.spec.ts
- src/providers/__mocks__/tokens.provider.fake.ts
- src/providers/tokens.provider.ts
This adds the post allowance validation from #3515 back into BalActionSteps. 
It had a bug previously where no one was able to stake their BPT because we didn't think they had allowed it to be spent. This happened because the allowances query only checks spenders of the vault, wstETH and veBAL. It doesn't check if a gauge can spend a users BPT. 
The bug was fixed by allowing injecting of new spenders, and injecting the gauge into the spenders list before the user stakes their BPT. 
I renamed `allowanceContracts` to `spenders` as that's how the ERC20 standard refers to them, it made it less confusing to understand, and they might not be contracts (you can allow normal EOA's to be a spender of your tokens). 
This also fixes a minor bug we didn't notice before: Users had to re-allow their …
> Fix allowance validation when staking in gauges

- src/composables/approvals/useTokenApprovalActions.ts
- src/lib/config/gnosis-chain/index.ts
- Refetch allowances before running the `isApprovalValid` action as sometimes it won't pick up the newly approved allowance (especially on Gnosis chain).
- Switch Gnosis chain to the official RPC as it seems to be more reliable than pokt. 
- Join a pool or stake on Gnosis Chain
- Ensure you don't get any errors about not having enough allowance.
> Hotfix - Improve allowance check on Gnosis Chain

- src/providers/tokens.provider.ts
Remove sentry log when price is not found for a token, as it's very noisy.
> Remove price info sentry log

- src/components/forms/lock_actions/LockForm/components/LockPreviewModal/components/LockActions.vue
- src/providers/local/join-pool.provider.ts
When a user rejects a join or lock transaction it still logs an error to sentry. Add additional checks for these errors to skip logging them. 
Fixes https://balancer-labs.sentry.io/issues/3905587191/?project=5725878&query=is%3Aunresolved+level%3Afatal&referrer=issue-stream&statsPeriod=14d&stream_index=2
- Perform a join transaction and reject it when the metamask window pops up. Ensure that this rejection is not logged to Sentry
> Ignore user errors in more places

- src/components/contextual/pages/claim/LegacyClaims.vue
- src/composables/swap/useCowswap.ts
- src/composables/swap/useJoinExit.ts
- src/composables/swap/useSor.ts
- src/composables/useTransactionErrors.spec.ts
- src/composables/useTransactionErrors.ts
- Rename useTransactions where it's misspelt
- Rename test file from user -> use. 
- Add more test cases for user errors found in sentry. 
- Change checks to regexes so they can match part of the error string instead of having to be an exact match.
> More ignoring of user errors and improvements to error handling

- src/composables/useTransactionErrors.ts
> Add a filter for insufficient funds

- src/components/forms/pool_actions/AddLiquidityForm/AddLiquidityForm.vue
- src/services/balancer/pools/joins/handlers/generalised-join.handler.spec.ts
- src/services/balancer/pools/joins/handlers/generalised-join.handler.ts
- tests/unit/builders/signer.ts
> feat: re-enable native asset joins for deep pools

- src/components/forms/lock_actions/LockForm/components/LockPreviewModal/components/LockActions.vue
- src/composables/swap/useCowswap.ts
- src/composables/swap/useJoinExit.ts
- src/composables/swap/useSor.ts
- src/composables/useTransactionErrors.ts
- src/providers/local/join-pool.provider.ts
- src/services/web3/transactions/concerns/transaction.concern.ts
There are more errors than just user-rejected errors that are triggered by the user and that we shouldn't treat as transaction errors. This PR adds a new function to capture them all and replaces the usage of the user-rejected function instead.
> refactor: Catch all user triggered errors

- src/App.vue
- src/components/contextual/pages/pool/MyPoolBalancesCard.vue
- src/components/layouts/DefaultLayout.vue
- src/composables/queries/usePoolQuery.ts
- src/pages/_layouts/DefaultLayout.vue
- src/pages/_layouts/PoolLayout.vue
- src/pages/pool/_id.vue
- src/plugins/router/index.ts
- src/providers/local/pool.provider.ts
- src/providers/tokens.provider.ts
- Uses pool provider on pool page.
- Refactors layouts so that pool page + nested join/exit flows use the same layout and providers.
- Optimises tokens provider to avoid running queries before vebal has been injected.
- Optimises usePoolQuery to not wait for token injection, this used to be important when prices were also dependent on token injection.
> refactor: Optimise pool page queries

- src/composables/queries/useAllowancesQuery.spec.ts
- src/composables/queries/useAllowancesQuery.ts
- src/composables/queries/useBalancesQuery.spec.ts
- src/composables/queries/useBalancesQuery.ts
- src/providers/tokens.provider.ts
I introduced a bug by enabling balance/allowance queries with the query options object where it bypassed the wallet is connected check. So it was trying to fetch balances/allowances for accounts when no wallet was connected. This PR cleans up that code.
> fix: Pass isEnabled to balance/allowance queries

- src/plugins/sentry.ts
Ignores specific sentry error via config.
> chore: Ignore specific sentry error

- src/assets/css/global/fonts.css
Fixes a lighthouse warning about loading fonts.
> chore: Improve font loading

- package-lock.json
- package.json
- src/lib/config/mainnet/pools.ts
Origin https://github.com/balancer/frontend-v2/pull/3671
> Release/1.112.0 (DM)

- package-lock.json
- package.json
Changes pools multicall to helper contract fetch, quite a big change so could be some issues. Needs testing.
> chore: Bump SDK

- src/components/contextual/pages/vebal/LMVoting/GaugeVoteModal.vue
- src/components/contextual/pages/vebal/LMVoting/SubmitVoteBtn.vue
The submit vote button wasn't updating after a successful transaction because at some point the receipt prop had been removed. The button requires the transaction receipt state in order to present the confirmation indicator and button to close the modal instead of a button that prompts the user to resubmit the vote.
> chore: Pass reciept to submit vote button

- src/components/forms/pool_actions/AddLiquidityForm/AddLiquidityForm.vue
- src/providers/local/join-pool.provider.ts
- src/providers/tokens.provider.ts
Might fix: https://balancer-labs.sentry.io/share/issue/4078ca967f574832828e73caf59b44b4/
- Ensures setAmountsIn is never called with an empty array on mounting components.
- Adds extra guard for join query after approval action promise.
It's difficult to replicate this issue. I only replicated by keeping the add liquidity page open for a long time, leaving it un focused and then returning. My guess is that some kind of re-render caused the setAmountsIn to be reset as empty during a call to query the join.
> fix: Missing tokens join call

- src/composables/swap/useSor.ts
- src/lib/utils/errors.ts
- src/services/contracts/vault.service.spec.ts
- src/services/contracts/vault.service.ts
- src/services/web3/transactions/concerns/contract.concern.ts
> Improve Sentry error logging readability

- src/composables/useTransactionErrors.ts
- src/services/web3/transactions/concerns/transaction.concern.ts
> hotfix: skip faucet refill error

- src/services/rpc-provider/rpc-provider.service.spec.ts
- src/services/rpc-provider/rpc-provider.service.ts
zkEVM wasn't running scripts that update on every new block because it didn't have a websocket provider and we initialize our block counter via getting the current block number from the websocket provider (we used to listen to all blocks this way which is why we used websocket provider in the first place, but then we switched to an interval to save on Alchemy costs). 
Switching the provider to the normal RPC provider so blocks update on networks without a websocket provider set. 
- Ensure that block numbers are increasing via putting a breakpoint in this code on each network. Ensure the current block number is correct from the jsonRPC provider.
> Hotfix: Use JsonRpc provider for initial block number

- src/components/cards/CreatePool/PreviewPool.vue
- src/composables/pools/usePoolCreation.ts
- The token allowance checks in pool creation were using scaled values when the allowance checker wants unscaled values. I noticed this when doing a swap it was checking for `0.5` BAL but when creating a pool it was checking for `500000000000000000` BAL being available. This meant the pool creation UI was only working when users had approved UINT256MAX amounts for their tokens, if they used the Metamask max value it thought they hadn't approved enough. 
Fixes a bug reported in Discord about having allowance issues creating a pool on Arbitrum. 
- Test creating a new pool in production arbitrum / polygon and only approving the amount of tokens required. It should error that the amount approved wasn't enough and continually ask for approval. 
- Test creating that same pool on this branch, …
> Hotfix - fix create pool allowances

- src/components/_global/BalActionSteps/BalActionSteps.vue
- src/components/contextual/pages/pool/staking/composables/useStakePreview.spec.ts
- src/components/contextual/pages/pool/staking/composables/useStakePreview.ts
- src/components/forms/pool_actions/AddLiquidityForm/components/AddLiquidityPreview/components/Actions.vue
- src/components/forms/pool_actions/WithdrawForm/components/WithdrawPreviewModal/components/WithdrawActions.vue
- src/composables/useNetwork.ts
- src/composables/useTransactions.ts
It's possible that zkevm rpc state mismatches/caching are causing problems with submitting transactions before approvals are finalized. Like we had already done for Polygon PoS, this PR introduces a 10 confirmation wait before we consider a tx finalized on zkevm.
Additionally, txListener was being used at two levels in several flows, we only need to listen in BalActionSteps and then emit the events to be handled at a higher level. This has been refactored where relevant.
> fix: zkevm tx confirmation callback

- src/lib/config/arbitrum/pools.ts
- src/lib/config/mainnet/pools.ts
- src/lib/config/polygon/pools.ts
Add Composable Stable V5 factory to pools list so pools created by it show as ComposableStable type instead of unknown type. 
- Visit recently created Composable Stable pools (See https://github.com/balancer/frontend-v2/pull/3685/files) and ensure they show as ComposableStable type and not Unkonwn Type
> Hotfix: Composable stable v5 factory

- src/components/forms/lock_actions/LockForm/components/LockPreviewModal/components/LockActions.vue
- src/composables/swap/useJoinExit.ts
- src/providers/local/exit-pool.provider.ts
- src/providers/local/join-pool.provider.ts
- src/services/web3/transactions/concerns/contract.concern.ts
- src/services/web3/transactions/concerns/raw.concern.ts
We log out Goerli errors as fatal, when no one is losing money on them and they could be due to all kinds of bad state issues. 
I was thinking we could ignore them entirely but we might want to keep track of them to ensure *everyone* isn't having issues. So instead just make them error instead of fatal. 
- Perform normal transactions on Goerli / Mainnet and ensure they work as expected
> Hotfix: Downgrade testnet failures to 'error' instead of 'fatal

- src/components/_global/BalActionSteps/BalActionSteps.vue
- src/lib/utils/errors.ts
Improves original error reporting to Sentry and ensures all BalActionStep errors are recorded as `fatal`.
> fix: Original error recording

- src/components/cards/SwapCard/SwapCard.vue
- src/components/modals/SwapPreviewModal.vue
- src/composables/approvals/types.ts
- src/composables/approvals/useTokenApprovalActions.ts
- src/composables/swap/useSwapping.ts
- src/lib/utils/balancer/lido.ts
- src/locales/default.json
Refactor swapping to use TokenApprovalActions so that it checks the user has made their allowance high enough to swap their token. Tested on Goerli and Polygon and it appears to work for me. 
Also tested wrapping/unwrapping stETH/wstETH on Goerli and it worked correctly.
- Test swapping when not enough is approved, it should ask for approval
- Test approving not enough, it should error that the amount approved wasn't high enough
- Test approving enough to swap, it should allow you to swap correctly. 
- Test wrapping/unwrapping stETH / wstETH to ensure it works correctly (approval should go to the wstETH contract).
> Hotfix: Add approval check to swap

- src/lib/utils/errors.ts
Extends Error class correctly for Sentry so the correct stack trace is provided. Stack traces are the primary source for grouping in Sentry.
https://develop.sentry.dev/grouping/#stack-traces
> Hotfix: sentry error extension

- src/constants/queryKeys.ts
- src/providers/local/exit-pool.provider.ts
We should re-trigger exit queries, in particular, the single exit max query, when the user's wallet changes.
> Hotfix: Re-trigger exit queries on wallet change

- src/data/voting-gauges.json
- src/lib/scripts/voting-gauge.generator.ts
We updated the chain names on Subgraph to match on-chain gauge type names. Most of the networks didn't have issues, except zkEVM where the gauge type is different from the short name we have on config files. Since this is moving to Beets API I just made a quick fix.
> hotfix: fix zkevm voting gauges

- src/lib/utils/errors.ts
After multiple tests I found that using `error.stack` instead of `captureStackTrace` works better to keep the stack trace in our sentry errors. 
Tested with chrome, firefox, edge and safari with a real vite build.
This is the issue stacktrace where I manually triggered an ether's `division by zero` inside `contract.concern.ts`:
It adds the original's error stack trace but excludes the `captureBalancerException` which will be common to all `SentryError's` so IMO is not worthy no be included. 
I would merge this PR and start checking if it groups issues better than the old system (I just tested it with some trivial examples). If not, maybe we can try to fine tune them in sentry setup. 
Please provide instructions so we can test. Please also list any relevant details for your test …
> Fix: use stack instead of captureStackTrace

- .github/workflows/tag.yml
Switching the Github Personal Access Token used in the BumpTag action from my personal one to one generated from @balopco user. It has the same permissions.
> Hotfix - Change the PAT the BumpTag action uses

- src/components/forms/pool_actions/WithdrawForm/components/WithdrawTotals.vue
- src/providers/local/exit-pool.provider.ts
We were allowing exit queries for invalid amounts out like 0 or amounts greater than the user's balance and therefore greater than the pool balance for that token. This allowed failed to construct exit errors. This PR prevents the queryExit function from running if single asset exits have invalid amounts and provides a mechanism for setting the price impact to `-` instead of 0 unless a value is explicitly returned from a queryExit.
> hotfix: Don't query exit if invalid amounts out

- src/components/forms/pool_actions/WithdrawForm/WithdrawForm.vue
ComposableStable pools allow exiting with a token swap (in single token tab) but not in recovery mode, which was causing errors.
This fix limits the single exit token list to the tokens in the current pool when the pool is in recovery mode: 
Example with ComposableStable arbitrum pool in recovery mode:
.../#/arbitrum/pool/0xfb5e6d0c1dfed2ba000fbc040ab8df3615ac329c000000000000000000000159
https://github.com/balancer/frontend-v2/assets/1316240/66508731-0ebf-4851-9a19-95fc6d0044e8
> Fix: single token exit only allows pool tokens subset when the pool is in recovery mode

- src/composables/swap/useSor.ts
When doing the bnum() parse on small numbers 1e-7 or less, the output is exponential notation, which causes errors in the parse. This parse is not needed, there is a check further down to ensure the amount does not exceed decimals
> Remove bnum parse, creates an issue with small number 1e-7 or smaller

- src/components/contextual/pages/claim/LegacyClaims.vue
- src/components/contextual/pages/vebal/cross-chain-boost/SyncNetworkAction.vue
- src/components/forms/pool_actions/WithdrawForm/WithdrawForm.vue
- src/components/forms/pool_actions/WithdrawForm/components/WithdrawPreviewModal/WithdrawPreviewModal.vue
- src/composables/approvals/useRelayerApprovalTx.ts
- src/composables/approvals/useTokenApproval.ts
- src/composables/swap/useJoinExit.ts
- src/composables/swap/useSor.ts
- src/composables/useEthers.ts
- src/pages/pool/withdraw.vue
I believe some errors are due to users accessing the withdraw form when they have a 0 BPT balance.
- Before mounting withdraw page, check if user has BPT, if not redirect to pool page
- After a successful withdrawal, if the user tries to close the modal, check if they have any remaining BPT, if not rediect to pool page.
> Hotfix: Block all access to withdraw page if BPT 0

- src/lib/utils/errors.ts
We shouldn't send user rpc issues as fatal to Sentry.
Fixes https://balancer-labs.sentry.io/issues/4325926774/?alert_rule_id=14519929&alert_type=issue&project=5725878
> Hotfix: Ignore user rpc issues

- src/lib/config/mainnet/pools.ts
- src/locales/default.json
Add/Update migration announcements for sfrxETH and wstETH pools
- [] Bug fix (non-breaking change which fixes an issue)
> chore: Add/Update migration announcements for sfrxETH and wstETH pools

- src/plugins/router/index.ts
- vercel.json
Avoids a 404 when vercel tries to redirect to a page without hash. 
When detecting a route without hash, it redirects to home page instead (clearing the malformed url path).
I tried to redirect to the intended route instead of to home but I didn't find a solution that doesn't involve a non-trivial router setup refactor. 
Example failing in production: 
https://app.balancer.fi/ethereum/pool/0x32296969ef14eb0c6d29669c550d4a0449130230000200000000000000000080
Same example working in preview:
https://beta-app-v2-git-fix-routes-without-hash-balancer.vercel.app/ethereum/pool/0x32296969ef14eb0c6d29669c550d4a0449130230000200000000000000000080
Please provide any relevant visual context for …
> fix: detect and clean routes without hash

- src/providers/local/pool-staking.provider.ts
This error about a pool not having a preferential gauge is hard to debug and rare, I've added in the poolId so we can debug further next time it comes up.
> Hotfix: make error more specific

- src/services/web3/transactions/concerns/contract.concern.ts
In this fatal error: https://balancer-labs.sentry.io/issues/4328790230/events/bd1f6774d328402085a07c2f83c17c33/ when gathering metadata about the error getting the signing account threw an additional error which was then reported to Sentry instead of the original. 
This PR adds a try/catch around this metadata gathering to stop it from re-throwing so that we can see the original error. Also adding a console.error so we can see that in the logs for more info.  It still returns the metadata it can.
> Catch metadata collection fetching errors

- src/providers/local/exit-pool.provider.ts
- src/services/balancer/pools/exits/handlers/exact-out-exit.handler.ts
If the single asset to withdraw with is one of the high-level pool tokens, we shouldn't be using swap exits. This PR also fixes and underlying issue with the exact out handler where `buildExitExactTokensOut` needs to have the BPT removed from the `pool.tokensList` attribute.
> fix: Exact out handler

- src/services/web3/transactions/concerns/contract.concern.ts
- src/services/web3/transactions/concerns/raw.concern.ts
Error types returned from transaction failures can't be relied on, sometimes they're read-only, sometimes just strings. This causes the setting of metadata on the error class to fail. This PR wraps the setting of metadata in a try/catch. These failures are quite rare so the missing metadata shouldn't be a big loss in Sentry.
> fix: Catch errors setting metadata

- src/components/forms/lock_actions/LockForm/components/LockPreviewModal/components/LockActions.vue
We weren't waiting for approval actions to be injecting in lock modal, so it was possible for a user to click the lock action before approvals appeared, which causes failed transactions.
> fix: Wait for approval actions in lock modal

- src/components/forms/pool_actions/WithdrawForm/WithdrawForm.vue
- src/providers/local/exit-pool.provider.ts
We are setting the single asset exit default token to the wrapped native asset in cases where swap exits were not possible. This PR updates the conditional so that it defaults to the first token list token if swaps are not possible.
> fix: Only set single asset exit default to wrapped if swaps possible

- src/components/forms/lock_actions/LockForm/components/LockPreviewModal/components/LockActions.vue
Once we extend lock period, we need to refetch sync data, to prevent showing wrong networks sync state
> fix: bug with synced networks after lock

- src/lib/config/avalanche/pools.ts
Add Factory for Avalanche FX pools
- Ensure the pool `0x55bec22f8f6c69137ceaf284d9b441db1b9bfedc000200000000000000000011` on Avalanche shows FX pool type instead of unknown
> Add Factory for Avalanche FX pools

- src/components/contextual/pages/pool/PoolContractDetails.vue
Adds  `maximumFractionDigits: 4,` to swapFees fNum.
Fixes format for old reported pool
https://beta-app-v2-git-fix-swap-fee-label-balancer.vercel.app/#/ethereum/pool/0x5aee1e99fe86960377de9f88689616916d5dcabe000000000000000000000467
and new reported pool:
https://beta-app-v2-git-fix-swap-fee-label-balancer.vercel.app/#/ethereum/pool/0x08775ccb6674d6bdceb0797c364c2653ed84f3840002000000000000000004f0
> Fix swapFees percentage label

- src/lib/config/avalanche/pools.ts
Makes FX/Gyro pools redirect to their site instead of allowing investing on Balancer site. This should really be a global config option instead of per network but fixing this on Avalanche for now. 
Test the pool `0x55bec22f8f6c69137ceaf284d9b441db1b9bfedc000200000000000000000011` on Avalanche shows a link to invest at Xave insetead of an invest/withdraw form.
> Add branded redirects for pools on Avalanche

- src/providers/local/exit-pool.provider.ts
When debugging https://balancer-labs.sentry.io/issues/4336208103/events/fb62e964fc49457088b1f6f99168c9bb/ I noticed that the error is that `tokenInfo` doesn't contain the EEE token. However in the error info logged to Sentry (down the bottom) the EEE token is included in the object, so the array was fixed in between calling `queryExit` and logging the error. 
This object is created dynamically from multiple vue reactive objects so my best guess is that the state hadn't fully synced across those vue objects before it was sent to `queryExit`. I've added a await nextTick to ensure that all vue state has synced first which should hopefully fix this. 
Nobody has been able to reproduce this bug yet as it's a race condition, but if everything is working with this PR hopefully we won't see it …
> Hotfix: Await next tick when exiting pool

- src/components/contextual/pages/vebal/cross-chain-boost/CheckpointGaugeModal.vue
- src/components/contextual/pages/vebal/cross-chain-boost/SyncNetworkAction.vue
- src/components/forms/lock_actions/LockForm/components/LockPreviewModal/components/LockActions.vue
- src/components/forms/lock_actions/UnlockForm/components/UnlockPreviewModal/components/UnlockActions.vue
Actions should be disabled if network is mismatched
> Hotfix: mismatch network error

- src/components/forms/pool_actions/WithdrawForm/WithdrawForm.vue
In a fix last week I limited the withdrawal form to the pool.tokensList if the pool is in recovery mode to fix another bug. This caused the single asset exit form to default to withdrawing with the pool's pre-minted BPT which is impossible. This PR ensures the tokensList in the withdrawal form always excludes the pre-minted BPT.
> hotfix: Remove pre-minted BPT from withdrawal options

- src/components/forms/pool_actions/WithdrawForm/WithdrawForm.vue
- src/providers/local/exit-pool.provider.ts
We were preventing single asset swap exits from composable stable pools in non-pool tokens if the pool was in recovery mode. I think this should be changed to if the pool is in recovery mode and is paused. It's possible to swap exit from pools in recovery mode, so I don't think we should block it for some edge cases where this might break.
> hotfix: Single asset exit options

- src/components/contextual/pages/pool/staking/StakePreview.vue
- src/components/contextual/pages/pool/staking/composables/useStakePreview.ts
In https://balancer-labs.sentry.io/issues/4366114128/events/cd83eac018dc40009a09ddbe5d07ee25/ the user went to unstake but it errored that there were no gauges available. This is because the `poolGaugesQuery` was still loading and `useStakePreview` doesn't wait for it. 
This PR makes `useStakePreview` check if `pool-staking` is still loading and doesn't allow the BalActionSteps to continue if it is loading. 
- Test staking / unstaking pool BPT. It should allow both. It may show loading for longer now than in production because it's waiting for that subgraph query to return, but that's ok.
> Wait for pool-staking to finish loading before allowing unstaking

- src/pages/index.vue
Adds 50/50 function to decide whether to display base or avalanche promos.
> feat: Alternate between promos

- src/lib/config/base/index.ts
Adds https in front of the base bridge URL so that it goes to another website instead of a page on app.balancer.fi
- Go to swap page on base
- On the bridge card in the bottom right hand corner, ensure the link goes to the bridge correctly.
> Fix base bridge URL

- src/lib/config/arbitrum/index.ts
- src/lib/config/base/index.ts
- src/lib/config/gnosis-chain/index.ts
- src/lib/config/optimism/index.ts
- src/lib/config/zkevm/index.ts
Min tx buffers were all the same as mainnet, this PR lowers the buffer for L2s.
> fix: Set lower min tx buffers on L2s

- src/components/contextual/pages/vebal/LMVoting/GaugesTable.vue
We [used to pin vebal gauge](https://github.com/balancer/frontend-v2/pull/1786) in the voting list but we don't need that anymore. 
Deleteing the old harcoded gauge address to avoid confusion.
- [] Other
> Remove old vebal gauge address from pinnedData

- src/components/tooltips/APRTooltip/components/StakingBreakdown.vue
Shows the reward tokens APR breakdown for pools that have no BAL emission.
Before:
After:
> fix reward tokens apr breakdown

- .github/workflows/allowlist-manual.yml
- src/lib/scripts/automatic-prs/allowlist-pool.ts
Auto-generated PRs like [this one](https://github.com/balancer/frontend-v2/pull/3928) pointed to a broken url in `Link to Pool` link because they were using `mainnet` instead of `ethereum`
This PR fixes the problem while keeping compatibility with the old `mainnet` value for the `network` option. 
> fix: ethereum pool links in auto allowlist PRs

- src/components/forms/pool_actions/WithdrawForm/WithdrawForm.vue
- src/providers/local/exit-pool.provider.ts
Limit swap withdrawals to deep pools. Previously we were injecting all the possible swap tokens for withdrawing under different conditions to enable the swap exits. This PR unifies the two conditionals.
> fix: Limit swap exits

- src/composables/useDisabledJoinPool.spec.ts
- src/composables/useDisabledJoinPool.ts
We shouldn't show the "Tokens not on allowlist" message on testnets, so that other teams can quickly test pools with their own test tokens without waiting on us to add them to the tokenlist. 
- Visit a sepolia pool like `0x2ea0b1475f2864de2c6de25fc93ed588b99a625700000000000000000000002a`. It should not give any warnings about missing tokens. 
- Pools with unverified tokens on normal networks should still show the warning.
> Hotfix: allow all tokens on testnet

- src/lib/utils/errors.ts
- src/providers/wallet.provider.ts
We were only setting the user's wallet network as a tag. This PR now sets two tags, one for `walletNetwork` and one for `appNetwork`.
> chore: Set two separate tags for wallet vs app network

- src/lib/config/arbitrum/pools.ts
@Tritium-VLK mentioned some users were having issues with this pool, temporarily disabling investing until they're resolved.
> Hotfix: Disable investing in USD overnight pool

- src/components/contextual/pages/pool/PoolCompositionCard/components/composables/useTokenBreakdown.ts
Fixes balances of tokens that have a priceRate. Previously we were multiplying the balance by priceRate when showing it in the UI which didn't make sense and also made the USD value look incorrect. Now we're just showing the raw balances. 
Also fixes a very minor issue that it was returning token.balance instead of token.balance * shareOfPoolInParent for pools that weren't deep + rateProvider. But I believe every composable pool that this effects has a priceRate so it doesn't really change anything. 
- Visit a metastable pool like ETH/rETH
- Calculate the token value by dividing Value / Balance. This value should equal Coingecko.
> Fix values of tokens with a priceRate on pool page

- src/components/_global/BalAlert/BalAlert.vue
- src/constants/local-storage.keys.ts
- src/pages/recovery-exit/UserInvestedInAffectedPoolAlert.vue
- Makes BalAlert dismissable
- Makes recovery exit warning dismissable and saves in local storage.
> hotfix: Make warning dismissable

- src/services/web3/connectors/trustwallet/walletconnect.connector.ts
Adds new chains (avalanche and base) to wallet connect optional chains. 
When connecting with ledger live, it is mandatory to check Ethereum checkbox (as well as the other desired networks).
https://github.com/balancer/frontend-v2/assets/1316240/0f73c668-8632-42a4-9325-59c18da203c2
We tried removing the mandatory `chains: [MAINNET]` option from wallet connect options but it did not work.
> Fix: wallet connect chain options

- src/pages/recovery-exit/components/UnstakeTable.vue
Some pools in the unstake list were appearing as 'mitigated' when they should have been labelled 'high risk'. The only way this can happen is if the `poolIdFor` function doesn't return the correct pool ID for the gauge token. I believe the only way that could happen is if we're comparing checksum vs lowercase addresses.
> hotfix: Use lowercase for comparison to find pool ID

- src/composables/queries/usePoolsQuery.ts
[This code ](https://github.com/balancer/frontend-v2/blob/7b60d27d0765fd0e42d20bf2e7b5ec6a631c0b3d/src/composables/queries/usePoolsQuery.ts#L222)disables pools query when `!options.enabled` so we need a default value when enabled option is not provided from the consumer like in [this case](https://github.com/balancer/frontend-v2/blob/7b60d27d0765fd0e42d20bf2e7b5ec6a631c0b3d/src/composables/pools/usePools.ts#L37).
> fix: add enabled default option to usePoolsQuery

- src/providers/wallet.provider.ts
When testing with walletconnect I noticed the walletNetwork tag was not being updated when changing network in your wallet. This is causing the users wallet network to be reported incorrectly. 
Also switches it to network slug to be consistent with appNetwork, and fixes a bug where this would error if the user is connected to a network we don't support. 
- Add a breakpoint in the watch statement
- Change networks in your wallet and ensure it hits the breakpoint and switches correctly. 
- Switch to an unsupported network and ensure it sets the walletNetwork to the chainId and doesn't error.
> Hotfix: update wallet network on switch

- src/lib/config/base/index.ts
- src/lib/config/base/keys.ts
Alchemy added support for base so I made a frontend project with the normal domain allowlist and switched the RPC to it. 
Also updating the public RPC from the developer one to the user specific one. 
- Ensure Base is working correctly
> Use alchemy for base RPC. Fix public RPC

- package-lock.json
- package.json
Bump SDK. Adds 4pool_BPT/wstEth mid pool to config for Gnosis to open more paths.
DAI>WETH currently shows high price impact. After this change it should find a path through higher liquidity 4Pool/wstETH pool and reduce PI.
> Bump SDK. Adds 4pool_BPT/wstEth mid pool for Gnosis to open more paths.

- src/lib/config/avalanche/index.ts
- src/lib/config/avalanche/tokens.ts
Changing the native address on Avalanche to 0xEee as it makes more sense than the zero address (and won't get confused with the burn address). This address is self referential so doesn't matter what it is except for getting the native asset token price from the beets API. It has been changed in the beets API here: https://github.com/beethovenxfi/beethovenx-backend/pull/417 so needs to be changed in this frontend to match. 
- Use Avalanche Network
- Ensure the native asset has a price on the swap page.
> Hotfix: change avalanche native asset

- src/components/navs/AppNav/DesktopLinks/DesktopLinkItem.vue
Fixes this issue after [bumping vue version](https://github.com/balancer/frontend-v2/pull/4167):
Complex prop types are now handled differently and now we must use `props.to` (we couldn't before due to bad type inference).
Note: This issue was only affecting development env, that's why we didn't catch it in preview.
> fix: use prop in prefetch links

- src/pages/recovery-exit/components/UnstakeTable.vue
Fixes risk label for staked Aura positions in the recovery exit page. The subgraph is a bit different so we were checking for a poolId against the wrong data.
> hotfix: Aura staked risk label

- src/services/rpc-provider/rpc-provider.service.spec.ts
- src/services/rpc-provider/rpc-provider.service.ts
Prevents two different json providers being initialized when it's not needed.
> hotfix: Minor RPC init optimization

- src/components/contextual/pages/vebal/LMVoting/GaugesFilters.vue
- src/components/contextual/pages/vebal/LMVoting/LMVoting.vue
Adds default network filter on vebal table, which is taken from `chain` query param
Add `chain` query param with desired network name and refresh page, vebal table will be filtered by it
> feat: add default network filter on vebal table

- package-lock.json
- package.json
Bump SDK which re-adds GyroE V2 pools that were disabled while SG was incorrect.
Everything should function as before, SOR will no consider GyroE V2 pools on mainnet.
> Bump SDK (re-adds GyroE V2 mainnet).

- package-lock.json
- package.json
- src/composables/swap/useJoinExit.ts
`getSwapInfo` function is using 18 decimals for scaling amount used in SOR/Swaps which causes issues when using something like USDC. Changed to use correct token decimals. This should also fixes token decimals for exact token out case which also seems to be broken.
I'm not 100% clear on how the swap logic is working on FE so should be double checked this doesn't lead to any knock-on effects.
Check USDC > wstEth on mainnet with a gas fee: Should now return a proper result compared to production.
Try a BAL > weth on mainnet with a gas fee and an amount for weth (e.g. exact out). Should now return a proper result compared to production.
> Hotfix swap input scaling

- src/components/forms/lock_actions/LockForm/components/VeBalForm/VeBalForm.vue
There is a bug in lock flow when preview btn is not disabled when user inputs lock amount greater than lockable
Try to lock/extend in veBAL form, preview btn should be disabled if entered lock amount is greater than lockable
> fix: bug with lockable amount

- src/components/contextual/pages/vebal/cross-chain-boost/StakingCardSyncAlert.vue
It shouldn't be possible to open checkpoint gauge modal if gauge id is not defined
> fix: no gauge id error in checkpoint error

- src/components/contextual/pages/vebal/LMVoting/LMVoting.vue
- src/components/contextual/pages/vebal/LMVoting/composables/useLMVotingFilters.spec.ts
- src/components/contextual/pages/vebal/LMVoting/composables/useLMVotingFilters.ts
This is a preparatory refactor before adding a new type of filter (soon to be killed filter).
It moves all the filtering logic to its own composable so that it is testable. 
> Refactor: extract filters to composable and add tests

- src/components/contextual/pages/pool/PoolStatCards.vue
- src/components/tables/PoolsTable/PoolsTable.vue
- src/components/tooltips/APRTooltip/APRTooltip.spec.ts
- src/components/tooltips/APRTooltip/APRTooltip.vue
- src/components/tooltips/APRTooltip/components/StakingBreakdown.vue
- src/components/tooltips/APRTooltip/components/VeBalBreakdown.vue
- src/components/tooltips/APRTooltip/components/YieldBreakdown.vue
- src/composables/usePoolHelpers.spec.ts
- src/composables/usePoolHelpers.ts
- src/dependencies/Multicaller.mocks.ts
- src/dependencies/default-mocks.ts
- src/lib/config/avalanche/pools.ts
- src/lib/config/base/pools.ts
- src/lib/utils/styles.ts
- src/providers/local/pool-staking.provider.ts
- src/providers/local/pool.provider.ts
- tests/mount-helpers.ts
- Updates style of APR tooltip
- Fixes display of range or single value depending on if wallet is connected and if they have a boost > 1
- Introduces staking range APRs on Base and Avalance (should have been added when cross-chain syncing was enabled)
> chore: Update APRs style and fix display

- src/components/tooltips/APRTooltip/components/StakingBreakdown.vue
Fixes staking APR in tooltip on pool pages when user's wallet is not connected or the boost value is 1.
> fix: APR tooltip staking range

- src/composables/usePoolHelpers.ts
- src/providers/local/exit-pool.provider.ts
See title, moving all recovery exit logic into the recovery exit function.
> fix: Ensure single asset exits hidden for edge case

- src/pages/index.vue
On removing token filter tags, the address was not being passed so it would default to removing the last in the array. This fixes that.
Closes #4265
> fix: Token filter removal

- src/lib/config/arbitrum/pools.ts
Adds GyroE factory address to arbitrum. 
It fixes pool type for:
https://beta-app-v2-git-chore-gyro-pool-balancer.vercel.app/#/arbitrum/pool/0xb6911f80b1122f41c19b299a69dca07100452bf90002000000000000000004ba
> Add gyro pool factory to arbitrum

- src/components/contextual/pages/vebal/MyVebalInfo.vue
- src/composables/useVeBAL.ts
The veBAL page header wasn't waiting for the veBAL balance to be loaded before rendering which would result in a balance of 0.00 for a few seconds before balances were loaded. This PR just includes balance loading in the computed isLoading property so the whole header doesn't render until it's ready.
> fix: veBAL balance loading state

- src/composables/queries/useUserPoolSharesQuery.spec.ts
Skip test causing flaky builds.
There is some concurrency problem when importing `balancerSubgraphService` from `useUserPoolSharesQuery` and this skipped test seems to make it more frequent. We skip it until we understand the root cause. 
> Chore: skip flaky test

- src/components/contextual/pages/vebal/MyVebalInfo.vue
Got a request to add a comma for large veBAL balances. Also happy to go with the default 3 decimals than the previous 2 here.
Impersonated with address: 0x31e9fFCFfd0e400a9d6adF0c25369fB4D513254f
Before:
After:
> Update veBAL balance to include commas for large amounts

- src/composables/swap/useSor.ts
- src/lib/balancer.sdk.ts
We were loading SOR pools on page load and whenever you visited the swap page. The swap page was also fetching every time you revised the page which is unnecessary.
- Prevents initial global fetch, this was for swap join/exit flows to speed up the flows, but it now seems to be affecting the global UX. The handlers themselves trigger a fetch if it hasn't been loaded globally so this won't break anything.
- Moves instantiation of SorManager outside of useSor so fetching is not retriggered every time you visit the swap page.
> fix: Overfetching sor pools

- src/constants/queryKeys.ts
- src/pages/pool/add-liquidity.vue
- src/pages/pool/withdraw.vue
- src/providers/local/exit-pool.provider.ts
- src/providers/local/join-pool.provider.ts
Removes conditionals waiting for SOR fetch pools in join exit flows. Falls back to fetching in handlers that need them.
> Hotfix: remove SOR conditionals

- src/components/contextual/pages/vebal/MyVebalInfo.vue
Hide user rank if no veBal balance
> fix: hide rank if no vebal balance

- src/lib/config/avalanche/index.ts
We had an additional slash injected into explorer links.
> fix: Avax explorer links

- src/components/contextual/pages/pools/StakedPoolsTable.vue
- src/components/contextual/pages/vebal/cross-chain-boost/CrossChainBoostCards.vue
- src/composables/usePoolHelpers.ts
- src/providers/cross-chain-sync.provider.ts
Fix broken cross chain sync links
> fix: cross chain sync links

- src/components/forms/pool_actions/AddLiquidityForm/AddLiquidityForm.vue
- src/components/forms/pool_actions/AddLiquidityForm/components/AddLiquidityTotals.vue
Show expected bptOut in add liquidity form so that users can test expected outputs even without having appropriate token balances.
> feat: Add LP tokens to add liquidity form

- src/components/contextual/pages/vebal/providers/voting.provider.spec.ts
- src/components/contextual/pages/vebal/providers/voting.provider.ts
Fixes an ordering issue when sending parameters to `vote_for_many_gauge_weights` call.
Example: 
The user had 100% allocated to gaugeA
Now they want to allocate: 
50% to gaugeA
50% to gaugeB
If we sent gaugeB parameters before gaugeA parameters, there was an error: `Used to much power`.
> Fix: take old weights into account when ordering weights for multivote

- src/components/forms/pool_actions/AddLiquidityForm/components/AddLiquidityTotals.vue
Just fixing a typo I found while using the frontend :heart:
> Fix typo in pool liquidity add form

- src/components/inputs/PoolFeatureSelect.vue
- src/composables/usePoolGroups.ts
- src/lib/config/arbitrum/pools.ts
- src/lib/config/mainnet/pools.ts
- src/lib/scripts/metadata.generator.ts
- src/pages/index.vue
- src/types/pools.ts
Adds pool filter by Points, i.e. if the pool is tagged as receiving points in the Balancer Metadata repo.
> feat: Points filter

- src/components/contextual/pages/vebal/LMVoting/GaugesTable.vue
Fix condition for showing pool name from metadata. We have some pools that have metadata (points) but not a name set up so previous if-condition broke the composition.
BEFORE FIX:
AFTER FIX:
> fix pools composition on vebal page

- package-lock.json
- package.json
> chore: Bump happy dom

- src/composables/contextual/add-liquidity/useDisabledJoinsGuard.spec.ts
- src/composables/useDisabledJoinPool.ts
> fix: Block joins page if unapproved rate provider

- src/components/contextual/pages/vebal/LMVoting/GaugesTable.vue
- Makes voting table row clicks check the vote select box instead of redirecting to pool.
- Adds link arrow in pool composition column which opens pool page in another tab.
> hotfix: Improve voting UX

- src/components/pool/PoolPageHeader.vue
- src/composables/useDisabledJoinPool.spec.ts
- src/composables/useDisabledJoinPool.ts
- src/lib/config/arbitrum/pools.ts
- src/lib/config/avalanche/pools.ts
- src/lib/config/base/pools.ts
- src/lib/config/gnosis-chain/pools.ts
- src/lib/config/goerli/pools.ts
- src/lib/config/mainnet/pools.ts
- src/lib/config/polygon/pools.ts
- src/lib/config/sepolia/pools.ts
- src/lib/config/zkevm/pools.ts
- src/locales/default.json
Since allowlisting is really controlled by the tokenlist we are reverting to a reactive approach to pool blocking in the UI.
> chore: Remove pool allowlisting

- src/components/web3/SanctionedWalletModal.vue
- src/components/web3/ThirdPartyServicesModal.vue
- src/locales/default.json
- src/pages/privacy-policy.vue
> chore: Update wording

- src/lib/config/arbitrum/index.ts
- src/lib/config/avalanche/index.ts
- src/lib/config/avalanche/keys.ts
- src/lib/config/gnosis-chain/index.ts
- src/lib/config/gnosis-chain/keys.ts
- src/lib/config/mainnet/index.ts
- src/lib/config/mainnet/keys.ts
- src/lib/config/optimism/index.ts
- src/lib/config/optimism/keys.ts
- src/lib/config/polygon/index.ts
- src/lib/config/polygon/keys.ts
- src/providers/cross-chain-sync.provider.spec.ts
TheGraph is deprecating the hosted service so this PR migrates all relevant endpoints to Studio. API key is public but I've allowlisted only `*.balancer.fi` to use it.
All endpoints are available at https://docs.balancer.fi/reference/subgraph
> update subgraphs to studio
