src/components/cards/TradeCard/TradeRoute.vue

Fixes # .
- Should fix V2 routing.
- 
-

V2 routing fixes.

---

src/components/_global/BalTable/BalTable.vue

fix: table sort arrow alignment

---

package-lock.json
package.json
src/components/cards/TradeCard/TradeRoute.vue
src/composables/trade/useSor.ts

Fixes # .
- Add guard to accessing route in TradeRoute.vue
- Add guard to accessing decimals in useSor.ts

Hotfix/1.0.9 - Fix undefined errors in TradeRoute and useSor

---

src/components/cards/TradeCard/TradeRoute.vue
src/components/forms/pool_actions/InvestForm.vue
src/components/forms/pool_actions/WithdrawForm.vue
src/composables/queries/usePoolQuery.ts
src/composables/useTokens.ts
src/plugins/router.ts
src/services/balancer/contracts/contracts/vault.ts
src/services/pool/calculator/index.ts
src/services/pool/exchange/index.ts
src/types/index.ts

Fix various TS types

---

src/components/_global/BalAsset/BalAsset.vue

- Fixes distorted bal asset (token icons) in various places.

fix: distorted balasset icons

---

src/lib/utils/profile.ts
src/store/modules/web3.ts

- Refactor profile data fetching

Fix ENS resolution

---

package-lock.json
package.json
src/lib/utils/balancer/contract.ts
src/lib/utils/balancer/swapper.ts
src/lib/utils/balancer/tokens.ts
src/lib/utils/balancer/web3.ts
src/lib/utils/balancer/wrapper.ts

No changes to behaviour, just passing back proper types from multicall and sending transactions.

refactor: replace some "any"s with concrete types

---

public/index.html

Provide OpenGraph/Twitter meta tags to render a card on social media.

Provide meta tags

---

package-lock.json
package.json

This hopefully should fix the "undefined" error users sometime seeing.

Update bnc-notify to latest

---

src/components/_global/BalLineChart/BalLineChart.vue
src/components/pages/pool/PoolChart.vue

- Smooth line
- Remove yAxis line and range numbers
- Use tailwind config for colors

Smooth line and remove yAxis

---

package-lock.json
package.json
src/lib/utils/balancer/helpers/sor/sorManager.ts

Fixes # .
- Fixes various SOR edge case bugs.
- Add SOR with Element pool support.
-

Bumped SOR package and added timestamp.

---

src/components/cards/TradeCard/TradeRoute.vue

AFAIK this is the only place where the domain needs to be updated. If this looks good I can update the Vercel config to use `kovan.balancer.fi` so that moving forward all networks will use a single subdomain instead of `kovan.app.balancer.fi`

single subdomain level for all networks

---

package-lock.json
package.json
src/composables/pools/useTokenApprovals.ts

Fixes #UI-555
- Help prevent race condition between blocknative txConfirmation and allowances update onchain

Fix potential race condition

---

src/composables/useFathom.ts
src/constants/fathom.ts
src/plugins/sentry.ts
src/services/fathom/goals.ts

Track goals in multiple fathom apps

---

src/composables/trade/useSor.ts
src/lib/utils/balancer/helpers/sor/sorManager.ts

Fixes # .
-  Change to get price of swap using stored market prices if using Polygon and set manually for SOR.
-  If mainnet price retrieved on-chain using SOR.

Set swap cost using stored prices for Polygon.

---

src/components/navs/AppNav/AppNav.vue

Hide network switch

---

src/services/balancer/subgraph/service.ts

(cherry picked from commit 8c3178cb1050cc70c6a4386b8f7aa32d21215e44)

Add polygon blocktime

---

src/lib/config/homestead.json
src/lib/config/polygon.json

Update stable pool factory addresses

---

package-lock.json
package.json
src/components/_global/BalModal/BalModal.vue
src/components/animate/AnimatePresence.vue
src/components/lists/TokenListItem.vue

Fixes # .
- Add the animation utility library i have been talking about for a while. Has a lot of useful features which will allow us to orchestrate some of our interactions better.

Animate presence component

---

src/composables/trade/useSor.ts

Just updating this to match the other ones

refactor: make blocknativeTxHandler take a TransactionResponse

---

package-lock.json
package.json

Hotfix 1.6.4

---

.github/workflows/checks.yml
package-lock.json
package.json

- Add check to prevent merges with master unless version is updated

Add check for version update

---

src/components/images/Avatar.vue

Update to jazzicon.

---

src/components/navs/AppNav/AppNavSettings.vue
src/components/popovers/TradeSettingsPopover.vue
src/pages/Home.vue

It was doing the opposite of what it was supposed to do.

Fix isV1Supported

---

src/constants/pools.ts

Add the new BTC stable pool to the AllowList

Add BTC stable pool to AllowList

---

src/lib/utils/liquidityMining/MultiTokenLiquidityMining.json

Note the addition of MTA rewards for a pool on Polygon, which we'll need to calculate for them so they can airdrop.
This marks the 8th week of liquidity mining on Balancer v2. The Ballers propose the following changes which will go into effect 00:00 UTC Monday, July 12th, 2021. 
Remove a Tier 1 slot, 2x Tier 3 slots and add 2x Tier 4 slot allocations for BAL/WETH 80/20. The pool will now receive 32,000 BAL per week total.
https://app.balancer.fi/#/pool/0x5c6ee304399dbdb9c8ef030ab642b10820db8f56000200000000000000000014
Allocate a Tier 3 slot to WBTC/renBTC/sBTC stablepool. This pool will now receive 2,500 BAL per week total.
https://app.balancer.fi/#/pool/0xfeadd389a5c427952d8fdb8057d6c8ba1156cc56000000000000000000000066
Allocate a Tier 3 slot and remove 2xTier 4 slots to BAL/GNO/WETH/DAI …

Liquidity Mining, week 59

---

src/components/_global/BalRangeInput/BalRangeInput.vue
src/components/cards/SuccessOverlay.vue
src/components/modals/TradePreviewModal.vue
src/composables/useBlocknative.ts
src/composables/useDarkMode.ts

Implement dark mode in missed features.

Multiple dark mode fixes

---

package-lock.json
package.json
src/lib/utils/liquidityMining/MultiTokenLiquidityMining.json

Proposal: https://snapshot.org/#/ballersvote.eth/proposal/Qmej25t4dzDSSkcHkEu2u79qu5qVxBfme8MFtoiGRA3ngG
Description provided by @bakamoto20 on e21c10f
- UMA/USDC 50/50 added to Tier 4 on ETH. 1,000 BAL/week total ( 0xf5aaf7ee8c39b651cebf5f1f50c10631e78e0ef9000200000000000000000069 ).
- GRT/USDC 50/50 added to Tier 4 on ETH. 1,000 BAL/week total ( 0x14462305d211c12a736986f4e8216e28c5ea7ab4000200000000000000000068 ). 
- 2xTier 4 slots (2,000 BAL per week) removed from BAL/WETH 80/20 ( 0x5c6ee304399dbdb9c8ef030ab642b10820db8f56000200000000000000000014 ). 
- 8 asset pool on polygon removed from incentives, following concerns with ADDY token & poor BAL per $ TVL efficiency ( 0x32fc95287b14eaef3afa92cccc48c285ee3a280a000100000000000000000005 ). 
- Addy pools BAL assigned to new renBTC/WBTC …

Liquidity Mining, week 60

---

src/store/modules/registry.ts

Fixes the undefined errors from development
Sense check the app

fix: undefined errors and unused vuex store

---

src/lib/utils/liquidityMining/MultiTokenLiquidityMining.json

Liquidity Mining Week 61
No liquidity mining changes were proposed for week 61.  
- [x ] Other
- [x ] Set your system date to some time within the mining week; APYs and LM indicators should change accordingly

Liquidity Mining, week 61

---

src/components/navs/AppNav/AppNavActivityBtn/AppNavActivityBtn.vue

Remove the spinner inside the popover (not needed anymore) - it already appears on the button.

Minor notifications tweak

---

src/locales/default.json

Fix translation typo

---

src/composables/trade/useTokenApproval.ts
src/composables/trade/useTokenApprovalGP.ts
src/composables/useAllowances.ts
src/providers/allowances.provider.ts

Allowances were not being fetched correctly when the vault was changed.
Test that allowances persist across trades

fix: allowances query

---

src/components/cards/TradeCard/TradeCard.vue
src/components/cards/TradeCardGP/TradeCardGP.vue
src/components/modals/TradePreviewModalGP.vue
src/composables/trade/useGnosis.ts
src/composables/trade/useSor.ts
src/composables/trade/useTokenApprovalGP.ts
src/composables/trade/useTrading.ts
src/locales/default.json
src/plugins/blocknative.ts

Interface tweaks and lots of bug fixes - based on https://www.figma.com/file/FnVmt8Ho1rdwgk26fyNDtE/TradeUI?node-id=337%3A12822

Gnosis interface tweaks

---

package-lock.json
package.json

Upgrade wallet connect provider version.

Hotfix 1.11.3

---

src/composables/trade/useSor.ts
src/composables/useTransactions.ts
src/locales/default.json

Wrapping/unwrapping is not really a "trade" - so I've added these as new types.
Here's how it looks now:

[Gnosis]: Add wrap/unwrap transaction action

---

package-lock.json
package.json
src/lib/utils/liquidityMining/MultiTokenLiquidityMining.json

Week 63, no changes were proposed (see #liquidity-committee in Discord), so there won't be a vote on the Baller's snapshot this week.

Liquidity Mining, week 63

---

src/lib/utils/liquidityMining/index.ts
src/pages/LiquidityMining.vue

I've been talking to the Ballers to try to avoid making the merge during the weekend, so it will often be the case that the current week is not the last in the JSON. This handles that case.

Compute current week

---

package-lock.json

Fix SOR version.

---

src/components/forms/pool_actions/InvestForm.vue
src/composables/pools/useTokenApprovals.ts

Fixes a few bugs highlighted by Langer in weekly testing.

Release fixes

---

package-lock.json
package.json
src/providers/tokens.provider.ts
src/services/coingecko/api/price.service.ts

Fix polygon specific bugs arising from registry refactor.

Hotfix 1.12.2

---

package-lock.json
package.json
src/components/lists/TokenListsListItem.vue
src/components/modals/SelectTokenModal/SelectTokenModal.vue
src/lib/utils/index.ts
src/providers/tokens.provider.ts

Fixes incorrect injection of liquidity mining tokens and links to token lists.

Hotfix 1.12.4

---

src/composables/queries/useRelayerApprovalQuery.ts
src/composables/trade/useRelayerApproval.ts
src/constants/queryKeys.ts

feat: add useRelayerApproval composable

---

src/constants/units.ts
src/lib/utils/balancer/web3.ts
src/services/gas-price/gas-price.service.ts
src/services/gas-price/providers/blocknative.provider.ts
src/services/gas-price/providers/polygon.provider.ts
src/services/gas-price/providers/types.ts
src/store/modules/market.ts

Adds support for EIP1559 type transactions.
Here is an example of a tx I made with the change - https://etherscan.io/tx/0xf2d62b204da7f2c0500fb0844821c627ca177a3d8c9cb15e1402be2041c38dd3

Add support for EIP1559

---

package-lock.json
package.json
src/composables/pools/useTokenApprovals.ts
src/composables/trade/useTokenApproval.ts
src/composables/trade/useTokenApprovalGP.ts
src/providers/tokens.provider.ts

Fix scaling of amounts passed into function for checking which tokens need approvals.

Hotfix 1.12.9

---

package-lock.json
package.json
public/index.html

Attempt to fix google analytics. Fix order of gtag script calls.

Hotfix 1.12.12

---

package-lock.json
package.json

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any new dependencies that are required for this change.
Updates SOR.

Update SOR package.

---

package-lock.json

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any new dependencies that are required for this change.
Updates SOR to version with working Kovan Stabal pool.

Update SOR to version with working Kovan staBAL pool.

---

src/lib/config/polygon.json
src/providers/tokens.provider.ts

We were trying to inject mainnet stEth/wstEth token addresses on polygon.

Fix token injection

---

package-lock.json
package.json
src/lib/utils/balancer/wrapper.ts

For the native wrapping transaction, the abi needs to specify that the deposit function is payable.

Hotfix 1.13.2

---

package-lock.json
package.json
src/services/pool/calculator/stable.ts

Fix inputs for SOR function, balances should be scaled appropriately.

Hotfix 1.13.3

---

package-lock.json

Somehow package-lock got out of sync

Update pkg lock

---

package-lock.json
package.json
src/services/pool/calculator/stable.ts

Fixes inconsistent scale of pool token balances into SOR function.

Hotfix 1.13.9

---

src/components/tables/LMTable/LMTable.vue
src/pages/LiquidityMining.vue

Includes all the design adjustments listed in https://www.figma.com/file/2w9g4vXIProu2EdP6xH1Yp/Liquidity-Mining?node-id=85%3A3264
Test the table on desktop and mobile for both polygon and mainnet.

LM Table Adjustments

---

package-lock.json
package.json
src/components/navs/AppNav/AppNavSettings.vue
src/composables/queries/usePoolSnapshotsQuery.ts
src/composables/queries/useTokenPricesQuery.ts
src/constants/tokens.ts
src/pages/LiquidityMining.vue
src/services/coingecko/api/price.service.ts
src/store/modules/app.ts

Hotfix 1.14.3

---

package-lock.json
package.json
src/components/tables/LMTable/LMTable.vue
src/composables/queries/usePoolSnapshotsQuery.ts
src/composables/queries/useTokenPricesQuery.ts
src/constants/tokens.ts
src/services/coingecko/api/price.service.ts

Hotfix 1.14.4

---

src/components/navs/AppNav/AppNavSettings.vue
src/store/modules/app.ts

Unhides Gnosis interface in preparation for launch

[Gnosis]: Unhide trade interface

---

package-lock.json
package.json
src/lib/utils/liquidityMining/MultiTokenLiquidityMining.json

Original #753, needed a version bump.

Week 66 Liquidity Mining

---

package-lock.json
package.json

Release 1.16.0

---

package-lock.json
package.json
src/services/pool/calculator/stable.ts
src/services/pool/exchange/serializers/ExitParams.ts

Making a draft PR to discuss wstETH withdrawals on.

Hotfix: Metastable rounding issues

---

package-lock.json
src/assets/images/icons/networks/arbitrum.svg
src/components/navs/AppNav/AppNavActions.vue
src/components/navs/AppNav/AppNavNetworkSelect.vue
src/constants/initialTokens.json
src/constants/network.ts
src/constants/pools.ts
src/constants/tokenlists.ts
src/constants/tokens.ts
src/lib/config/arbitrum.json
src/lib/config/index.ts
src/plugins/sentry.ts
src/services/balancer/subgraph/balancer-subgraph.service.ts
src/services/coingecko/coingecko.service.ts
src/services/web3/useWeb3.ts

This PR adds the necessary configs for interacting with the Balancer deployment on Arbitrum.
**TODO before merge:**
Full test of app on Arbitrum

Add Arbitrum support

---

package-lock.json
package.json
src/services/claim.ts
src/services/pool/calculator/stable.ts
src/services/pool/exchange/serializers/ExitParams.ts

Hotfix 1.16.2

---

package-lock.json
package.json
src/lib/config/arbitrum.json
src/services/balancer/subgraph/types.ts
src/services/pool/calculator/stable.ts

Hotfix stable pool maths

---

package-lock.json
package.json
src/components/tooltips/LiquidityMiningTooltip.vue
src/composables/useTime.ts
src/locales/default.json
src/services/balancer/subgraph/entities/pools/index.ts
src/services/balancer/subgraph/types.ts
src/services/coingecko/api/price.service.ts
src/services/lido/lido.service.ts
src/services/web3/useWeb3.ts

Add Lido stETH APR to APR tooltip.

Hotfix 1.17.5

---

package-lock.json
package.json
src/pages/LiquidityMining.vue

Add Arbitrum to the LM page

---

package-lock.json
package.json
src/components/tooltips/LiquidityMiningTooltip.vue
src/composables/useTime.ts
src/locales/default.json
src/pages/LiquidityMining.vue
src/services/balancer/subgraph/entities/pools/index.ts
src/services/balancer/subgraph/types.ts
src/services/coingecko/api/price.service.ts
src/services/lido/lido.service.ts
src/services/web3/useWeb3.ts

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any new dependencies that are required for this change.

Arbitrum lm

---

package-lock.json
package.json

Release 1.18.0

---

package-lock.json
package.json
src/components/_global/BalCard/BalCard.vue
src/components/sections/FeaturedPools.vue
src/constants/links.ts
src/locales/default.json

A few minor fixes for the ecosystem cards.

Hotfix: fix ecosystem cards

---

package-lock.json
package.json

Updates SOR V1 package to use latest released package. (Same as previous Github package we were using).
V1 trades should operate as before.

Update SOR V1 package to latest released package.

---

package-lock.json
package.json
src/components/_global/BalCard/BalCard.vue
src/components/sections/FeaturedPools.vue
src/constants/links.ts
src/lib/utils/liquidityMining/MultiTokenLiquidityMining.json
src/locales/default.json

Liquidity Mining, week 68

---

package-lock.json
package.json
src/components/navs/AppNav/AppNavClaimBtn.vue

Hotfix: Hide LM estimate on Arbitrum

---

src/composables/pools/usePools.ts
src/locales/default.json
src/pages/Home.vue
src/pages/Pool.vue

Adds error alerts for pool/pools page. I think these should be "app-level" as well due to their significance. 

Add error alerts for pool/pools page

---

package-lock.json
package.json

Release 1.19.0

---

package-lock.json
package.json
src/lib/utils/balancer/web3.ts

Hotfix 1.19.2

---

package-lock.json
package.json
src/components/navs/AppNav/AppNavClaimBtn.vue
src/lib/config/arbitrum.json
src/pages/LiquidityMining.vue
src/services/claim.ts

Add LM claim button to the arbitrum app

Hotfix: Arbitrum claim

---

package-lock.json
package.json
src/lib/utils/balancer/stablePoolEncoding.ts
src/lib/utils/balancer/swapper.ts
src/lib/utils/balancer/weightedPoolEncoding.ts
src/services/balancer/contracts/contracts/vault.ts

I've replaced some functionality that's duplicated from the monorepo with the newly published balancer.js package.
Check that pool weights display correctly + joins/exits still work (balancer.js powers all join/exits in the monorepo so this is very unlikely to be wrong)

Add Balancer.js

---

src/components/tables/PoolsTable/PoolsTable.vue
src/components/tables/PoolsTable/TokenPills/HiddenTokensPills.vue
src/components/tables/PoolsTable/TokenPills/StableTokenPill.vue
src/components/tables/PoolsTable/TokenPills/TokenPills.vue
src/components/tables/PoolsTable/TokenPills/WeightedTokenPill.vue
src/pages/Home.vue

Highlights searched tokens on pool search + tidy up and refactor to use the new Vue SFC for some components.
Here's how it looks:

Highlight searched tokens on pool search

---

package-lock.json
package.json
src/components/inputs/TokenSelectInput/TokenSelectInput.vue

Release 1.20.0

---

package-lock.json
package.json
src/components/forms/pool_actions/WithdrawForm.vue
src/components/inputs/TokenInput/TokenInput.vue

Hotfix 1.20.2

---

package-lock.json
package.json
src/components/forms/pool_actions/WithdrawForm.vue
src/components/navs/AppNav/AppNavClaimBtn.vue

Hotfix: Restore LM estimates on Arbitrum

---

package-lock.json
package.json
src/services/balancer/subgraph/entities/pools/index.ts

Hotfix 1.20.5 

---

package-lock.json
package.json
src/composables/trade/useSor.ts

Hotfix 1.20.6 

---

src/constants/pools.ts

Add InvestmentPoolFactory and Macro Hedge Pool
First need subgraph factory PR to be merged so that the pool is visible.
Then should see InvestmentPool 0xe7b1d394f3b40abeaa0b64a545dbcf89da1ecb3f00010000000000000000009a

Invest deploy

---

src/composables/trade/useValidation.ts

Minor refactor of work from @beethovenxfi in #835

Show no liquidity error message

---

package-lock.json
package.json
src/constants/tokens.ts
src/lib/utils/liquidityMining/MultiTokenLiquidityMining.json

Liquidity Mining, week 70

---

package-lock.json
package.json
src/components/forms/pool_actions/InvestForm.vue
src/components/forms/pool_actions/WithdrawForm.vue

Release 1.21.0

---

package-lock.json
package.json
src/composables/trade/useTokenApproval.ts
src/providers/tokens.provider.ts

Hotfix 1.21.2

---

package-lock.json
package.json
src/components/tables/LMTable/LMTable.vue

The isNewPool attribute is optional and so should be accessed with optional chaining.

Hotfix 1.21.3

---

package-lock.json
package.json
src/components/tables/LMTable/LMTable.vue
src/composables/trade/useGnosis.ts

Hotfix 1.21.4

---

package-lock.json
package.json
src/providers/tokens.provider.ts
src/services/balancer/contracts/contracts/vault.ts

Release 1.22.0 - Weekly Release

---

package-lock.json
package.json
src/components/cards/TradeCard/TradeCard.vue
src/components/forms/AppSlippageForm.vue
src/components/modals/TradePreviewModalGP.vue
src/composables/trade/useTrading.ts
src/composables/useSlippage.ts
src/providers/user-settings.provider.ts
src/store/modules/app.ts
vue.config.js

Hotfix 1.22.3

---

package-lock.json
package.json
src/lib/utils/liquidityMining/MultiTokenLiquidityMining.json

Pending Ballers [vote](https://snapshot.org/#/ballersvote.eth/proposal/QmXPRM9jgWaGqimcSLnjgcrFrfEaUuyJBDTBoXpMwo2bfs) 
See bakamoto's comment below

Liquidity Mining, week 72

---

package-lock.json
package.json
src/composables/trade/useValidation.ts
src/composables/useTransactions.ts
src/composables/watchers/useWeb3Watchers.ts
src/lib/utils/liquidityMining/MultiTokenLiquidityMining.json

Liquidity Mining, week 73

---

src/components/_global/BalAccordion/BalAccordion.vue
src/components/cards/MyPoolBalancesCard/MyPoolBalancesCard.vue
src/components/cards/MyWalletTokensCard/MyWalletTokensCard.vue
src/pages/pool/invest.vue

This PR moves the side modules found in the new invest flow into accordions on smaller screens.

Responsive design for invest flow

---

package-lock.json
package.json
src/components/pages/pool/PoolActivitiesCard/Table.vue
src/composables/useNumbers.ts
src/lib/config/arbitrum.json
src/lib/utils/liquidityMining/MultiTokenLiquidityMining.json

Liquidity Mining, week 75

---

package-lock.json
package.json
src/components/forms/pool_actions/InvestForm/InvestForm2.vue

Release 1.26.0

---

package-lock.json
package.json
src/components/contextual/pages/pool/MyPoolBalancesCard.vue
src/constants/pools.ts

Hotfix - Allowlist irobot pool

---

src/locales/default.json

Miscellaneous copy edits for the English UI elements. Several typos, grammatical errors, and inconsistencies are addressed.

Miscellaneous copy edits for English

---

package-lock.json
package.json
src/composables/trade/useGnosis.ts
src/constants/pools.ts
src/lib/utils/balancer/helpers/sor/sorManager.ts
src/pages/pool/_id.vue

Hotfix 1.26.5 - Hide pool actions if no init pool liquidity

---

package-lock.json
package.json
src/composables/contextual/pool-transfers/usePoolTransfers.ts
src/composables/contextual/pool-transfers/usePoolTransfersGuard.ts
src/composables/usePool.ts
src/pages/_layouts/PoolTransferLayout.vue
src/pages/pool/_id.vue
src/pages/pool/invest.vue
src/pages/pool/withdraw.vue

Hotfix 1.26.6 - Invest/withdraw flow guard

---

src/constants/pools.ts

Allowlist WSB's 2nd ETP on Kovan, for testing
Can see pool 0x37a6fc079cad790e556baedda879358e076ef1b3000100000000000000000348 on Kovan

Allowlist 2nd WSB ETP on Kovan

---

package-lock.json
package.json
src/lib/utils/liquidityMining/MultiTokenLiquidityMining.json

No proposed liquidity mining changes this week.

Liquidity Mining, week 76

---

package-lock.json
package.json

Release 1.27.0

---

package-lock.json
package.json

Since our production app is a static build we don't need production dependencies, they should all be included at build time.
This should also make the production docker image much smaller.

Move all deps to dev deps

---

package-lock.json
package.json
src/components/cards/TradeCard/TradePair.vue
src/components/cards/TradeCardGP/TradeCardGP.vue

Hotfix 1.27.3 - Revert previous hotfix

---

package-lock.json
package.json
src/components/cards/TradeCard/TradePair.vue
src/components/cards/TradeCardGP/TradeCardGP.vue
src/lib/utils/balancer/swapper.ts

Hotfix 1.27.4 - Fix ETH trades

---

src/composables/trade/useGnosis.ts

Reverts balancer-labs/frontend-v2#1071

Revert "hotfix/1.27.5"

---

package-lock.json
package.json
src/services/claim/MultiTokenClaim.json

Add BANK to claim UI

---

package-lock.json
package.json
src/lib/utils/liquidityMining/MultiTokenLiquidityMining.json
src/lib/utils/liquidityMining/index.ts
src/services/claim/MultiTokenClaim.json

Liquidity mining, week 77

---

package-lock.json
package.json
src/components/_global/BalAsset/BalAsset.vue

Release 1.28.0

---

package-lock.json
package.json

Includes a fix for an issue in the SOR which prevents trading against DUSD pool
Changes in SOR package: https://github.com/balancer-labs/balancer-sor/pull/207
Test trading against DUSD token (0xbAe28251B2a4E621aA7e20538c06DEe010Bc06DE)

Hotfix 1.28.6

---

package-lock.json
package.json

Release 1.29.0

---

package-lock.json
package.json
src/services/claim/MultiTokenClaim.json

Adds NOTE to the claim interface
- [X ] Other : Hotfix to enable Note claims

Add NOTE to MultiTokenJSON

---

package-lock.json
package.json
src/components/forms/pool_actions/InvestForm/composables/useInvestMath.ts
src/components/forms/pool_actions/WithdrawForm/composables/useWithdrawMath.ts
src/services/claim/MultiTokenClaim.json

Hotfix 1.29.2 - Fix invest/withdraw if missing prices

---

src/composables/queries/usePoolQuery.ts
src/services/balancer/subgraph/types.ts
src/services/pool/concerns/liquidity.concern.ts

feat: calc pool value/apr

---

package-lock.json
package.json
src/components/forms/pool_actions/InvestForm/composables/useInvestMath.ts
src/components/forms/pool_actions/WithdrawForm/composables/useWithdrawMath.ts
src/components/navs/AppNav/AppNavClaimBtn.vue
src/composables/useTransactionErrors.ts
src/locales/default.json
src/services/claim/MultiTokenClaim.json

Hotfix 1.29.3 - Remove NOTE from claims

---

package-lock.json
package.json
src/components/navs/AppNav/AppNavClaimBtn.vue
src/composables/usePool.ts
src/composables/useTransactionErrors.ts
src/locales/default.json
src/services/claim/MultiTokenClaim.json

Hotfix 1.29.4: Correct logic for determining managed pool halted state

---

src/components/_global/BalLineChart/BalLineChart.vue

Add a @mouseleave event on the BalLineChart that resets the `currentValue` to the `latestValue` on mouse leave. Currently, when you hover off the swap price chart, the shown value is the last value you hovered over, which is confusing. You'd expect the price to always show the latest price, unless you are explicitly interacting with it.

Swap Price Chart: Introduce a mouseleave event that resets the current value to the latest

---

package-lock.json
package.json

Release 1.30.0

---

src/services/claim/MultiTokenClaim.json

Once decimal scaling issues are fixed, we can reinstate note claims (that come from the new distribution that was created)

added note to multitokenjson

---

package-lock.json
package.json
src/locales/default.json
src/services/claim/MultiTokenClaim.json
src/services/claim/claim.service.ts

The estimates API backend queries `MultiTokenClaim.json` to determine what tokens are distributed via the MerkleOrchard. 
This creates placeholders for tokens that will be distributed via the MerkleOrchard but for which we don't know the distributor addresses yet.
As the placeholder might point to a manifest that doesn't exist yet, I also added some error handling to `getSnapshot`
Use the app as an LP in the NEXO pool or the TUSD pool. The liquidity mining estimates button with the stars should remain responsive.

Orchard placeholders

---

src/components/cards/CreatePool/ChooseWeights.vue
src/components/cards/CreatePool/InitialLiquidity.vue
src/components/cards/CreatePool/PoolFees.vue
src/composables/pools/usePoolCreation.ts
src/locales/default.json
src/services/balancer/pools/weighted-pool.service.ts

Includes various minor fixes for pool creation.
Test on the pool creation UI available at /pool/create

Create pool fixes

---

package-lock.json
package.json
src/components/cards/CreatePool/ChooseWeights.vue
src/components/inputs/TokenInput/TokenWeightInput.vue
src/components/inputs/TokenSelectInput/TokenSelectInput.vue
src/components/modals/SelectTokenModal/SelectTokenModal.vue
src/providers/tokens.provider.ts

Release - pool creation

---

package-lock.json
package.json
src/components/cards/CreatePool/ChooseWeights.vue
src/components/inputs/TokenInput/TokenWeightInput.vue
src/components/inputs/TokenSearchInput.vue
src/composables/pools/usePoolCreation.spec.ts
src/composables/pools/usePoolCreation.ts
src/locales/default.json
src/pages/index.vue
src/pages/pool/_id.vue
src/pages/pool/create.vue
src/providers/tokens.provider.ts
src/services/balancer/pools/weighted-pool.service.spec.ts

Hotfix 1.31.2

---

package-lock.json
package.json
src/services/claim/MultiTokenClaim.json

Adds the distributor for TUSD so rewards show up
See that TUSD rewards show up

Added TUSD distributor to MultiTokenClaim

---

package-lock.json
package.json
src/lib/utils/liquidityMining/MultiTokenLiquidityMining.json

Liquidity mining week 80

---

package-lock.json
package.json

Release 1.32.0

---

package-lock.json
package.json
src/services/claim/MultiTokenClaim.json

Adds WMATIC distributor address to MultiTokenClaim.json

Hotfix - add wmatic distributor

---

src/components/_global/BalBreakdown/BalBreakdown.vue
src/components/contextual/pages/pool/PoolBalancesCard/BoostedPool.vue
src/locales/default.json

- Removal of "totals" in Pool composition
- Copy change of pool title
- Alignment of the BalBreakdown component

Linear pool tweaks

---

package-lock.json
package.json
src/components/forms/pool_actions/InvestForm/composables/useInvestMath.ts
src/components/forms/pool_actions/WithdrawForm/composables/useWithdrawMath.ts
src/composables/useSlippage.ts
src/services/balancer/contracts/contracts/batch-relayer.ts
src/types/index.ts

Update SDK version and convert inputs/outputs of SDK functions.

Boosted pools - update sdk

---

package-lock.json
package.json
src/lib/utils/liquidityMining/MultiTokenLiquidityMining.json
src/pages/pool/_id.vue

Hotfix - remove copper module

---

package-lock.json
package.json

Release 1.33.0

---

package-lock.json
package.json

Release 1.34.0 - Boosted pool support

---

package-lock.json
package.json
src/composables/watchers/useExploitWatcher.ts
src/lib/config/arbitrum.json
src/lib/config/homestead.json
src/lib/config/kovan.json
src/lib/config/polygon.json
src/lib/config/rinkeby.json
src/services/balancer/contracts/contracts/batch-relayer.ts

Hotfix - missing batch relayer address

---

package-lock.json
package.json

I accidentally pushed commits straight to master that updated some package versions. This PR reverts those commits so they can be tested first.

Hotfix - revert untested commits

---

package-lock.json
package.json
src/components/modals/SelectTokenModal/SelectTokenModal.vue

Hotfix 1.34.6 - Inject selected tokens

---

package-lock.json
package.json
src/components/modals/SelectTokenModal/SelectTokenModal.vue
src/components/tables/LMTable/LMTable.vue

Hotfix - Remove BPT from table LM

---

src/components/_global/BalLineChart/BalLineChart.vue

Update current value on new data

---

package-lock.json
package.json
src/components/tables/LMTable/LMTable.vue
src/constants/pools.ts

Hotfix: Add zero protocol fee LBP factory address

---

package-lock.json
package.json
src/lib/utils/liquidityMining/MultiTokenLiquidityMining.json

Liquidity Mining, week 82

---

package-lock.json
package.json

Release 1.35.0

---

package-lock.json
package.json
src/pages/index.vue

The mobile layout was breaking around the token filter options and the create pool button on the home page. This PR fixes those layout issues.

Hotfix - filter token layout

---

package-lock.json
package.json
src/pages/index.vue
src/services/claim/MultiTokenClaim.json

Revert wmatic distributor

---

package-lock.json
package.json

Release 1.35.3

---

package-lock.json
package.json
src/services/claim/MultiTokenClaim.json

Polygon team re-did distribution 4 using a new distributor
https://polygonscan.com/tx/0xee02a98f626018f21ae27f8a18e67f989786c84f525ba45e80611511fb49fb0f

Wmatic 3rd distributor

---

src/lib/utils/liquidityMining/MultiTokenLiquidityMining.json

Liquidity Mining week 83

---

package-lock.json
package.json
src/services/claim/MultiTokenClaim.json

Polygon team had to change the distributor again for security concerns
https://polygonscan.com/tx/0xa1cd220b2d898deac50e78ed77ff070dc3aa0814c8b9c58d5ceb5cfad3df35ca
WMATIC for week 81 should be claimable

Wmatic 4th distributor

---

package-lock.json
package.json
src/services/claim/MultiTokenClaim.json

Wmatic 4th dist

---

src/lib/utils/liquidityMining/MultiTokenLiquidityMining.json

Liquidity Mining Week 84

---

package-lock.json
package.json
public/index.html

Fathom have retired their original custom domain setup, this PR replaces the fathom URL with the new custom domain.

Hotfix - update fathom url

---

package-lock.json
package.json
src/locales/default.json

Cowswap are rebranding, this PR changes some wording to reflect those changes.

Hotfix - cowswap rebrand

---

package-lock.json
package.json
src/locales/default.json

Revert changes to Cowswap naming.

Hotfix - revert cowswap rebrand

---

package-lock.json
package.json
src/components/contextual/pages/pool/PoolChart.vue
src/locales/default.json

Hotfix - hide boosted chart

---

src/lib/utils/liquidityMining/MultiTokenLiquidityMining.json

* No proposed changes this week.
Reduce 100 BAL per week from USDC/DAI/miMATIC/USDT pool. This pool will now receive 2,400 BAL per week.
Establish a new BANK/WETH pool that will receive 100 BAL per week.
* Reduce 150 BAL per week from NDX/WETH pool. This pool will now receive 100 BAL per week.
* Reduce 1,100 BAL per week from MCB/WETH pool. This pool will now receive 500 BAL per week.
* Reduce 500 BAL per week from TCR/WETH pool. This pool will now receive 200 BAL per week.
* Add 1,750  BAL per week to BAL/WETH pool. This pool will now receive 5,250 BAL per week.
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any new dependencies that are required for this change.
Please provide instructions so we …

LM85 changes

---

package-lock.json
package.json
src/components/contextual/pages/pool/PoolChart.vue
src/composables/watchers/useExploitWatcher.ts

Fix exploit watcher disconnected wallet

---

package-lock.json
package.json
src/lib/utils/liquidityMining/MultiTokenLiquidityMining.json

Pending Ballers [vote](Link TBD)
* 
* 
*

Liquidity Mining, week 85

---

package-lock.json
package.json
src/components/_global/BalActionSteps/BalActionSteps.vue
src/components/tooltips/LiquidityAPRTooltip.vue

Release 1.36.0

---

package-lock.json
package.json
src/locales/default.json

Minor naming change where Cowswap is referenced.

Hotfix - cowswap naming

---

package-lock.json
package.json
src/components/contextual/pages/pool/PoolChart.vue

Originally done here #1306 by @mendesfabio

Hotfix - Restore boosted pool chart

---

package-lock.json
package.json

Release 1.37.0

---

src/constants/links.ts

Currently in the `FeaturedPools` component, the element.fi links point to element's 404 page. I updated the constants to point to the right resources and new term liquidity pools.
- Manual QA

Updated Element.fi links in constants

---

package-lock.json
package.json
src/lib/abi/ProtocolFeesCollector.json
src/services/balancer/contracts/__mocks__/balancer-contracts.service.ts
src/services/balancer/contracts/contracts/__mocks__/vault.ts
src/services/balancer/contracts/contracts/protocol-fees-collector.spec.ts
src/services/balancer/contracts/contracts/protocol-fees-collector.ts
src/services/balancer/contracts/contracts/vault.ts
src/services/balancer/subgraph/entities/pools/index.ts
src/services/lido/lido.service.ts

Fetches protocol fee and accounts for it in the APR calculations.
n/a

Hotfix - Account for protocol fee

---

src/lib/config/polygon.json
src/services/gas-price/providers/polygon.provider.ts

Flip the eip1559 switch for polygon and update gas price api call to support eip1559 response.
Perform any transaction on Polygon
N/A

feat: support EIP1559 on Polygon

---

package-lock.json
package.json

Release 1.38.0

---

src/composables/queries/usePoolsQuery.ts
src/composables/queries/useUserPoolsQuery.ts
src/services/balancer/subgraph/entities/pools/index.ts
src/services/balancer/subgraph/types.ts

Proposed changes as per the review on #1340

Review of #1340

---

package-lock.json
package.json
src/lib/utils/liquidityMining/MultiTokenLiquidityMining.json

Liquidity Mining, Week 88

---

package-lock.json
package.json
src/components/cards/CreatePool/PreviewPool.vue
src/components/cards/CreatePool/TokenPrices.vue
src/components/cards/MyWallet/MyWallet.vue
src/components/cards/TrendingPairs/TrendingPairs.vue
src/composables/useDarkMode.ts

Release 1.39.0

---

package-lock.json
package.json
src/components/cards/CreatePool/PoolFees.vue
src/components/contextual/pages/pool/MyPoolBalancesCard.vue
src/components/contextual/pages/pool/PoolChart.vue
src/components/forms/AppSlippageForm.vue
src/components/forms/pool_actions/WithdrawForm/components/ProportionalWithdrawalInput.vue
src/components/inputs/TokenSelectInput/TokenSelectInput.vue
src/components/tables/PoolsTable/TokenPills/TokenPills.vue
src/composables/useNumbers.spec.ts
src/composables/useNumbers.ts
src/composables/usePool.ts
src/pages/pool/_id.vue
src/services/pool/pool.helper.ts

Change all style 'unit' to 'percent' in fNum2 usage - develop merge

---

package-lock.json
package.json
src/components/forms/pool_actions/MigrateForm/components/MigratePreviewModal/MigratePreviewModal.vue

Feature release - boosted migration

---

package-lock.json
package.json
src/components/_global/BalLineChart/BalLineChart.vue
src/components/cards/PairPriceGraph/PairPriceGraph.vue

- Fixes pair price chart tooltip to have pair label order the other way round to match the card title (https://discord.com/channels/638460494168064021/829044997202378852/937363628884111380)
- Removes braces accidentally added to label (https://discord.com/channels/638460494168064021/829044997202378852/938613020832170044)

Minor chart fixes

---

package-lock.json
package.json
src/components/_global/BalLineChart/BalLineChart.vue
src/components/cards/PairPriceGraph/PairPriceGraph.vue
src/lib/utils/liquidityMining/MultiTokenLiquidityMining.json

Week 89 LM Changes

---

package-lock.json
package.json
src/components/forms/pool_actions/MigrateForm/components/MigratePreviewModal/MigratePreviewModal.vue
src/components/forms/pool_actions/MigrateForm/composables/useMigrateMath.ts
src/constants/tokenlists.ts

Release 1.40.0

---

package-lock.json
package.json
src/components/contextual/pages/pool/PoolChart.vue
src/services/pool/calculator/stable.ts

Fix stable single asset withdrawals

---

package-lock.json
package.json
src/components/contextual/pages/pool/PoolChart.vue
src/services/balancer/subgraph/entities/poolSnapshots/query.ts
src/services/pool/calculator/stable.ts

Fix boosted pool chart values

---

package-lock.json
package.json

Release 1.41.0

---

src/composables/trade/useSor.spec.ts
src/services/contracts/exchange-proxy.service.spec.ts
src/services/swap/swap.service.spec.ts

There was a lot of unnecessary output when running tests, this PR hides that console log output. From attempting this I noticed several tests were failing but not throwing the test suite because they were waiting on rejected promises. This PR also fixes those tests.

Fix tests and cleanup output

---

package-lock.json
package.json
src/services/claim/MultiTokenClaim.json

Adds LIDO token to claim widget

Add LIDO token to claim widget

---

package-lock.json
package.json
src/lib/utils/liquidityMining/MultiTokenLiquidityMining.json

Liquidity mining update, week 92

---

package-lock.json
package.json
src/components/cards/TradeCard/TradePair.vue
src/services/gas-price/gas-price.service.ts
src/services/gnosis/explorer.service.ts

Fix gnosis link

---

package-lock.json
package.json
src/components/cards/TradeCard/TradePair.vue
src/components/cards/TradeCardGP/TradeCardGP.vue
src/composables/trade/useSor.spec.ts
src/services/contracts/exchange-proxy.service.spec.ts
src/services/gas-price/gas-price.service.ts
src/services/swap/swap.service.spec.ts

Add D2D distributor mainnet

---

package-lock.json
package.json
src/components/_global/BalActionSteps/BalActionSteps.vue
src/components/cards/CreatePool/ChooseWeights.vue
src/components/cards/CreatePool/PreviewPool.vue
src/composables/pools/usePoolCreation.ts
src/lib/utils/liquidityMining/MultiTokenLiquidityMining.json

Week 93 LM changes

---

package-lock.json
package.json

Release 1.43.0

---

package-lock.json
package.json
src/components/forms/pool_actions/WithdrawForm/WithdrawForm.vue
src/components/forms/pool_actions/WithdrawForm/composables/useWithdrawMath.ts

Update SOR. Changed to handle SDK Relayer error throwing.

---

src/lib/config/arbitrum.json
src/lib/config/docker.json
src/lib/config/homestead.json
src/lib/config/index.ts
src/lib/config/kovan.json
src/lib/config/polygon.json
src/lib/config/rinkeby.json
src/lib/config/test.json
src/services/balancer/gauges/gauges-subgraph.client.ts

Adds gauges subgraph URL to network configs.
n/a
n/a

Add gauge subgraph to config

---

src/components/_global/BalActionSteps/BalActionSteps.vue
src/components/contextual/pages/pools/StakedPoolsTable.vue
src/components/contextual/pages/pools/types/index.ts
src/components/contextual/stake/StakePreview.vue
src/composables/pools/useTokenApprovals.ts
src/composables/staking/useStaking.ts
src/composables/useTokenApprovalActions.ts
src/lib/abi/GaugeFactory.json
src/lib/config/arbitrum.json
src/lib/config/homestead.json
src/lib/config/index.ts
src/lib/config/kovan.json
src/lib/config/polygon.json
src/lib/config/rinkeby.json
src/lib/config/test.json

Tokenomics - Staking Action (Fix approvals and polish)

---

package-lock.json
package.json

Update SDK/SOR to v4.0.0-beta.0 to use new BoostedPools path algo.
Gasless trading should show same (or better) results than previous version and trades should be executed correctly.

Update SOR to v4.0.0-beta.0 to use new BoostedPools path algo.

---

src/services/web3/web3.plugin.ts

Connector ID seems to have changed for metamask. This PR catches that change.
n/a

Fix wallet logo injection

---

package-lock.json
package.json
src/lib/config/polygon.json

Infura polygon RPC is currently down, this switches to alchemy for polygon config.
n/a

Hotfix - switch rpc provider

---

src/components/web3/ConfirmationIndicator.vue
src/constants/queryKeys.ts

The strip for confirmation date and the etherscan link is used in multiple places, thought I would make it a common component. 
Currently not used in this PR, but can be tested on #1451 
https://www.loom.com/share/5b89619bcf7b4b36b5f016725f78c7a3
The loading block not showing has been fixed.

Confirmation indicator

---

src/composables/queries/useGraphQuery.ts

I tried using it in the wild on my claim branch and needed some changes to make it easier to use.
n/a
n/a

Refactor useGraphQuery

---

package-lock.json
package.json
src/components/cards/CreatePool/SimilarPools.vue
src/pages/index.vue

Release 1.44.0

---

package-lock.json
package.json
src/composables/pools/usePoolCreation.ts
src/services/balancer/pools/weighted-pool.service.ts

For #1482 . The provider was not being loaded in fast enough. Using a manual JsonRpcProvider with the network config.

Provider not being loaded fast enough for pool creation restore

---

package-lock.json
package.json
src/composables/pools/usePoolCreation.ts
src/lib/utils/liquidityMining/MultiTokenLiquidityMining.json
src/services/balancer/pools/weighted-pool.service.ts

Adding TUSD rewards back

---

src/components/web3/ConfirmationIndicator.vue

I was seeing some funky behaviour around the transition between the loading block and the confirmation label. See the before and after demo, where I've used the ConfirmationIndicator in the invest flow. In particular, the animation/transition components were really messing things up and causing weird behaviour. I tried just using raw Transition components as well and it was also behaving weirdly.
n/a
Before: [https://www.loom.com/share/c7510cf75017420ca2895d3a1223e174](https://www.loom.com/share/c7510cf75017420ca2895d3a1223e174)
After: [https://www.loom.com/share/1731351b44d049edbbf54fc5cc1c0f4e](https://www.loom.com/share/1731351b44d049edbbf54fc5cc1c0f4e)

Fix confirmation label

---

src/plugins/sentry.ts

Log sentry errors before sent to the sentry server
N/A
N/A

Log sentry errors before sent to the sentry server

---

src/lib/config/kovan.json
src/services/balancer/gauges/gauges-subgraph.client.spec.node.ts
src/services/balancer/gauges/gauges-subgraph.service.spec.node.ts

Update kovan gauges subgraph URL

---

src/components/contextual/pages/vebal/LMVoting/GaugeVoteModal.vue
src/components/contextual/pages/vebal/LMVoting/GaugesTable.vue
src/components/contextual/pages/vebal/LMVoting/LMVoting.vue
src/composables/useVotingGauges.ts
src/locales/default.json

- Add warning if user does not have veBAL locked for > 7 days
- Make vote success call handler that refreshes the gauge info.
- Add un-allocated votes and epoch time remaining label to LMVoting
- Test that accounts with veBAL locked for less than a week cannot vote
- Accounts should no longer be able to get exceptions after clicking the vote button because it's handled by the warning. 

Add more veBAL error handling and information

---

src/components/forms/pool_actions/InvestForm/components/InvestPreviewModal/components/InvestActions.vue
src/components/forms/pool_actions/WithdrawForm/components/WithdrawPreviewModal/components/WithdrawActions.vue

Use ConfirmationIndicator in invest/withdraw flow

---

package-lock.json
package.json
src/lib/utils/liquidityMining/MultiTokenLiquidityMining.json

Week 95 LM

---

package-lock.json
package.json
src/components/modals/TradePreviewModalGP.vue

Re-add token approval

---

package-lock.json
package.json

Release 1.45.0

---

src/components/forms/lock_actions/LockForm/components/VeBalForm/components/LockEndDate.vue
src/components/forms/lock_actions/LockForm/composables/useLockEndDate.ts
src/composables/pools/useTokenApprovals.ts
src/composables/useTokenApprovalActions.ts
src/locales/default.json

This is the base branch for the veBAL page + getVeBAL modal.

Locking & Voting (Tokenomics)

---

package-lock.json
package.json
src/App.vue

This PR removes the current boosted pool feature alert so we have some time between it and the veBAL alert that we will add on launch.
n/a

Hotfix - remove boosted alert

---

src/components/contextual/pages/vebal/LMVoting/LMVoting.vue
src/components/forms/lock_actions/LockForm/components/MyVeBAL.vue
src/components/heros/AppHero.vue
src/components/navs/AppNav/AppSidebar/SidebarContent.vue
src/components/navs/AppNav/DesktopLinks/DesktopLinks.vue

A few minor css tweaks:
- Updated veBAL banner on Invest page 
- Tightening external link icons
- Tightening the claim stars in the primary nav
- Setting a max width to the voting tip on the veBAL page.

Feature/pk UI tweaks

---

src/locales/default.json

Fixed missing capitalisation of "proceed" button and corrected token symbol for 80-20 pool
Check that modal text displays correctly

Correct typos on veBAL redirection screen

---

package-lock.json
package.json

Release 1.46.0

---

package-lock.json
package.json
src/plugins/router.ts

Move routes so they're not blocked on production.

Hotfix - routes

---

package-lock.json
package.json
src/pages/claim.vue
src/pages/pool/_id.vue

Hotfix - respect staking allowlist

---

package-lock.json
package.json
src/components/forms/lock_actions/LockForm/components/LockPreviewModal/components/LockActions.vue
src/composables/pools/useTokenApprovals.ts
src/composables/useTokenApprovalActions.ts

Hotfix- lock approvals

---

package-lock.json
package.json
src/components/tooltips/LiquidityAPRTooltip.vue
src/lib/utils/liquidityMining/MultiTokenLiquidityMining.json

Add additional COW APR

---

src/composables/pools/useTokenApprovals.ts
src/composables/useTokenApprovalActions.ts

Minor cleanup of function names and inputs to make approvals a little more understandable. I think more refactoring could be done here. It seems the composable has a mixed-use case and needs to be separated or rethought. 
n/a

Refactor: Approval action function names and inputs

---

package-lock.json
package.json
src/components/_global/BalTable/BalTable.vue
src/components/contextual/pages/vebal/LMVoting/GaugesTable.vue
src/composables/useTime.ts
src/lib/config/arbitrum.json
src/lib/config/homestead.json
src/lib/config/index.ts
src/lib/config/kovan.json
src/lib/config/polygon.json
src/lib/config/rinkeby.json
src/lib/config/test.json
src/pages/claim.vue
src/services/balancer/gauges/entities/gauges/query.ts
src/services/balancer/gauges/gauge-controller.decorator.ts

Hotfix: Calculate gauge weights manually

---

src/components/tables/PoolsTable/PoolsTable.vue
src/constants/pools.ts
src/pages/pool/_id.vue
src/providers/local/staking.provider.ts

I had previously gotten confused about the spelling of Stakable. This PR fixes that spelling mistake in multiple places.
n/a

Fix spelling

---

package-lock.json
package.json
src/lib/utils/liquidityMining/MultiTokenLiquidityMining.json
src/plugins/router.ts

Hotfix - Conditional LM page access

---

package-lock.json
package.json
src/composables/pools/usePoolCreation.ts

Makes the details request use rpc instead of public rpc
N/A
N/A

Fix details call on create UI

---

package-lock.json
package.json
src/components/inputs/TokenInput/TokenInput.vue
src/composables/pools/usePoolCreation.ts

Hotfix 1.47.3

---

package-lock.json
package.json
src/constants/voting-gauges.ts

Fix LINK/WETH description in voting page

---

package-lock.json
package.json
src/components/inputs/TokenInput/TokenInput.vue
src/composables/pools/usePoolCreation.ts

Hotfix 1.47.5

---

src/services/staking/staking-rewards.service.ts
src/services/staking/utils.ts

For calculating non-BAL rewards we need to use total supply rather than working supply.
n/a

Fix - use total supply

---

package-lock.json
package.json

Add Staking APRs

---

package-lock.json
package.json
src/services/balancer/gauges/gauge-controller.decorator.ts

Fix div by zero

---

package-lock.json
package.json
src/composables/queries/useGaugesQuery.ts
src/providers/local/staking/staking.provider.ts
src/services/balancer/contracts/contracts/token-admin.ts

I had to cancel the deployments to polygon and arbitrum because they were totally borked by the APR update for mainnet. This PR fixes all issues so they can be deployed.
n/a

Hotfix - APRs L2s

---

package-lock.json
package.json
src/locales/default.json
src/pages/claim.vue

Claim page has references to mainnet boosts. This PR rewords the text on L2 claim pages to be more accurate.
Fixes #1668 
n/a

Hotfix - update L2 claim labels

---

src/services/balancer/subgraph/entities/pools/index.ts
src/services/rpc-provider/rpc-provider.service.spec.ts
src/services/rpc-provider/rpc-provider.service.ts
src/services/staking/staking-rewards.service.ts

Kyzia551 - improve data loading

---

package-lock.json
package.json

The last hotfix for liquidity mining didn't include the correct version bump. This PR simply bumps the patch version again.
n/a
n/a

Hotfix - bump version

---

src/components/cards/TradeCard/TradePair.vue

Fixes #1657 - removing veBAL from the trade card.

fix: remove veBAL from trade card

---

package-lock.json
package.json

Release 1.48.0

---

package-lock.json
package.json
src/components/forms/pool_actions/WithdrawForm/composables/useWithdrawMath.ts
src/lib/utils/balancer/stablePoolEncoding.ts
src/lib/utils/balancer/swapper.ts
src/lib/utils/balancer/weightedPoolEncoding.ts
src/services/balancer/contracts/contracts/vault.ts
src/services/balancer/pools/weighted-pool.service.spec.ts
src/services/balancer/pools/weighted-pool.service.ts
src/services/contracts/vault.service.spec.ts
src/services/contracts/vault.service.ts
src/services/swap/swap.service.spec.ts
src/services/swap/swap.service.ts

`balancer-js` is a legacy library that causes confusion because it has lots of overlapping functionality with `@balancer-labs/sdk`

remove balancer js lib

---

src/plugins/router.ts

This pr adds lazy loading routes in order to decrease bundle size.

Add lazy loading routes

---

package-lock.json
package.json
src/services/claim/MultiTokenClaim.json

Hotfix - add LDO distributor

---

package-lock.json
package.json
src/lib/utils/liquidityMining/MultiTokenLiquidityMining.json
src/services/claim/MultiTokenClaim.json

Liquidity Mining, week 99

---

package-lock.json
package.json
src/plugins/router.ts
src/services/claim/MultiTokenClaim.json

Remove /liquidity-mining route

---

package-lock.json
package.json

Release 1.49.0

---

package-lock.json
package.json

Hotfix - SDK Subgraph pagination

---

package-lock.json
package.json

Release 1.49.3 - L2 Voting Gauges

---

package-lock.json
package.json
public/data/voting-gauges.json
src/components/contextual/pages/vebal/LMVoting/GaugesTable.vue
src/composables/usePool.ts
src/lib/scripts/voting-gauge.generator.ts

Fixes
- Token pills in list if pool type is unknown, e.g. Element pools.
- Fetching addition token URIs from tokenlists.
- Adds support for linking to Element pools.
n/a

Hotfix - voting improvements

---

package-lock.json
package.json
public/data/vebal-gauge.json
public/data/voting-gauges.json
src/components/contextual/pages/vebal/LMVoting/GaugesTable.vue
src/components/tables/PoolsTable/TokenPills/StableTokenPill.vue
src/composables/usePool.ts
src/lib/scripts/voting-gauge.generator.ts

Hotfix - add vebal gauge

---

package-lock.json
package.json
src/lib/abi/GaugeController.json
src/services/balancer/gauges/gauge-controller.decorator.ts

Hotfix fetch more accurate gauge weights

---

package-lock.json
package.json
src/lib/config/polygon.json

The Polygon RPC was changed to the public rpc for everyone, this will not cope with the requests we use, we have to use Alchemy or Infura here. Lots of issues probably caused by rate limiting.
n/a

Hotfix - fix polygon

---

package-lock.json
package.json
src/components/heros/AppHero.vue
src/composables/queries/useVeBalLockInfoQuery.ts
src/lib/config/arbitrum.json
src/plugins/router.ts

Hotfix - Arbitrum staking

---

src/components/tables/PoolsTable/PoolsTable.vue

Reduce invest pool composition width on small/medium screens (Closes #1773)

---

src/components/_global/BalTooltip/BalTooltip.vue
src/components/tables/PoolsTable/TokenPills/BalanceTooltip.vue
src/components/tables/PoolsTable/TokenPills/StableTokenPill.vue
src/components/tables/PoolsTable/TokenPills/TokenPills.vue
src/components/tables/PoolsTable/TokenPills/WeightedTokenPill.vue
src/locales/default.json

Adds balance tooltip according to #1735 

feat: add balance tooltip

---

src/components/tables/PoolsTable/TokenPills/TokenPills.vue

Fixes #1789 pill spacing issue

---

package-lock.json
package.json
src/components/_global/BalTable/BalTable.vue
src/components/contextual/pages/vebal/LMVoting/GaugesTable.vue

Hotfix - table vote btn

---

package-lock.json
package.json
src/locales/default.json

Update L2 incentives alert copy

---

src/components/inputs/TokenSearchInput.vue

Removes veBAL from the token filter as described in #1787
I've tweaked the component to use the setup syntax.

fix: remove vebal from token filter

---

package-lock.json
package.json
src/composables/trade/useSor.ts

Fix trade value snapping

---

package-lock.json
package.json

Release 1.52.0

---

package-lock.json
package.json
src/composables/useClaimsData.ts
src/lib/abi/LiquidityGaugeV5.json
src/locales/default.json
src/pages/claim.vue
src/services/balancer/gauges/gauges.decorator.ts

Fixes claiming staking rewards on L2s.
n/a

Hotfix - fix l2 claiming

---

package-lock.json
package.json
public/data/voting-gauges.json
src/composables/trade/useSor.ts
src/composables/useClaimsData.ts
src/constants/voting-gauge-pools.ts
src/lib/abi/LiquidityGaugeV5.json
src/locales/default.json
src/pages/claim.vue
src/services/balancer/gauges/gauges.decorator.ts

Hotfix - add voting gauges

---

src/composables/useNumbers.spec.ts
src/composables/useNumbers.ts

Format very small percentages

---

package-lock.json
package.json
src/locales/default.json

The claim page on L2s had some copy that stated "No staking is required for now" which is no longer true. This PR revises that wording.
n/a

Hotfix - L2 claiming label update

---

package-lock.json
package.json
src/components/_global/BalTable/BalTable.vue
src/components/forms/pool_actions/WithdrawForm/components/WithdrawPreviewModal/WithdrawPreviewModal.vue
src/components/forms/pool_actions/WithdrawForm/components/WithdrawPreviewModal/components/WithdrawActions.vue

Hotfix: Fix Table Sorting

---

package-lock.json
package.json
src/composables/useNumbers.spec.ts
src/composables/useNumbers.ts
src/services/aave/aave.service.ts
src/services/multicalls/erc20.multicaller.ts

Hotfix - aave aprs

---

package-lock.json
package.json
public/data/voting-gauges.json
src/lib/scripts/voting-gauge.generator.ts

Updated the voting gauge generation script to fetch pool information from Balancer's Subgraph instead of Pools API.

Hotfix - gauge generation

---

package-lock.json
package.json
src/components/_global/BalAsset/BalAsset.vue
src/components/_global/BalTable/BalTableRow.vue
src/components/contextual/pages/vebal/LMVoting/GaugesTable.vue
src/components/images/Avatar.vue
src/plugins/components.ts

This PR fixes a console error that was being thrown by the Jazzicon component on every render. It had something to do with it being imported within a component rather than at the app level. There are also a couple of minor style fixes included.
n/a

Hotfix - fix jazzicon error

---

package-lock.json
package.json
src/components/_global/BalAsset/BalAsset.vue
src/components/_global/BalTable/BalTableRow.vue
src/components/contextual/pages/vebal/LMVoting/GaugesTable.vue
src/components/images/Avatar.vue
src/plugins/components.ts

Hotfix - Jazzicon fix 2

---

package-lock.json
package.json

Synthetix assets warning

---

src/services/pool/calculator/weighted.ts

Not a big deal, but the variable name here is incorrect, should be `tokenAmountOut`, not `bptAmountIn`.

rename the variable for clarity, it is tokenAmountOut not bptAmountIn

---

package-lock.json
package.json
src/components/contextual/pages/pool/PoolBalancesCard/Pool.vue
src/components/modals/VeBalRedirectModal.vue

Release 1.54.0

---

package-lock.json
package.json
src/locales/default.json

Hofix - update vuln link

---

.eslintrc.js
package-lock.json
src/components/_global/BalChip/BalChip.vue
src/components/_global/BalModal/BalModal.vue
src/components/tables/PoolsTable/TokenPills/HiddenTokensPills.vue
src/components/tables/PoolsTable/TokenPills/TokenPills.vue

There were some warnings in our build output. This PR cleans up those warnings.
n/a

Build cleanup

---

package-lock.json
package.json
src/composables/usePoolWarning.ts
src/locales/default.json

Adjust stable pool warning statement for L2 pools.
n/a

Hotfix - update warning copy

---

package-lock.json
package.json
src/components/contextual/stake/StakePreview.vue
src/composables/usePoolWarning.ts
src/locales/default.json

Hotfix - hide staking preview yield

---

package-lock.json
package.json
src/services/pool/calculator/stable.ts

Fixes #1922 - Use priceRate for amounts in bptForTokensZeroPriceImpact.
Replicate issue as described in linked issue. Price impact should be correct.

Use priceRate for amounts in bptForTokensZeroPriceImpact.

---

package-lock.json
package.json

Release 1.56.0

---

Dockerfile.dev
README.md
docker-compose.yml

Proposing to use local node_modules instead of a cached docker layer.
Pros: 
- no need for image rebuilding when changing dependency packages
- former resulting in more free HDD space
Cons:
- need to install dependencies manually before starting the app
Start up docker-compose locally and see if it's working fine:
```bash
docker-compose build
docker-compose run --rm web npm i
docker-compose up
```
No impact on visuals.

Docker development with local node_modules

---

package-lock.json
package.json

Release 1.58.0

---

package-lock.json
package.json
src/components/contextual/pages/pool/PoolTransactionsCard/TradeTransactions/Table.vue

Hotfix fix avatars in trade table

---

package-lock.json
package.json
src/composables/usePool.ts

Hotfix dont show stablephantom bpt token

---

package-lock.json
package.json
src/constants/tokens.ts
src/providers/local/staking/userUserStakingData.ts
src/services/pool/calculator/calculator.sevice.ts

Hotfix - Single asset max withdrawals

---

src/lib/scripts/voting-gauge.generator.ts

The gauge generator was constantly timing out for me and I couldn't tell why so added some debug logs to debug it more easily in the future.

Add logs and fix typos in gauge generator

---

src/composables/queries/useGraphQuery.ts
src/lib/config/homestead.json
src/lib/config/index.ts
src/pages/index.vue
src/services/balancer/subgraph/balancer-subgraph.client.ts
src/services/config/config.service.ts

This uses the decentralized graph as the subgraph endpoint

use the decentralized graph endpoint

---

package-lock.json
package.json
src/composables/trade/useSor.ts

Bumps SDK to 0.1.15. Has new SOR version (4.0.1-beta.0) that introduces a general graph algorithm to create the paths through boosted pools.
Gasless trading (using SOR) should function correctly. Try testing on Mainnet and Polygon. Would be good to go through ZeKrakens weekly testing too.
N/A.

Bump SDK to 0.1.15. SOR has new algo for boosted pools.

---

package-lock.json
package.json
src/services/web3/web3.plugin.ts

TRM is having an outage right now and this is causing a partial app outage as now no users can connect their wallet to the frontend. Response being received from TRM:
```
curl -X POST --data '[{"address": "0xaD66946538E4B03B1910DadE713feBb8B59Cff60"}]' https://api.trmlabs.com/public/v1/sanctions/screening
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta charset="utf-8">
<title>Application Error</title>
<style media="screen">
html,body,iframe {
margin: 0;
padding: 0;
}
html,body {
height: 100%;
overflow: hidden;
}
iframe {
width: 100%;
height: 100%;
border: 0;
}
</style>
</head>
<body>
<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
</body>
</html>
```
Removing the disconnect on TRM error for now so that …

Dont disconnect on TRM error

---

package-lock.json
package.json
src/lib/config/arbitrum.json

Hotfix: Use infura for arbitrum RPC Endpoint

---

src/components/navs/AppNav/AppNavNetworkSelect.vue
src/components/pool/PoolChartPeriodSelect.vue
src/locales/default.json

Updated the styling on select labels to make them feel less selectable.

Improved selector label styling and label text

---

package-lock.json
package.json

Some graph updates were deployed to production that broke trading on Polygon and Arbitrum. Fixes were implemented in the SDK but a new version hasn't been released so instead I did a build to a branch and are using that for now. 
- Test that trading works on polygon/arbitrum. 
- This is a new SDK update so anything could break, check that general app functionality works correctly as well.

Hotfix: Update sdk to 0.1.18

---

package-lock.json
package.json
src/App.vue

Hotfix - fix transaction notifications (develop merge)

---

package-lock.json
package.json

Release 1.64.0 (develop merge)

---

package-lock.json
package.json

Release 1.64.1 (develop merge)

---

package-lock.json
package.json

Release 1.65.0 (develop merge)

---

package-lock.json
package.json

Release 1.66.0 (develop merge)

---

src/services/web3/connectors/metamask/metamask.connector.ts
src/services/web3/useWeb3.ts

See title
Test with coinbase wallet, should automatically attempt to connect with that wallet. If metamask, don't.
N/A

Only auto connect if coinbase wallet is current provider

---

src/composables/queries/useStreamedPoolsQuery.ts

Fix "Filter by token"

---

package-lock.json
package.json
src/constants/tokenlists.ts
src/lib/scripts/voting-gauge.generator.ts

The voting gauge script has been failing because Tracer token list isn't working -- we're reaching out to them to check if there's a new endpoint. To avoid this happening again, I added a filter to drop invalid responses and log the error to the console.

hotfix: voting gauge script

---

package-lock.json
package.json
src/composables/queries/usePoolQuery.ts
src/services/pool/pool.service.ts

Hotfix: total shares bug (develop merge)

---

package-lock.json
package.json
src/components/forms/pool_actions/InvestForm/InvestForm.vue
src/components/inputs/TokenSelectInput/TokenSelectInput.vue
src/lib/utils/index.ts

Release 1.67.0 (develop merge)

---

package-lock.json
package.json
src/lib/config/polygon.json

Switches polygon http RPC back to Infura.
n/a

Hotfix: Use infura for polygon RPC

---

src/components/_global/BalTable/BalTable.vue

Fix load more button issue #1989

---

package-lock.json
package.json

Release 1.68.0 (develop merge)

---

package-lock.json
package.json
src/App.vue
src/constants/exploits.ts
src/services/web3/useWeb3.ts
src/services/web3/web3.plugin.ts

Hotfix - Update trm sanctions endpoint

---

package-lock.json
package.json
src/App.vue
src/constants/exploits.ts
src/services/web3/useWeb3.ts
src/services/web3/web3.plugin.ts

Hotfix/update trm sanctions endpoint (develop merge)

---

src/components/_global/BalBreakdown/BalBreakdown.vue
src/components/contextual/pages/pools/UnstakedPoolsTable.vue
src/components/heros/PortfolioPageHero.vue
src/components/tables/PoolsTable/PoolsTable.vue
src/components/tooltips/APRTooltip/APRTooltip.vue
src/pages/index.vue

Minor design fixes after design details session with Pon.
- APR tootip text alignment and spacing fix.
- More height for the home page pools table loading state.
- Add title for unstaked pools table on portfolio page for L2s
- Have $0 number for title on portfolio page when wallet disconnected.
No functionality should be affected.
n/a

Design details

---

src/pages/privacy-policy.vue

Updates to the privacy policy which better reflect how we collect, share and store user information.
- Needs to be reviewed by Legal.

Privacy Policy updates

---

src/components/cards/MyPoolBalancesCard/MyPoolBalancesCard.vue
src/pages/_layouts/PoolTransferLayout.vue

Include staked balance on Invest Page MyPoolBalancesCard. Closes #1845 
1. Go to pool page
2. See the token balances on My pool balance card
3. Click "Invest"
4. Invest page's My Pool balance card should show same amounts
| Invest page | Pool page |
| --- | --- |
| ![Screen Shot 2022-08-26 at 14 26 13](https://user-images.githubusercontent.com/28311328/186893683-9c00d5d4-179b-40ac-afe0-2d7a37c76995.png) | ![Screen Shot 2022-08-26 at 14 25 44](https://user-images.githubusercontent.com/28311328/186893687-3d5ada0c-b13a-473b-9899-ceec46bef4c4.png) |

Include staked balance on Invest Page MyPoolBalancesCard

---

package-lock.json
package.json
src/components/contextual/pages/pool/PoolTransactionsCard/TradeTransactions/Table.vue

Release 1.69.0 (develop merge)

---

src/components/_global/BalTable/BalTable.vue

Fixes issue with `bodyRef` `onScroll` event. There were plenty errors in sentry with it

Fix BalTable error

---

src/components/_global/BalAsset/BalAssetSet.vue
src/components/cards/MyPoolBalancesCard/components/AssetRow.vue
src/components/cards/MyWalletTokensCard/MyWalletTokensCard.vue
src/components/inputs/TokenSearchInput.vue
src/components/inputs/TokenSearchInputSelectTokens.vue
src/components/modals/SelectTokenModal/SelectTokenModal.vue
src/components/navs/AppNav/AppSidebar/AppSidebar.vue
src/pages/_layouts/FocusedLayout.vue
src/pages/_layouts/PoolTransferLayout.vue
src/pages/index.vue

Minor design detail updates. See commits for change descriptions.
Nothing should break
n/a

Design detail updates

---

package-lock.json
package.json

Release 1.70.0 (develop merge)

---

src/__mocks__/pool.ts
src/components/cards/CreatePool/SimilarPoolsCompact.vue
src/components/contextual/pages/pool/PoolChart.vue
src/components/forms/lock_actions/LockForm/components/LockPreviewModal/components/LockAmount.vue
src/components/forms/lock_actions/UnlockForm/components/UnlockPreviewModal/components/UnlockAmount.vue
src/components/tables/PoolsTable/PoolsTable.vue
src/components/tables/PoolsTable/TokenPills/BalanceTooltip.vue
src/components/tables/PoolsTable/TokenPills/HiddenTokensPills.vue
src/components/tables/PoolsTable/TokenPills/StableTokenPill.vue
src/components/tables/PoolsTable/TokenPills/TokenPills.vue
src/components/tables/PoolsTable/TokenPills/WeightedTokenPill.vue
src/composables/pools/usePools.ts
src/composables/queries/usePoolsQuery.ts
src/pages/claim.vue
src/pages/portfolio.vue
src/services/pool/concerns/apr/apr.concern.spec.node.ts
src/services/pool/types.ts

Minor fixes

---

src/components/contextual/pages/vebal/LMVoting/GaugesTable.vue
src/components/icons/IconLimit.vue
src/locales/default.json

Cherry picked a commit by @Matthews3301 from #2181 to display the cap icon based on the new schema introduced in #2207 

Add cap icon

---

src/lib/scripts/voting-gauge.generator.ts

Voting gauge generator script got messed up on develop during a merge, this fixes that by syncing with what's on master.

Fix messed up merge

---

package-lock.json
package.json

Release 1.71.0 (develop merge)

---

src/components/contextual/pages/pool/PoolTransactionsCard/BoostedPoolActivities/Activities.vue
src/components/contextual/pages/pool/PoolTransactionsCard/PoolActivities/Activities.vue
src/components/contextual/pages/pool/PoolTransactionsCard/TradeTransactions/TradeTransactions.vue
src/components/forms/pool_actions/InvestForm/components/InvestPreviewModal/components/InvestActions.vue
src/components/forms/pool_actions/WithdrawForm/components/WithdrawPreviewModal/components/WithdrawActions.vue
src/components/pool/PoolPageHeader.vue
src/composables/contextual/pool-transfers/usePoolTransfers.ts
src/composables/usePoolWarning.ts
src/pages/_layouts/PoolTransferLayout.vue
src/pages/pool/_id.vue

Convert pool id param to lowercase

---

package-lock.json
package.json
src/components/_global/BalAlert/BalAlert.vue
src/components/modals/TradePreviewModalGP.vue

Release 1.72.0 (develop merge)

---

src/composables/usePoolWarning.ts
src/locales/default.json

We're not creating migration flows for all pools affected by the vulnerability. This PR updates the copies of all pools to make them consistent.
cc @pkattera for copy review
Merge only when pool migration feature goes live

update stablepools vulnerability copies

---

package-lock.json
package.json
public/data/hardcoded-gauges.json
public/data/vebal-gauge.json
public/data/voting-gauges.json
src/components/contextual/pages/vebal/LMVoting/GaugesTable.vue
src/constants/voting-gauges.ts
src/lib/scripts/voting-gauge.generator.ts

hotfix: add chip to new gauges (develop merge)

---

src/composables/usePool.ts
src/services/balancer/gauges/entities/gauges/query.ts
src/services/balancer/gauges/types.ts
src/services/staking/staking-rewards.service.ts

Only use preferential gauges for bal APRs

---

package-lock.json
package.json

Release 1.72.2 (develop merge)

---

package-lock.json
package.json

Release 1.73.0 (develop merge)

---

package-lock.json
package.json
src/lib/config/arbitrum.json
src/services/lido/lido.service.ts

Fix stETH apr for weighted pools (develop merge)

---

package-lock.json
package.json
public/data/voting-gauges.json
src/constants/voting-gauge-pools.ts
src/lib/config/optimism.json

Add the following approved gauges to JSON and fix the Beets Subgraph URL.
- https://snapshot.org/#/balancer.eth/proposal/0x126128c42bbaa9b6f371a7cb69abdbbedf0f97d26213e666f5f083ca9e742145
- https://snapshot.org/#/balancer.eth/proposal/0x73fb4bf6aa723ba2d803d8db7c605dc40ac61338770648c68f401c3e45900863
- https://snapshot.org/#/balancer.eth/proposal/0x8649212927a11958db985613552b74ba5753f491b009542b8ea83a520456e6e8

add voting gauges

---

src/composables/queries/usePoolSnapshotsQuery.ts
src/services/balancer/subgraph/entities/poolSnapshots/index.ts
src/services/balancer/subgraph/entities/poolSnapshots/query.ts
src/services/balancer/subgraph/subgraph-fallback.service.ts

We need to be sure that decentralised url works properly, that’s why we need to call sentry `captureException` method.
Other urls errors  will be handled higher, in functions that use this subgraph fallback service.
So, we call sentry captureException method only with decentralized url

Change subgraph fallback service error handling

---

src/services/config/config.service.ts

Add dev graph key env variable, which allows to use decentralised endpoint while developing (without domain restrictions).

Add dev graph key env variable

---

src/services/balancer/subgraph/entities/pools/query.ts

Adds a pool's token tree (up to 3 levels deep) to the default pool schema.
- Nothing should be affected by this change since it's just an addition to the existing schema.
n/a

Add pool token tree schema to default pool attributes

---

src/providers/local/staking/userUserStakingData.ts

There is an error in `userUserStakingData.ts` during the migration flow. This pr fixes this.
During the migration flow there shouldn't be this error

Fix user staking composable error

---

package-lock.json
package.json

Release 1.75.0 (develop merge)

---

.github/workflows/checks.yml
.vscode/settings.json
package-lock.json
package.json
src/jest/jest.setup-suite.ts
src/services/balancer/gauges/gauges-subgraph.client.spec.node.ts
src/services/balancer/gauges/gauges-subgraph.service.spec.node.ts
src/services/gas-price/providers/blocknative.provider.spec.node.ts
src/services/ipfs/ipfs.service.spec.node.ts
src/tests/msw/handlers.ts
src/tests/msw/server.ts

This is the first basic [MSW](https://mswjs.io/) setup that replaces _nock_. 
The handlers setup should be better arranged and we should probably include Typescript builders to improve the control of the mocked responses from the tests but, we can iteratively do that while we discover our needs in future tests.      

Replace nock with msw

---

src/__mocks__/pool.ts
src/composables/usePool.spec.ts
src/composables/usePool.ts
src/services/balancer/subgraph/entities/pools/query.ts
src/services/pool/types.ts

Extract leaf tokens from tree. For LinearPools only extract mainTokens.
Unit test for `tokenTreeLeafs` should work.
n/a

Add function to parse leaf tokens from tree

---

src/main.ts

Removes provider parameter that was not being used when installing `Web3Plugin`.

Remove unused Web3Plugin setup parameter

---

package-lock.json
package.json
src/components/contextual/pages/pool/PoolActionsCard.vue
src/components/forms/pool_actions/MigrateForm/constants.ts
src/components/tables/PoolsTable/PoolsTable.vue

Add possibility to invest in mai4 pool and remove warning on pools table.

Hotfix: Add possibility to invest in mai4 pool 

---

src/components/contextual/stake/StakePreview.vue

Removes redundant variable and sets currentShares as a static property.
n/a

Refactor StakePreview proposal

---

src/composables/pools/useExitPool.ts
src/constants/symbol.keys.ts
src/providers/local/exit-pool.provider.ts

Adds the ExitPoolProvider. Note that it doesn't really work yet, this PR is just to get the files in place.
n/a
n/a

Add ExitPoolProvider

---

src/components/_global/BalAsset/BalAssetSet.vue
src/components/cards/PairPriceGraph/PairPriceGraph.vue
src/components/links/BridgeLink.vue
src/pages/trade.vue

- Fixes token overlay issue on gauges table.
- Adds bridge link to L2 trade page.
TODO
TBD

Style updates

---

package-lock.json
package.json

Release 1.76.0 (develop merge)

---

src/components/pool/PoolMigrationWarningTooltip.vue
src/components/tables/BalClaimsTable.vue
src/components/tables/PoolsTable/PoolsTable.vue

This pr adds friendly names on claims page and migration warning tooltip. Closes https://github.com/balancer-labs/frontend-v2/issues/2256

Display the friendly names on claims page (Closes: #2256)

---

src/components/_global/BalRangeInput/BalRangeInput.vue
src/components/forms/pool_actions/WithdrawForm/composables/useWithdrawMath.ts

This pr fixes proportional withdraw. It is almost impossible now to perform proportional withdraw from new bbaUsd pool on mainnet.

Fix proportional withdraw

---

src/App.vue
src/composables/useNavigationGuards.ts
src/composables/useNetwork.spec.ts
src/composables/useNetwork.ts
src/plugins/router/index.ts
src/plugins/router/nav-gaurds.ts
src/plugins/router/nav-guards.ts

Moves logic around and extracts into functions to be more understandable.
n/a

Refactor network nav gaurds

---

src/components/modals/TradePreviewModalGP.vue

Have been running into lots of divide by zero errors using the app. Quick fix

Fix divide by zero for quote update

---

src/components/contextual/pages/pool/PoolContractDetails.vue

Fix swap fee display in details table on pool page.

Fix swap fee display in pool detail table

---

src/services/web3/web3.plugin.spec.ts
src/services/web3/web3.plugin.ts
src/tests/msw/handlers.ts

New unit test to check that `TRM endpoint` (`https://api.balancer.fi/wallet-check`) detects sanctioned addresses.
- [x ] Other

Add spec to test TRM wallet-check

---

babel.config.js
package-lock.json
package.json
src/__mocks__/vuex.ts
src/jest/jest.setup-suite.ts
src/services/contracts/vault.service.spec.ts
src/services/contracts/vault.service.ts
src/store/modules/app.ts

App was using max uint256 for trade deadline which is a lot of wasted non-zero calldata bytes 😢 . This will save a few hundred gas per swap.
Please excuse my Vue hacks, I'm not sure if the AppState store is being used or if I added it to a service correctly.
Swap and confirm the trade deadline timestamp is the default of 100 mins

Update trade deadline

---

src/components/_global/BalDetailsTable/BalDetailsTable.vue
src/components/contextual/pages/pool/PoolContractDetails.vue
src/locales/default.json
src/services/pool/types.ts

Add amp factor to pool details table.
- Open any stable pool
- Find amp factor row in pool details table 

Add amp factor to pool details table

---

src/components/_global/BalTable/BalTable.vue
src/components/cards/TrendingPairs/TrendingPairs.vue
src/components/tables/BalClaimsTable.vue
src/components/tables/PoolsTable/TokenPills/StableTokenPill.vue
src/components/tables/PoolsTable/TokenPills/WeightedTokenPill.vue
src/components/tables/ProtocolRewardsTable.vue

- Syncs Stable/Weighted pill heights
- Updates column spacing in claims tables
- Fixes table header hover states if they are not sortable
See list of updates and inspect app.
Not required.

Weekly style updates/fixes

---

src/components/_global/BalActionSteps/BalActionSteps.vue
src/components/cards/TradeCard/TradeCard.vue
src/components/cards/TradeCard/TradeRoute.vue
src/components/contextual/pages/pool/PoolActionsCard.vue
src/components/contextual/pages/pool/PoolTransactionsCard/BoostedPoolActivities/Table.vue
src/components/contextual/pages/pool/PoolTransactionsCard/InvestmentTransactions/InvestmentTransactions.vue
src/components/contextual/pages/pool/PoolTransactionsCard/PoolActivities/Table.vue
src/components/contextual/pages/pool/PoolTransactionsCard/TradeTransactions/Table.vue
src/components/contextual/pages/pool/PoolTransactionsCard/TradeTransactions/TradeTransactions.vue
src/components/footer/Footer.vue
src/components/forms/pool_actions/InvestForm/components/InvestPreviewModal/components/InvestActions.vue
src/components/forms/pool_actions/InvestForm/components/InvestPreviewModal/components/InvestSummary.vue
src/components/forms/pool_actions/MigrateForm/components/MigratePreviewModal/components/MigrateSummary.vue
src/components/forms/pool_actions/MigrateForm/constants.ts
src/components/heros/AppHero.vue
src/components/heros/HomePageHero.vue
src/components/heros/PortfolioPageHero.vue
src/components/modals/TradePreviewModal.vue
src/components/navs/AppNav/AppNavToggle.vue
src/components/navs/AppNav/AppSidebar/SidebarContent.vue
src/components/navs/AppNav/DesktopLinks/DesktopLinks.vue
src/composables/usePool.ts
src/locales/default.json
src/pages/index.vue
src/pages/pool/invest.vue
src/pages/portfolio.vue
src/pages/terms-of-use.vue

- New copy updates to use the terms 'Swap' & 'Pool' across the board.
- Minor change to the order of the navigation to place the verbs together (e.g. Pool / Swap / Claim)
- Review the app and make sure the new terms like Swap & Pool are applied consistently throughout the site.
- Check code to make sure nothing being used was deleted.
New navigation:
- [] I have requested at least 2 reviews (If the PR is significant enough, use best judgement here)

Messaging updates

---

package-lock.json
package.json

Release 1.77.0 (develop merge)

---

.eslintrc.js
src/components/_global/BalAccordion/BalAccordion.vue
src/components/_global/BalChart/BalChart.vue
src/components/_global/BalTable/BalTable.vue
src/components/_global/BalTextInput/BalTextInput.vue
src/components/_global/BalTooltip/BalTooltip.vue
src/components/btns/TxActionBtn/TxActionBtn.vue
src/components/contextual/pages/pool/PoolChart.vue
src/components/contextual/pages/pool/PoolTransactionsCard/BoostedPoolActivities/Table.vue
src/components/contextual/pages/pool/PoolTransactionsCard/PoolActivities/Table.vue
src/components/contextual/pages/pool/PoolTransactionsCard/TradeTransactions/Table.vue
src/components/inputs/TokenInput/TokenInput.vue

Remove eslint rule vue/require-default-prop

Remove eslint rule vue/require-default-prop

---

src/components/forms/pool_actions/WithdrawForm/WithdrawFormV2.vue
src/components/forms/pool_actions/WithdrawForm/components/ProportionalWithdrawalInputV2.vue
src/composables/usePool.ts
src/providers/local/exit-pool.provider.ts

Refactors component to use provider exclusively.
n/a
n/a

Refactor ProportionalWithdrawalInputV2

---

package-lock.json
package.json

Updates `bnc-sdk` to 3.7.1 which fixes a websocket reconnection issue
Confirm tx tracked correctly

Update blocknative sdk to fix websocket reconnection issue

---

src/composables/queries/usePoolsQuery.ts
src/services/pool/decorators/pool.decorator.ts
src/services/pool/pool.service.ts
src/services/staking/staking-rewards.service.ts

Аdd sdk total liquidity calculation for single pool.

Аdd sdk total liquidity calculation

---

package-lock.json
package.json

Updates SDK package. Mainly SOR bug fixes. Notes [here](https://github.com/balancer-labs/balancer-sdk/releases/tag/v0.1.36).
Should fix previously reported issues with trade page.

Hotfix: Fix SOR bugs

---

jest.config.js
package-lock.json
package.json
src/__mocks__/pool.ts
src/composables/usePool.spec.ts
src/composables/usePool.ts
src/jest/jest.setup-suite.ts
src/providers/local/exit-pool.provider.ts
src/services/balancer/subgraph/entities/pools/query.ts
src/services/pool/types.ts
tsconfig.json

Adds option for including or excluding pre-minted bpt in flat token tree.

Fix: flat token tree

---

package-lock.json
package.json
src/components/forms/pool_actions/InvestForm/components/InvestPreviewModal/components/InvestActions.vue
src/components/forms/pool_actions/WithdrawForm/components/WithdrawPreviewModal/components/WithdrawActions.vue
src/composables/trade/useSor.ts
src/composables/useNumbers.ts

Fathom expects event values in cents.
n/a
n/a

Hotfix: Fix Fathom event values

---

package-lock.json
package.json
src/constants/pools.ts

Adding the most recent additions from the subgraph.

update list of ExcludedPoolTypes

---

package-lock.json
package.json

Release 1.79.0 (develop merge)

---

package-lock.json
package.json

Bumps SDK version to 0.1.38
n/a

Hotfix: update sdk version

---

package-lock.json
package.json
src/composables/trade/useGnosis.ts
src/composables/trade/useSor.ts
src/composables/useFathom.ts

Track trade types in Fathom, e.g. through Balancer or Gnosis.
n/a
n/a

Hotfix: track trade types

---

package-lock.json
package.json
src/composables/trade/useSor.ts
src/composables/useFathom.ts

We need to compare Gnosis swaps against only mainnet Balancer swaps so this PR adds event tracking for that.
n/a
n/a

Hotfix: track mainnet swaps

---

package-lock.json
package.json
src/services/web3/web3.plugin.ts
src/tests/msw/handlers.ts

Pass check-wallet address as a query param (Develop Merge)

---

package-lock.json
package.json

Release 1.80.0 (develop merge)

---

src/locales/default.json
src/pages/claim.vue

Minor copy tweaks and new tooltips for the Claims page tables. 
New table headings with tooltips:

Updated claim page table headers

---

package-lock.json
package.json
public/data/hardcoded-gauges.json
public/data/vebal-gauge.json
public/data/voting-gauges.json
src/constants/voting-gauges.ts
src/lib/scripts/voting-gauge.generator.ts
src/services/pool/exchange/serializers/ExitParams.ts

add isKilled to voting gauges (develop merge)

---

src/components/contextual/pages/pool/invest/InvestPageInvestBlock.vue
src/composables/pools/useInvestPageTabs.ts
src/composables/usePool.ts

See title.
n/a
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1203441928704672

If deep pool but no pre-minted BPT hide swap join

---

package-lock.json
package.json
src/components/navs/AppNav/AppNavNetworkSelect.vue
src/lib/utils/browser.ts
src/plugins/router/nav-guards.ts

This pr fixes bug with IOS chrome/metamask browsers freeze when network is changed
Change network in chrome browser in IOS, there shouldn't be any freeze.

Hotfix: ios freeze on network change

---

package-lock.json
package.json

Release 1.81.0 (develop merge)

---

package-lock.json
package.json
src/components/tooltips/APRTooltip/components/StakingBreakdown.vue

Hotfix staking apr scaling (Develop Merge)

---

src/lib/balancer.sdk.ts

No need to pass tenderly config into SDK since we're using proxy endpoint lambda.
n/a

Remove tenderly config

---

src/components/contextual/pages/pool/PoolTransactionsCard/PoolActivities/Table.vue
src/composables/usePool.spec.ts
src/composables/usePool.ts
src/pages/pool/_id.vue

After API usage, title tokens included the BPT token. This PR removes BPT from the titleTokens computed property.
n/a

Remove BPT from title tokens

---

package-lock.json
package.json

Release 1.82.0 (develop merge)

---

src/pages/claim.vue

Claim on ethereum href was broken. This PR fixes it by removing old subdomain property and using id instead (as we no longer need "app" subdomain for ethereum)

Fix claim on ethereum href

---

README.md

Digital Ocean deploy button was linking to a deleted branch. Updated that and added Vercel and Netlify to address #2153 
Click the buttons, confirm the deployment process loads

fix digital ocean button and add vercel, netlify

---

src/components/_global/BalTable/BalTable.vue
src/components/contextual/pages/pools/StakedPoolsTable.vue
src/components/contextual/pages/pools/UnstakedPoolsTable.vue
src/components/contextual/pages/pools/VeBalPoolTable.vue
src/components/tables/PoolsTable/PoolsTable.vue

Addresses #2212. Also adds a sortColumn prop to the `PoolsTable` component
Confirm columns show for portfolio and main pool pages and are properly sorted.
New column on the portfolio page

Adds pool value to portfolio page. creates sortColumn on PoolsTable

---

src/components/cards/TradeCard/TradePair.vue
src/components/inputs/TokenInput/TokenInput.vue

Fix exactIn setting on pair toggle or max click

---

package-lock.json
package.json
src/composables/queries/useTokenPricesQuery.ts
src/providers/tokens.provider.ts

Release 1.83.0 (develop merge)

---

package-lock.json
package.json
src/lib/config/homestead.json

hotfix: Use hosted graph endpoint

---

src/components/_global/BalAccordion/BalAccordion.vue
src/components/cards/MyWallet/MyWallet.vue
src/components/contextual/pages/pool/PoolTransactionsCard/InvestmentTransactions/InvestmentTransactions.vue
src/locales/default.json
src/pages/trade.vue

Weekly style fixes.
- Fixed padding of connect wallet on swap page.
- Fixed minor issue with swap page accordion styling.
- Update title for transactions table on boosted pool pages.
n/a
-

Style fixes

---

package-lock.json
package.json

Release 1.84.0 (develop merge)

---

package-lock.json
package.json
src/services/gas-price/gas-price.service.spec.ts
src/services/gas-price/gas-price.service.ts

Now if there is any error during calling `settingsForContractCall` function, it returns `undefined`, this pr fixes it

Fix contract call settings error process

---

package-lock.json
package.json
src/locales/default.json

Minor spelling fix for warning.
n/a
n/a

Hotfix: fix typo

---

src/components/_global/BalActionSteps/BalActionSteps.vue
src/components/contextual/stake/StakePreview.vue
src/components/forms/pool_actions/InvestForm/components/InvestPreviewModal/components/InvestActions.vue
src/components/forms/pool_actions/InvestForm/components/InvestPreviewModal/components/InvestActionsV2.vue
src/components/forms/pool_actions/WithdrawForm/components/WithdrawPreviewModal/components/WithdrawActions.vue
src/components/forms/pool_actions/WithdrawForm/components/WithdrawPreviewModal/components/WithdrawActionsV2.vue
src/providers/local/exit-pool.provider.ts
src/providers/local/join-pool.provider.ts

chore: Capture more exceptions & throw friendlier error messages

---

src/components/contextual/pages/claim/LegacyClaims.vue
src/composables/queries/useUserClaimsQuery.ts
src/locales/default.json
src/services/claim/claim.service.ts
src/services/claim/types.ts

Estimates for the pending legacy claims are no longer needed.

Remove pending legacy claims tab and calcs

---

src/components/contextual/pages/pool/PoolCompositionCard/components/TokenBreakdown.vue

Deep pools with more than 2 levels have broken tree structures. This PR fixes that.
A visual check to see that it looks like the right hand side shot below, at all screen sizes.

3-level deep pool tree structure fix

---

src/components/_global/BalAsset/BalAssetSet.vue
src/components/heros/HomePageHero.vue
src/components/pool/PoolPageHeader.vue
src/components/tables/PoolsTable/PoolsTableActionsCell.vue
tailwind.config.js

- [Fix BalAsset border color and shape](https://github.com/balancer-labs/frontend-v2/commit/8d1a7770d5c23396d434913f35a43a7d7e40aee1)
- [Adjust PoolPageHeader layout](https://github.com/balancer-labs/frontend-v2/commit/a31186204709781cb33b8782fbec33bdf264a031)
- [Update home page title font weight](https://github.com/balancer-labs/frontend-v2/commit/f39bc462b769705fe1363597aa27b678440c5b2e)
- [Stop row click event propagation for stake and migrate buttons](https://github.com/balancer-labs/frontend-v2/commit/7f88e2caf2d361833c791fd2dfde8d47b7423996)
n/a
n/a

Weekly style fixes

---

package-lock.json
package.json
src/lib/config/arbitrum.json

Arbitrum graph endpoint (Develop Merge)

---

package-lock.json
package.json

Release 1.85.0 (develop merge)

---

src/components/_global/BalLazy/BalLazy.vue
src/components/_global/BalTable/BalTable.vue
src/components/contextual/pages/vebal/LMVoting/GaugesTable.vue
src/components/footer/Footer.vue
src/components/sections/FeaturedProtocols.vue
src/pages/vebal.vue
src/types/global-components.d.ts

This pr adds optimisation of veBal table render + adds `v-once` to some components

Add optimisation to veBal table render

---

src/components/_global/BalAccordion/BalAccordion.vue

Test the different accodions in the app. For instance:
- Go to swap page
- Open browser devtools and change device format to test mobile device format

Remove animejs from BalAccordion

---

src/components/pool/__mocks__/sample-pool.json
src/constants/pools.ts
src/lib/config/gnosis-chain.json
src/services/pool/decorators/pool.decorator.ts
src/services/pool/pool.service.ts

A couple of fixes for pool loading on Gnosis chain.
n/a
n/a

fix: pool loading bugs

---

package-lock.json
package.json
src/components/cards/TradeCard/TradeCard.vue
src/composables/trade/useTrading.ts

Cowswap changes their API so the endpoint we were using doesn't work anymore.
n/a

Hotfix: disable gasless trading

---

package-lock.json
package.json
src/lib/utils/balancer/lido.ts

This pr fixes bug with converting stEth -> wstEth and vice versa on trade page.

Hotfix: fix stEth trade calculation

---

package-lock.json
package.json
src/components/contextual/pages/pools/StakedPoolsTable.vue
src/components/contextual/pages/pools/UnstakedPoolsTable.vue
src/components/contextual/stake/StakeSummary.vue
src/composables/queries/usePoolsQuery.ts
src/providers/local/staking/userUserStakingData.ts

Release 1.86.0 (develop merge)

---

src/locales/default.json

Fix: typos

---

package-lock.json
package.json

The new SDK version fixes an ESM bundling problem introduced in SDK `v0.1.45.beta.8`.

Update balancer SDK to v 0.1.46

---

package-lock.json
package.json

Updates SDK to [v0.1.47](https://github.com/balancer-labs/balancer-sdk/releases/tag/v0.1.47)
- Adds Gnosis tokens and pools.
- Updates APRs to use weekly emissions extrapolated to yearly.
- SOR uses configurable connecting tokens to extend boosted pool routes.

Update SDK to v0.1.47

---

package-lock.json
package.json
src/lib/config/polygon.json

Hotfix: temporarily disable polygon api with bad data

---

package-lock.json
package.json
src/lib/config/arbitrum.json

Disables the balancer api so fallback to subgraph happens

Hotfix: Disable api on arbitrum

---

package-lock.json
package.json
src/lib/config/arbitrum.json
src/lib/config/polygon.json

Reenable balancer api (Develop Merge)

---

package-lock.json
package.json

Release 1.87.0 (develop merge)

---

package-lock.json
package.json
src/constants/pools.ts

Hotfix: add pools to allowlist

---

package-lock.json
package.json
src/composables/trade/useSor.ts

Hotfix: wsteth price impact

---

package-lock.json
package.json
src/components/cards/TradeCard/TradeCard.vue
src/composables/trade/useJoinExit.spec.ts
src/composables/trade/useJoinExit.ts
src/composables/trade/useSor.ts
src/composables/trade/useTrading.ts
src/composables/trade/useValidation.ts

Fixes a variety of issues with the swap UI.
- [fix: Prevent join/exit overwriting sor output if no returnAmount](https://github.com/balancer-labs/frontend-v2/commit/a413819263f741f459e28e3cb9bdbd4c2aa75d8e)
- [fix: Handle No Liquidity errors directly in useSOR](https://github.com/balancer-labs/frontend-v2/commit/6fdddea66bbebb8533d2427d7d6f5abadb4117cd)
n/a

Hotfix: SOR issues

---

src/services/staking/staking-rewards.service.ts

This pr fixes user boost value calculation

Fix user boost value calculation

---

src/lib/config/arbitrum.json
src/services/gas-price/providers/arbitrum.provider.spec.ts

Migrating RPC provider on Arbitrum from Infura to Alchemy.
n/a

Change Arbitrum RPC url

---

package-lock.json
package.json
src/pages/pool/_id.vue
src/providers/local/pool-staking.provider.ts
src/providers/tokens.provider.ts

Release 1.88.0 (develop merge)

---

package-lock.json
package.json
src/constants/pools.ts

Adds new factory keys so pool page titles are correct.
n/a

Hotfix: add new factory

---

src/components/_global/BalBlankSlate/BalBlankSlate.vue
src/components/_global/BalTable/BalTableRow.vue
src/components/contextual/pages/pool/PoolChart.vue
src/components/contextual/pages/pool/PoolStatCards.vue
src/components/tables/PoolsTable/PoolsTable.vue
src/composables/usePool.ts
src/locales/default.json

Style updates after call with Pon.

Chore: weekly style updates

---

package-lock.json
package.json
src/components/tables/PoolsTable/PoolsTable.vue
src/pages/index.vue

Release 1.89.0 (develop merge)

---

package-lock.json
package.json
src/composables/swap/useSor.ts

Fixes Sentry issue: https://balancer-labs.sentry.io/share/issue/8200ef48bedd429ea8c082a6353564f0/
n/a

Hotfix: fraction component error

---

package-lock.json
package.json

Updates SDK to 1.0.0-beta.8.
- Fixes bug with exit for non AaveLinear
- Fixes bug with pool fetching
- Makes it easier to add new Linear types.
No specific tests but will avoid double loading pools.

Hotfix: Update SDK

---

.github/workflows/checks.yml

Uses github action to turn todo comments throughout the codebase into github issues. Uses: https://github.com/marketplace/actions/todo-to-issue
n/a
n/a

feat: Turn todo comments into issues

---

.github/CODEOWNERS
src/components/pool/branded-redirect/constants.ts

Add Codeowners file to request review automatically

feat: add codeowners file

---

.github/CODEOWNERS

feat: remove codeowners file

---

package-lock.json
package.json
src/components/tables/PoolsTable/PoolsTable.vue
src/composables/usePool.ts
src/constants/pools.ts

Don't show APR's or volumes above the threshold in the pools table  (develop merge)

---

package-lock.json
package.json
src/components/contextual/pages/pool/PoolChart.vue

Readd charts now that subgraph pricing fixed

add charts back

---

package-lock.json
package.json
src/constants/pools.ts

Factory address wasn't lowercase

fix polygon weighted v3 factory address

---

package-lock.json
package.json
src/composables/usePool.ts

Use `APR_THRESHOLD` from pool constants

fix wrong APR_THRESHOLD import

---

src/composables/usePool.ts

Remove old APR_THRESHOLD import

---

package-lock.json
package.json

Release 1.90.0 (develop merge)

---

package-lock.json
package.json
src/providers/tokens.provider.ts

A change to injectTokens meant pool pages didn't finish loading if a wallet was not connected. This PR fixes the responsible conditional.
n/a

Hotifx: pool loading

---

.github/workflows/develop-merge.yml
package-lock.json
package.json

Should fix github action that creates the develop merge PR after merging with master.
n/a
n/a

Hotfix: develop merge github action

---

package-lock.json
package.json
src/components/contextual/pages/pool/PoolChart.vue

Restores charts on the pool's page.

hotfix: restore pool charts

---

src/components/contextual/pages/pool/PoolContractDetails.vue
src/constants/pools.ts

feat: add meta name support in pool details table

---

package-lock.json
package.json
src/components/_global/BalActionSteps/BalActionSteps.vue
src/components/_global/BalChart/BalChart.vue
src/components/cards/SwapCard/SwapCard.vue
src/components/contextual/pages/pools/StakedPoolsTable.vue
src/components/contextual/pages/pools/UnstakedPoolsTable.vue

- [fix: Loading states on portfolio page](https://github.com/balancer-labs/frontend-v2/commit/604069df8eb951b202667fe1dbe23f0ffdfe80a8)
- [fix: Native asset deep links](https://github.com/balancer-labs/frontend-v2/commit/c94843ab6ff1834db43daf0358863f3afe427f9a) (https://balancer-labs.sentry.io/share/issue/300e3977bedf4eec854c52b57d1f89c3/)
- [fix: maximumFractionDigits error in charts](https://github.com/balancer-labs/frontend-v2/commit/18d0f6ce4496f305db1c8ae8b8496fb137f57c09) (https://balancer-labs.sentry.io/share/issue/6fa915ccd04d41d0a4a90d01fcfc7076/)
- [fix: Only capture error if is actually error](https://github.com/balancer-labs/frontend-v2/commit/9551e32d2a8e2689f5f61a3b78b946c05a1778e2) (https://balancer-labs.sentry.io/share/issue/587649fe1b3b428699fb16cd24994dfa/)
n/a

Hotfix: Fixes variety of sentry issues

---

package-lock.json
package.json
src/composables/usePool.ts

Revert isDeep setting for wstETH/bb-e-USD and temple/bb-e-USD.
n/a

Hotfix: revert is deep

---

package-lock.json
package.json
src/composables/usePool.ts

Add gearbox stable to deep pool list

treat gearbox stable as deep

---

package-lock.json
package.json

Release 1.91.0 (develop merge)

---

package-lock.json
package.json
src/components/navs/AppNav/AppNavNetworkSelect.vue

Removes GC options from network select dropdown.
n/a
n/a

Hotfix: remove NC from network select

---

package-lock.json
package.json

Accidentally force merged a PR where the lock version wasn't updated, this PR rectifies that.
n/a
n/a

chore: Bump version

---

src/components/cards/MyWalletTokensCard/MyWalletTokensCard.vue
src/components/contextual/pages/pool/PoolActionsCard.vue
src/components/navs/AppNav/AppNavNetworkSelect.vue
src/composables/contextual/pool-transfers/usePoolTransfersGuard.ts
src/pages/pool/add-liquidity.vue
src/plugins/router/index.ts
src/plugins/router/nav-guards.ts

Replaces old 'invest' terminology in route with add-liquidity. This PR does not address component naming which is a much bigger task.
n/a

chore: Replace /invest with /add-liquidity route

---

package-lock.json
package.json
src/components/pool/branded-redirect/constants.ts
src/constants/pools.ts
src/locales/default.json

Hotfix version of https://github.com/balancer-labs/frontend-v2/pull/2956

hotfix: fx mainnet support

---

src/components/contextual/pages/pool/PoolActionsCard.vue
src/components/contextual/pages/pool/PoolDeprecatedWarning.vue
src/components/contextual/pages/pool/index.ts
src/components/contextual/pages/pool/staking/StakingIncentivesCard.vue
src/components/pool/PoolWarningTooltip.vue
src/composables/usePool.ts
src/constants/pools.ts
src/locales/default.json
src/pages/pool/_id.vue

Copy of https://github.com/balancer-labs/frontend-v2/pull/2831

feat: add great migration

---

README.md
package-lock.json
package.json
public/data/vebal-gauge.json
src/components/navs/AppNav/AppSidebar/SidebarContent.vue
src/components/pool/__mocks__/sample-pool.json
src/components/pool/__mocks__/sample-title-tokens.json
src/constants/tokenlists.ts
src/data/voting-gauges.json
src/lib/scripts/voting-gauge.generator.ts
src/services/claim/MultiTokenClaim.json
tests/test-tokenlists.json
tests/tokenlists/tokens-5.json

Replaces all references to old github handle.

chore: Replace references to Github balancer-labs handle

---

Dockerfile
package-lock.json
package.json

Fixes dockerfile build command so action should pass.

chore: Fix docker build

---

package-lock.json
package.json
src/providers/tokens.provider.ts

On swaps page, My Tokens card spins as loading when no wallet is connected. I'm not very familiar with `vuequery` and if this is the correct approach, but this fixes. If we want to use a similar pattern on all other queries I can update those as well.

fix my tokens card flashing as loading when no wallet connected

---

package-lock.json
package.json
src/components/contextual/pages/vebal/LMVoting/GaugesTable.spec.ts
src/components/contextual/pages/vebal/LMVoting/GaugesTable.vue
src/composables/usePool.ts
src/composables/useVotingGauges.ts
src/constants/pools.ts

Uses pool metadata in vebal table.
Check pool names are used in verbal table.
n/a

Hotfix: vebal table names

---

.github/workflows/checks.yml
.github/workflows/docker.yml
.github/workflows/tag.yml

Update deprecated github actions. 

Chore: Bump github actions

---

package-lock.json
package.json

Chore: Update vitest to v0.29.2

---

src/components/_global/BalBtn/BalBtn.vue
src/components/_global/BalBtn/button-options.js
src/components/contextual/pages/vebal/LMVoting/GaugesTable.vue

Refactor BalBtn to script setup and simplify button-color code. 

Refactor BalBtn to script setup

---

package-lock.json
package.json
src/components/contextual/pages/claim/LegacyClaims.vue
src/composables/queries/useQueryHelpers.ts
src/composables/queries/useUserClaimsQuery.ts
src/constants/queryKeys.ts
src/lib/config/arbitrum.json
src/lib/config/homestead.json
src/lib/config/index.ts
src/lib/config/polygon.json
src/pages/claim/legacy.vue
src/services/claim/MerkleOrchardV1Config.json
src/services/claim/MerkleOrchardV2Config.json
src/services/claim/claim.service.ts

Introduces two merkle orchard configs, V1 & V2, and duplicates the legacy claims widget to support both versions.
Replaces #2739
n/a

Hotfix: legacy claims

---

package-lock.json
package.json
src/composables/queries/usePoolsQuery.ts
src/services/balancer/api/entities/pools/query.ts
src/services/balancer/subgraph/entities/pools/query.ts

Lower min total shares (Develop Merge)

---

src/composables/approvals/useRelayerApproval.ts
src/services/web3/wallet-names.ts

feat: approval tx for walletconnect

---

package-lock.json
package.json
src/components/navs/AppNav/AppNavNetworkSelect.vue

Re-add Gnosis Chain to network select options.
n/a

Chore: re-add Gnosis Chain option

---

package-lock.json
package.json
src/constants/pools.ts

Add Polygon Balancer Tetu Boosted StablePool (bb-t-USD) to allow list (develop merge)

---

package-lock.json
package.json
src/composables/usePool.ts

Add bb-t-usd pool to isDeep list to be able to join with the main tokens

---

package-lock.json
package.json

Original https://github.com/balancer/frontend-v2/pull/3027

Release 1.93.0 (develop merge)

---

package-lock.json
package.json
src/components/forms/pool_actions/MigrateForm/MigrateForm.vue

hotfix: infinite loading of migration card

---

package-lock.json
package.json
src/constants/voting-gauge-pools.ts
src/data/voting-gauges.json

Add Gauges to UI (Develop Merge)

---

package-lock.json
package.json
src/constants/pools.ts

Hotfix: add tetu metadata

---

src/assets/css/global/all.css
src/components/footer/Footer.vue
src/components/web3/WalletSelectModal.vue
src/locales/default.json
src/pages/_layouts/ContentLayout.vue
src/pages/risks.vue
src/plugins/router/index.ts
src/plugins/router/nav-guards.ts
src/services/meta/meta.constants.ts

A page to outline risks for LPs on the Balancer Protocol.
Go to the new page at /#/risks (also found in the footer) and make sure it displays well across different screen sizes.
View the two links:
- In the footer
- On the Connect Wallet screen.
One important change to test is the scroll behavior across the app. I made a change to the `scrollBehavior` function in `src/plugins/router/index.ts`, in order to enable normal functioning on anchor links which currently don't seem to work across the site. Please review this code.

Create a protocol risks page

---

package-lock.json
package.json

Release 1.94.0 (DM)

---

package-lock.json
package.json
src/constants/pools.ts
src/lib/balancer.sdk.ts

add ankrmatic to whitelist (DM)

---

package-lock.json
package.json
src/composables/queries/useTokenPricesQuery.spec.ts
src/dependencies/balancer-sdk.mocks.ts
src/providers/tokens.provider.spec.ts
tests/unit/builders/address.ts

Updates to the lastest version of vitest and improves an existing test.

Bump vitest 0.29.7

---

package-lock.json
package.json
src/composables/usePool.ts
src/constants/pools.ts

Add tetu boosted MATIC pool to allow list.
The pool should be visible at https://app.balancer.fi/polygon#/polygon/pool/0x10b040038f87219d9b42e025e3bd9b8095c87dd9000000000000000000000b11

Add tetu boosted MATIC pool to allow list.

---

package-lock.json
package.json
src/composables/swap/useJoinExit.ts
src/providers/tokens.provider.ts

There is a bug with typing small amount (e.g 0.01) in token input on swap page and setting amount to max. this pr fixes this

hotfix: token input bug

---

src/components/cards/GradientCard/GradientCard.vue

Removed final s from gradient image path (typo)

fix: gradient image path

---

src/components/contextual/pages/pool/PoolCompositionCard/PoolCompositionCard.vue
src/components/contextual/pages/pool/PoolCompositionCard/components/TokenBreakdown.vue
src/components/pool/PoolPageHeader.vue
src/pages/risks.vue

- Update the pool composition for better readability of deep nested pools.
- As pool levels go deeper, update typography to lessen in weight, add background colors, reduce size of token icons.
- Fix small screen layout bugs where text in tables was overlapping
- Fix Pool page header where tokens were not wrapping on small screens which broke horizontal layouts
Test for the changes outlined here:

Pool composition table styles

---

package-lock.json
package.json
src/composables/usePool.ts
src/constants/pools.ts

Hotfix: tetu boosted matic redeployment

---

package-lock.json
package.json
src/pages/index.vue
src/plugins/router/index.ts

Temporarily disables access to pool creation UI.
n/a

Hotfix: Temp disable pool creation UI

---

package-lock.json
package.json
src/pages/pool/create.vue
src/plugins/router/index.ts

Adds temporary pool creation warning

hotfix: pool creation warning

---

src/lib/config/mainnet/pools.ts

feat: add pool name for bbma usd pool

---

package-lock.json
package.json

Release 1.96.0 (DM)

---

package-lock.json
package.json
src/lib/config/arbitrum/pools.ts

Removes pool warning from new pool.

Fix: pool warning

---

src/components/tables/PoolsTable/PoolsTable.vue

Added new data-testid to simplify pool selection in e2e tests-

Add data-testid to pool rows to simplify e2e test selectors

---

package-lock.json
package.json
src/services/block/block.service.ts

Release 1.97.0 (DM)

---

src/components/_global/BalRadio/BalRadio.vue
src/components/web3/WalletSelectModal.vue
src/constants/local-storage.keys.ts

feat: add rules checkbox on wallet select

---

src/composables/usePoolHelpers.spec.ts
src/composables/usePoolHelpers.ts
tests/unit/builders/pool.builders.ts

This is a preparatory PR that adds some helper functions (and its tests) that will be used by [PR](feat/generalized-join-exit) 
- [] New feature (non-breaking change which adds functionality)

add new pool helpers: isComposableStable, tokenWeight and joinTokens

---

src/components/layouts/Col2Layout.vue

Extract from https://github.com/balancer/frontend-v2/pull/3044, adds a new component for controlling 2 column layouts.
Not used yet.

feat: Add new component for controlling 2 column layouts

---

src/constants/symbol.keys.ts
src/providers/local/user-tokens.provider.spec.ts
src/providers/local/user-tokens.provider.ts

Extract from #3044, adds a user tokens provider for access to functionality related to tokens in a user's connected wallet.
Not used yet.

feat: Add user tokens provider

---

package-lock.json
package.json
src/lib/config/goerli/pools.ts

Add pool ID to allowlist. Pool id is 0xbb372d299cc1afa14d5b8691ced1486fa0216f74000200000000000000000757.

update pool whitelist 

---

package-lock.json
package.json
src/lib/config/gnosis-chain/pools.ts

Adds the newly created BAL WETH GNO exDAI pool on Gnosis Chain to the AllowList. See pool: https://app.balancer.fi/#/gnosis-chain/pool/0xa99fd9950b5d5dceeaf4939e221dca8ca9b938ab000100000000000000000025

Adds new BAL WETH GNO wxDAI pool to AllowList

---

package-lock.json
package.json
src/components/contextual/pages/pool/PoolMigrationCard/PoolMigrationCard.vue
src/lib/config/mainnet/pools.ts
src/lib/config/polygon/pools.ts
src/locales/default.json
src/types/pools.ts

hotfix: add migration addresses

---

src/dependencies/balancer-sdk.mocks.ts
src/services/balancer/pools/exits/handlers/exact-out-exit.handler.ts
src/services/balancer/pools/exits/handlers/recovery-exit.handler.spec.ts
src/services/balancer/pools/exits/handlers/recovery-exit.handler.ts

This PR adds recovery-exit.handler with 100% test coverage. 
It is an extract of #3044.

Add recovery-exit handler

---

package-lock.json
package.json

Hotfix: Bump sdk

---

src/dependencies/balancer-sdk.mocks.ts
src/lib/utils/index.ts
src/services/balancer/pools/joins/handlers/exact-in-join.handler.spec.ts
src/services/balancer/pools/joins/handlers/exact-in-join.handler.ts
tests/unit/builders/pool.builders.ts

This is an extract of #3044 
It adds the new exact-in handler with test coverage.

Add new exact-in join handler

---

src/components/contextual/pages/pool/staking/StakePreview.vue
src/components/contextual/pages/pool/staking/StakingIncentivesCard.vue
src/components/pool/PoolPageHeader.vue
src/lib/config/polygon/index.ts
src/locales/default.json
src/pages/pool/_id.vue

Add restake btn in staking incentives card, and fix texts in restake flow notifications

feat: add restake btn in staking incentives card

---

package-lock.json
package.json
src/lib/config/mainnet/pools.ts
src/lib/config/polygon/pools.ts
src/locales/default.json

hotfix: add polygon pool migration addresses

---

package-lock.json
package.json
src/lib/config/gnosis-chain/pools.ts

Changes the AGVE-GNO pool id to lower case in the whitelist.

Fix case of pool ID

---

package-lock.json
package.json
src/lib/config/arbitrum/pools.ts
src/lib/config/mainnet/pools.ts

update pool metadata (DM)

---

package-lock.json
package.json

Release 1.98.0 (DM)

---

src/composables/approvals/useTokenApprovals.ts
src/composables/queries/useAllowancesQuery.ts
src/composables/queries/usePoolsQuery.spec.ts
src/providers/__mocks__/tokens.provider.fake.spec.ts
src/providers/__mocks__/tokens.provider.fake.ts
src/providers/tokens.provider.ts
src/services/rpc-provider/static-json-rpc-batch-provider.ts
src/services/token/token.service.ts

Instead of copy-pasting, `tokens.provider.fake` now extends the original provider so that we don't need to duplicate future `tokens.provider` changes.
We are also enforcing that the consumers of `TokensService` explicitly instantiate `new TokensService()` so that it is always possible to inject a mock version of rpc-provider service in related tests.

Refactor fake tokens.provider

---

package-lock.json
package.json
src/lib/config/polygon/pools.ts

Add kacy/weth to withlist and increase version. Relaces #3261

Hotfix: Add Kacy/weth to allowlist

---

package-lock.json
package.json
src/plugins/router/index.ts

The create page layout was broken as a result of the join/exit architecture change. This PR fixes the reference to the focussed layout it should have been using.

Hotfix: create page layout

---

package-lock.json
package.json
src/components/web3/WalletSelectModal.vue
src/composables/useUserAgent.ts

hotfix: hide metamask selector for ios

---

src/components/_global/BalRadio/BalRadio.vue
src/pages/_layouts/ContentLayout.vue
src/pages/risks.vue

Two changes:
- New risks added for Composable Stable Pools
- Improve the visibility of radio buttons in dark mode
Current dark mode radio button for Accept terms:
New dark mode radio button:

UX details

---

package-lock.json
package.json

💯 Release 1.100.0 (DM)

---

package-lock.json
package.json
src/lib/config/mainnet/pools.ts

Add pool [UZD/bb-a-usd pool](https://app.balancer.fi/#/ethereum/pool/0xec3626fee40ef95e7c0cbb1d495c8b67b34d398300000000000000000000053d) to stable allowlist

Hotfix: Add pool uzd/bb-a-usd to stable allowlist

---

package-lock.json
package.json
src/lib/config/mainnet/pools.ts

Hotfix: add BaoUSD-LUSD StablePool mainnet 

---

package-lock.json
package.json
src/components/contextual/pages/pool/staking/StakingIncentivesCard.vue

hotfix: add unstake btn in restake flow

---

package-lock.json
package.json
src/components/web3/WalletSelectModal.vue
src/composables/useUserAgent.ts
src/composables/useWalletHelpers.ts
src/services/web3/connectors/metamask/metamask.connector.ts

- Refactors user agent / wallet connector helpers into composables
- Fixes logic around hiding connectors.

Hotfix: metamask connector logic

---

package-lock.json
package.json
src/composables/useTransactionErrors.ts
src/services/web3/transactions/concerns/contract.concern.ts
src/services/web3/transactions/concerns/raw.concern.ts
src/services/web3/transactions/concerns/transaction.concern.ts

Hotfix: Don't send user rejected errors to Sentry

---

package-lock.json
package.json
src/lib/config/arbitrum/pools.ts

Hotfix: add pool to allowlist

---

package-lock.json
package.json
src/components/contextual/pages/vebal/LMVoting/LMVoting.vue

Remove intersection observer on vebal table, as it doesn't work correctly. meanwhile investigate if there are any quick fixes to optimise vebal table render

hotfix: remove intersection observer on vebal table

---

.github/workflows/tag.yml
package-lock.json
package.json

Hotfix: Revert auto bump change in tag action

---

package-lock.json
package.json
src/services/web3/connectors/trustwallet/wallet-connect-provider.js
src/services/web3/connectors/trustwallet/walletconnect.connector.ts
vite.config.ts

Release 1.101.0 (DM)

---

package-lock.json
package.json
src/App.vue
src/components/chips/BoostedChip.vue
src/components/contextual/pages/pool/PoolActionsCard.vue
src/components/contextual/pages/pool/PoolContractDetails.vue
src/components/contextual/pages/pool/PoolTransactionsCard/InvestmentTransactions/InvestmentTransactions.vue
src/components/contextual/pages/pool/risks/PoolRisks.vue
src/components/links/ApyVisionPoolLink.vue
src/components/tables/PoolsTable/PoolsTableExtraInfo.vue
src/locales/default.json
src/pages/pool/_id.vue

Release/1.102.0 (DM)

---

src/components/contextual/pages/pools/StakedPoolsTable.vue
src/components/contextual/pages/pools/UnstakedPoolsTable.vue
src/components/tables/PoolsTable/PoolsTable.vue

Hide volume column in portfolio pool pages

Hide volume column in portfolio pool pages

---

package-lock.json
package.json
src/services/balancer/gauges/gauges.decorator.ts

fix claimable rewards crash (DM)

---

package-lock.json
package.json
src/lib/config/polygon/pools.ts

Whitelist paxg pool (DM)

---

package-lock.json
package.json
src/components/cards/CreatePool/PoolSummary.vue
src/pages/pool/create.vue

Hotfix: pool creation add token bug

---

package-lock.json
package.json
src/lib/config/mainnet/pools.ts

add sWETH pool to whitelist (DM)

---

package-lock.json
package.json

Weekly Release 1.103.0 (Develop Merge)

---

src/components/tables/GaugeRewardsTable.vue

If a gauge has reward tokens that are not ERC20s then it breaks the gauge reward table. This PR accounts for this exception and ensures they're not displayed as a reward token.

Hotfix: Account for bad reward tokens

---

.github/workflows/tag.yml
package-lock.json
package.json

Bumptag is failing and needs more work, see failed actions, reverting for now.

Hotfix: remove bump tag

---

package-lock.json
package.json

chore: Bump vitest to 0.31.4

---

.github/workflows/checks.yml
.github/workflows/tag.yml

Removes version check and cleans up BumpTag action.

Hotfix: remove version check

---

src/components/contextual/pages/vebal/LMVoting/GaugesTable.vue

Fix: Remove debug html

---

src/components/contextual/pages/vebal/cross-chain-boost/CrossChainBoostCards.vue
src/components/contextual/pages/vebal/cross-chain-boost/CrossChainSyncModal.vue
src/components/contextual/pages/vebal/cross-chain-boost/SyncNetworkAction.vue
src/components/contextual/pages/vebal/cross-chain-boost/SyncSelectNetwork.vue
src/composables/queries/useCrossChainNetwork.ts
src/providers/cross-chain-sync.provider.spec.ts
src/providers/cross-chain-sync.provider.ts

Extracting common logic to `useCrossChainNetwork` reduces complexity and duplication and, now, adding a new network does not require modifying the existing code (Open-Closed principle).

Refactor: extract useCrossChainNetwork

---

.github/workflows/tag.yml
package-lock.json
package.json
src/components/contextual/pages/vebal/LMVoting/GaugesTable.vue

Fix bumptag (DM)

---

package-lock.json
package.json
src/composables/usePoolHelpers.spec.ts
src/composables/usePoolHelpers.ts
src/lib/config/polygon/pools.ts

Update isdeep list and fix xave link

---

src/lib/config/mainnet/pools.ts

Update ComposableStable factory address in config.

Update ComposableStable factory address in config

---

package-lock.json
package.json
src/lib/config/arbitrum/pools.ts
src/lib/config/gnosis-chain/pools.ts
src/lib/config/mainnet/pools.ts

Release 1.106.0 (DM)

---

package-lock.json
package.json
src/dependencies/balancer-sdk.mocks.ts
src/services/balancer/pools/exits/handlers/swap-exit.handler.ts
src/services/balancer/pools/joins/handlers/swap-join.handler.ts

SDK Update that fixes some issues when routing through multiple hops on L2's (Gnosis wstETH -> USDC and zkEVM wstETH -> USDC)
- Test swapping wstETH -> USDC on Gnosis and ensure it finds a good swap path
- Test swapping wstETH -> USDC on zkEVM and ensure it finds a good swap path

Update SDK to support better SOR routes

---

package-lock.json
package.json
src/lib/config/polygon/keys.ts
src/lib/config/zkevm/keys.ts

Hotfix/switch polygon keys (DM)

---

src/components/contextual/pages/vebal/cross-chain-boost/SyncNetworkAction.vue
src/composables/queries/useCrossChainNetwork.ts
src/providers/cross-chain-sync.provider.ts

There was a problem of multiple localstorage set when user submitted sync tx, which led to ui freeze

feat: prevent ui freeze on submit sync tx

---

src/components/contextual/pages/pool/PoolMigrationCard/PoolMigrationCard.vue
src/lib/config/mainnet/pools.ts
src/locales/default.json
src/types/pools.ts

Hotfix: add migration announcement

---

src/data/voting-gauges.json

@zekraken-bot Added these pools and gauges in #3563 but that was for a merge into develop. So I cherry picked the commits to merge them into master for now.

Weekly Gauge Updates

---

.github/workflows/allowlist.yml

Just adding the pool info + network to the commit message for allowlisting so it's easier to parse what the commits mean in the future.

Minor change to Allowlist message

---

src/components/contextual/pages/pools/ZkevmPromo.vue

Updated promo message about BAL incentives going live
It should now look like this:

Updated Polygon zkEVM promo message

---

src/components/contextual/pages/pools/ZkevmPromo.vue

Fix zkEVM promo wording

---

src/lib/config/mainnet/pools.ts

Add LE/WETH as per the [how-to](https://github.com/balancer/frontend-v2/wiki/How-tos#add-a-new-pool).
More information about leNFT can be found [here](https://lenft.fi/).

Add LE/WETH to Weighted.Allowlist array

---

src/composables/swap/useSor.ts

Fixes https://balancer-labs.sentry.io/share/issue/25a25924306642c092da4100eb07f3d8/

fix: Make sure deltas returned from SDK have a value

---

src/locales/default.json

chore: update wording

---

package-lock.json
package.json
src/components/contextual/pages/vebal/cross-chain-boost/CrossChainBoostCards.vue
src/components/contextual/pages/vebal/cross-chain-boost/SyncFinalState.vue
src/components/contextual/pages/vebal/cross-chain-boost/SyncNetworkAction.vue
src/providers/cross-chain-sync.provider.ts

feat: add layer zero tx link

---

src/composables/useTransactionErrors.ts

Add additional check for uncaught scenario:
https://balancer-labs.sentry.io/share/issue/01aab219dfcb4fd0a81c004420d38735/

Add additional canceled check

---

package-lock.json
package.json

chore: Bump SDK, removes warnings from console

---

src/components/contextual/pages/vebal/cross-chain-boost/StakingCardSyncAlert.vue

feat: no fetch gauge working balance if no staked shares

---

src/constants/local-storage.keys.ts
src/pages/index.vue

See title.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1204800491557403

feat: Store chosen sort column in local storage

---

src/composables/useTransactionErrors.ts

Add check for user rejected signing.

---

package-lock.json
package.json

Fixes issue with BAL#998 errors: https://balancer-labs.sentry.io/issues/2999209081/events/f706df24364f4e48922775da85e33074/

chore: bump sdk

---

package-lock.json
package.json
src/components/_global/BalAsset/BalAsset.vue
src/pages/index.vue
vite.config.ts

- image optimisations
- image lazy loading

Chore: bundle optimizations

---

src/plugins/sentry.ts

This is probably too general an ignore statement, reverts commit 4adbe639f371b35c5817469608dbc79427903c9e.

Revert "chore: Igrnore specifc sentry error"

---

src/components/pool/PoolPageHeader.vue

hotfix: remove restake warning for fx pools

---

src/components/_global/BalActionSteps/BalActionSteps.vue
src/components/contextual/pages/pool/staking/composables/useStakePreview.spec.ts
src/components/contextual/pages/pool/staking/composables/useStakePreview.ts
src/components/forms/pool_actions/AddLiquidityForm/components/AddLiquidityPreview/components/Actions.vue
src/components/forms/pool_actions/WithdrawForm/components/WithdrawPreviewModal/components/WithdrawActions.vue
src/composables/useNetwork.ts
src/composables/useTransactions.ts

fix: zkevm tx confirmation callback (DM)

---

src/services/balancer/pools/joins/handlers/generalised-join.handler.ts

fix: simulation type if native asset join

---

src/components/contextual/pages/vebal/LMVoting/LMVoting.vue

Fix bug with vebal list render 

fix: vebal list render

---

src/components/_global/BalActionSteps/BalActionSteps.vue

fix: action step change delay in tx flow

---

src/composables/useTransactions.ts
src/lib/utils/balancer/helpers/sor/sorManager.ts
src/lib/utils/errors.ts

Make fetch pools errors fatal

---

src/lib/utils/errors.ts
src/services/contracts/vault.service.spec.ts
src/services/contracts/vault.service.ts
src/services/web3/transactions/concerns/contract.concern.ts
src/services/web3/transactions/concerns/raw.concern.ts
src/types/index.ts

Add sentry metadata to error rather than logging errors in contract.concern and raw.concern

---

package-lock.json
package.json

Release 1.114.0 (dm)

---

src/components/_global/BalActionSteps/BalActionSteps.vue
src/lib/utils/errors.ts

fix: Original error recording (dm)

---

package-lock.json
package.json
src/components/_global/BalActionSteps/BalActionSteps.vue
src/lib/config/mainnet/pools.ts
src/lib/utils/errors.ts

Hotfix: idle/usdc whitelist (dm)

---

src/components/cards/SwapCard/SwapCard.vue
src/components/modals/SwapPreviewModal.vue
src/composables/approvals/types.ts
src/composables/approvals/useTokenApprovalActions.ts
src/composables/swap/useSwapping.ts
src/lib/utils/balancer/lido.ts
src/locales/default.json

Hotfix: Add approval check to swap (dm)

---

package-lock.json
package.json

chore: Bump wc modal

---

package-lock.json
package.json

chore: Bump wc modal (dm)

---

src/lib/utils/errors.ts

Add metadata action as tag

---

src/lib/config/mainnet/pools.ts

This PR is adding the 80RATE/20WETH  pool to the weighted pool allow list. Test by ensuring the UI allows provisioning liquidity to it. 

Adding 80RATE/20WETH pool to weighted allowlist

---

src/lib/utils/errors.ts

Adds additional checks for user-rejected transactions.

Hotfix: Improve user rejected check

---

package-lock.json
package.json

Tested in dev and zkEVM is working correctly now

Update SDK to fix fetchPools errors

---

src/lib/utils/errors.spec.ts
src/lib/utils/errors.ts

Ignoring a bunch of user errors that showed up in the last day.

Hotfix - Ignore more user errors

---

src/components/contextual/pages/pool/PoolLockingCard/PoolLockingCard.vue
src/components/forms/pool_actions/AddLiquidityForm/components/AddLiquidityPreview/components/Actions.vue
src/components/tables/PoolsTable/PoolsTableActionsCell.vue

Some links to the vebal lock form page were not being properly constructed.

fix: Lock route links

---

src/lib/utils/errors.ts

Add user cancelled filter

---

src/services/balancer/pools/exits/handlers/exact-in-exit.handler.ts
src/services/balancer/pools/exits/handlers/exact-out-exit.handler.ts

Add additional logging on exit error.

---

src/components/forms/pool_actions/AddLiquidityForm/AddLiquidityForm.vue

Add liquidity - clear amount when changing token

---

src/components/forms/pool_actions/AddLiquidityForm/AddLiquidityForm.vue

Hotfix: Add liquidity - clear amount when changing token (dm)

---

src/components/forms/pool_actions/AddLiquidityForm/AddLiquidityForm.vue
src/components/inputs/TokenInput/TokenInput.vue

fix: Selected token in add liquidity form (dm)

---

src/components/cards/CreatePool/CreateActions.vue
src/components/cards/CreatePool/PreviewPool.vue
src/components/inputs/TokenInput/TokenInput.vue
src/components/inputs/TokenSelectInput/TokenSelectInput.vue

- [fix: Prevent any kind of negative input in TokenInput](https://github.com/balancer/frontend-v2/commit/58f4e59d8b47b17c683610867051be3b695af495)
- [chore: Minor style fix in TokenSelectInput](https://github.com/balancer/frontend-v2/commit/aaa138ac317748055714c5251a025a1f5940a5ea)
- [fix: Prevent pool creation before approval actions have loaded](https://github.com/balancer/frontend-v2/commit/0d9bebe152fd3b96c94a494959c09068bcb54ac1)
- [fix: Prevent pool creation if wallet on wrong network](https://github.com/balancer/frontend-v2/pull/3804/commits/b0d183efa02babac67feacdfb8311a8d9ca1ec51)

fix: Multiple minor fixes

---

src/components/inputs/TokenInput/TokenInput.vue
src/lib/config/arbitrum/pools.ts
src/locales/default.json

Adds pool migration notices to Arbitrum pools:
0xcba9ff45cfb9ce238afde32b0148eb82cbe635620000000000000000000003fd -> 0xbe0f30217be1e981add883848d0773a86d2d2cd4000000000000000000000471
0xee02583596aee94cccb7e8ccd3921d955f17982a00000000000000000000040a -> 0xc6eee8cb7643ec2f05f46d569e9ec8ef8b41b389000000000000000000000475
0x5a7f39435fd9c381e4932fa2047c9a5136a5e3e7000000000000000000000400 -> 0x45c4d1376943ab28802b995acffc04903eb5223f000000000000000000000470
0x567ecfcb22205d279bb8eed3e066989902bf03d5000000000000000000000452 -> 0xbbf9d705b75f408cfcaee91da32966124d2c6f7d00000000000000000000047e

chore: Add pool migration notices

---

src/lib/utils/errors.ts

Add cancelled to user rejection messages

fix: Add cancelled to user rejection messages

---

index.html

Suggested by lighthouse: https://developer.chrome.com/docs/lighthouse/performance/uses-rel-preconnect/

chore: Test preconnect links

---

src/lib/config/mainnet/pools.ts

Support branded redirect card for gyro pools on mainnet

Hotfix: gyro card on mainnet

---

package-lock.json
package.json

Bump sdk to improve Avax routing.
- [] Bug fix (non-breaking change which fixes an issue)

fix: bump-sdk to improve Avax routing

---

package-lock.json
package.json

Small update that adds the base blocks subgraph to the SDK.

Update SDK to add Blocks subgraph for Base

---

src/lib/config/base/index.ts

Updates Base RPC to use tenderly.

Hotfix: Update Base RPC

---

src/lib/config/avalanche/contracts.ts
src/lib/config/base/contracts.ts

Hotfix: Add vebal delegation proxy addresses for Base & Ava

---

.github/workflows/allowlist-manual.yml
src/lib/scripts/automatic-prs/allowlist-pool.ts

Our allowlist github action was missing some chains. 

Include missing chains in allowlist actions

---

.github/workflows/allowlist-manual.yml
src/lib/scripts/automatic-prs/allowlist-pool.ts

Add missing chains to allowlist script

Add missing chains to allowlist script

---

src/lib/config/polygon/pools.ts

Hotfix: Add migration notice to polygon pool

---

src/lib/config/zkevm/contracts.ts

hotfix: fix BAL claiming on zkEVM

---

src/lib/config/base/pools.ts

fix: disable boosts in base

---

src/lib/config/mainnet/pools.ts
src/lib/config/polygon/pools.ts

chore: Add migration notices

---

src/lib/config/base/pools.ts

Allowlist rETH/WETH pool on base

---

src/lib/utils/errors.ts

fix: ignore lack of native asset error

---

src/lib/utils/errors.ts

Ignore intermittent wallet connect v2 errors:
https://github.com/WalletConnect/walletconnect-monorepo/issues/2326
https://github.com/WalletConnect/walletconnect-monorepo/issues/1772

Ignore wallet connect v2 matching key errors

---

src/lib/utils/errors.ts

Ignores `unknown account #0` in sentry but shows error in the UI. 

Handle unknown account #0 error

---

src/composables/useDisabledJoinPool.spec.ts
src/composables/useDisabledJoinPool.ts

Hotfix: allow all tokens on testnet (DM)

---

src/pages/recovery-exit/recovery-exit.vue

hotfix: Add network alert to recovery page

---

src/pages/recovery-exit/components/TokenUnwrapTable.vue

hotfix: Allow token exclusions from unwrap list

---

src/constants/pool-lists/csp-issue.ts

hotfix: Add pool to no recovery exit list

---

src/components/contextual/pages/vebal/LMVoting/GaugesTable.vue
src/composables/usePoolHelpers.ts

See title.
https://github.com/balancer/frontend-v2/assets/1316240/f5aa0efb-19cb-49a5-a5ff-6def85f555eb

feat: add CLP chip to gyro pools in vebal voting list

---

src/components/modals/SelectTokenModal/SelectTokenModal.vue

chore: Remove tokenlist options from tokens select modal

---

package-lock.json
package.json

Update SDK. Adds connecting pools for Arb USDC<>auraBal/aura
On swaps for Arbitrum can see results for USDC<>aura/auraBAL trades where they didn't previously exist.

Bump SOR. Open Arb routes for Aura/AuraBAL<>USDC.

---

src/services/balancer/contracts/contracts/fee-distributor.ts

hotfix: make usdc claimable

---

src/composables/pools/usePools.ts
src/composables/queries/usePoolsQuery.ts

Minor optimisations for pool list loading.
- Removes await for token injection (not sure if this actually makes a difference)
- Prevents token injection happening twice.

chore: minor optimisations

---

src/pages/pool/create.vue

hotfix: Remove create pool popup

---

src/components/tables/PoolsTable/PoolsTableActionSelector.vue

hotfix: remove stake and migrate actions for branded redirect pools

---

src/components/contextual/pages/vebal/cross-chain-boost/StakingCardSyncAlert.vue

hotfix: prevent sync modal open if user not staked

---

src/services/rpc-provider/rpc-provider.service.spec.ts
src/services/rpc-provider/rpc-provider.service.ts

hotfix: Minor RPC init optimization (dm)

---

src/components/contextual/pages/pools/StakedPoolsTable.vue
src/composables/queries/useUserBoostsQuery.spec.ts
src/lib/utils/errors.ts
src/services/staking/staking-rewards.service.ts
src/services/token/concerns/balances.concern.ts

Release 1.125.0

---

package-lock.json
package.json

Forgot to update version in weekly release.

Tag 1.125.0

---

package-lock.json
package.json

Tag/1.125.0 (dm)

---

src/components/tables/PoolsTable/PoolsTableActionSelector.vue

feat: remove stake action if pool is not stakable

---

package-lock.json
package.json

Release 1.126.0 (dm)

---

package-lock.json
package.json

Bump SDK (re-adds GyroE V2 mainnet) (dm)

---

src/components/contextual/pages/vebal/LMVoting/LMVoting.vue

fix: disable voting if network is mismatched

---

package-lock.json
package.json

Hotfix: bump to 1.127.0

---

package-lock.json
package.json

Bump ethereum-provider

---

src/components/navs/AppNav/AppNavNetworkSelect.vue

feat: remove new tag from base and avax in networks selector

---

src/components/tables/PoolsTable/PoolsTable.vue

Just checking if make sense to make them a bit more prominent.

chore: Make pool list icons bigger

---

src/plugins/router/index.ts

Avoid capturing sentry errors as we won't be able to fix this problem until vite team releases an official solution.
In the meantime, we will keep on reloading the page when this error happens (this PR added another case when it happened with css imports).
Context:
https://github.com/vitejs/vite/issues/11804#issuecomment-1760951463

Improve dynamic import error handling

---

src/lib/utils/errors.ts

chore: Add BAL#505 as a slippage error

---

src/pages/claim-submissions.vue

Adds Optimism to claim submission options.

chore: Add OP to claim options

---

src/lib/config/zkevm/pools.ts

hotfix: add pool composable stable factory address on zkevm

---

src/lib/config/optimism/index.ts
src/lib/config/optimism/pools.ts

feat: Enable OP

---

src/components/web3/WalletButton.vue
src/providers/wallet.provider.ts

- Remove tally
- Fix WC icon aspect ratio

chore: Update wallet connect modal

---

src/lib/config/zkevm/pools.ts

- Adds mapping for gyro pool titles
- Adds branded redirect for gyro pools on zkevm

chore: Add zksync pool title for Gyro pools

---

src/composables/usePoolHelpers.ts
src/providers/local/exit-pool.provider.ts

fix: Ensure single asset exits hidden for edge case (dm)

---

package-lock.json
package.json
src/composables/usePoolHelpers.ts
src/pages/index.vue
src/providers/local/exit-pool.provider.ts

fix: Token filter removal (dm)

---

src/lib/config/zkevm/pools.ts

chore: Include Gyro pools in pools list on zkEVM

---

src/components/cards/CreatePool/ChooseWeights.vue
src/components/contextual/pages/pool/PoolActionsCard.vue
src/composables/pools/usePoolCreation.ts

- Allow pool creation with unlisted tokens
- Allow joins for all pools

chore: Ease goerli restrictions

---

src/components/navs/AppNav/AppSidebar/SidebarContent.vue
src/constants/links.ts

Dune dashboards have been migrated to the Balancer team - https://dune.com/balancer

hotfix: update dune links

---

src/lib/config/arbitrum/pools.ts

Includes GyroE pool type in arbitrum pool list so that pools like this one appear in the pool list: 
https://beta-app-v2-git-chore-gyro-pool-arbitrum-balancer.vercel.app/#/arbitrum/pool/0xb6911f80b1122f41c19b299a69dca07100452bf90002000000000000000004ba

Include GyroE in pools

---

package.json

Bump vitest coverage

---

package-lock.json
package.json
src/lib/config/polygon/pools.ts

chore: bump sdk (dm)

---

src/pages/RedAlert.vue
src/pages/index.vue

Add red alert

---

.vscode/settings.json
src/pages/index.vue

We will keep the component for now until we confirm that there's no risk

Remove red alert

---

src/composables/swap/useSor.ts
src/lib/balancer.sdk.ts

fix: Overfetching sor pools (dm)

---

src/lib/config/arbitrum/rateProviders.ts

Add s frax wst eth rate providers

---

src/locales/default.json

chore: Update Xave description

---

src/components/pool/PoolPageHeader.vue

feat: add recovery and pause chip on pool page

---

package-lock.json
package.json

Fixes issue with ignoring pools in swap routes.

chore: SDK SOR fix

---

src/lib/config/mainnet/pools.ts

Update stakeable allowlist mainnet-sDAI-USDC-USDT-DAI-stakeable 0x49cbd67651fbabce12d1df18499896ec87bef46f00000000000000000000064a

Mainnet sdai usdc usdt dai stakeable

---

src/composables/swap/useCowswap.ts
src/pages/claim-submissions.vue

chore: Disable claims page

---

src/components/_global/BalDetailsTable/BalDetailsTable.vue
src/components/contextual/pages/pool/PoolContractDetails.vue
src/composables/usePoolRisks.ts
src/services/pool/types.ts

hotfix: add rate providers details

---

src/pages/pool/_id.vue
src/pages/swap.vue

Remove swap chart, and historical price fetching for tvl chart

feat: remove coingecko price fetching

---

src/lib/config/arbitrum/pools.ts

hotfix: Add branded redirect for Gyro pools on Arb

---

src/lib/config/zkevm/pools.ts

chore: Add label for new factory

---

src/components/contextual/pages/pool/PoolContractDetails.vue

See title
Please provide any relevant visual context for UI changes or additions. This could be static screenshots or a loom screencast

hotfix: add veBal gauge address

---

src/components/contextual/pages/pool/PoolContractDetails.vue

hotfix: add veBal gauge address (dm)

---

src/lib/config/mainnet/rateProviders.ts

chore: Add rsETH rate provider

---

src/lib/config/arbitrum/pools.ts
src/locales/default.json
src/types/pools.ts

See title. To be deployed on Thursday morning.

chore: Adds migration notice for rETH Arbitrum pools

---

src/lib/config/avalanche/keys.ts
src/lib/config/polygon/keys.ts

chore: update polygon key

---

src/lib/config/arbitrum/pools.ts

fix: Pool ID in metadata

---

src/lib/config/mainnet/pools.ts

fix: add gyro factory

---

src/plugins/router/index.ts

Hotfix: Remove trade redirect

---

src/lib/config/mainnet/pools.ts

chore: update points

---

src/components/pool/PoolPageHeader.vue
src/lib/config/polygon/pools.ts

add new Fx pool factory in polygon config

---

src/lib/config/mainnet/rateProviders.ts

chore: Add rate provider to allowlist

---

src/lib/config/arbitrum/pools.ts
src/lib/config/base/pools.ts

chore: Add factory

---

src/locales/default.json

chore: Update gyro label

---

src/components/pool/branded-redirect/BrandedRedirectCard.vue
src/components/pool/branded-redirect/constants.ts
src/lib/config/base/pools.ts
src/pages/pool/_id.vue

Provides links directly to gyro pool pages.

feat: Gyro deep links

---

src/lib/config/arbitrum/pools.ts
src/lib/config/mainnet/pools.ts

chore: Update Renzo point multiples

---

src/components/cards/CreatePool/ChooseWeights.vue
src/components/contextual/pages/pool/PoolActionsCard.vue
src/composables/pools/usePoolCreation.ts

allow pool creation with unlisted tokens on sepolia

---

src/lib/config/mainnet/pools.ts

chore: update kelp points program

---

src/lib/config/gnosis-chain/pools.ts

fix unknown pool type for csp v6 on gnosis

---

src/lib/config/arbitrum/pools.ts

CSP showing as unknown pool type because factory address is not lower case.

fix csp v6 on arbitrum

---

src/lib/config/gnosis-chain/pools.ts

config gyro pools on gnosis

---

src/services/contracts/gauge-controller.service.ts

Temporary fix for a custom user to undo a 100% vote in a very old killed gauge.

Fix: old gauge vote

---

src/composables/queries/mappers.spec.ts
src/services/api/graphql/generated/api-schema.graphql
src/services/api/graphql/generated/api-types.ts
src/services/api/graphql/mappers.ts

Add FRAXTAL and MODE to voting list.

Fix: Add FRAXTAL and MODE to voting list

---

src/services/staking/staking-rewards.service.ts

This pr fixes vebal boost value on portfolio page

hf: vebal boost value on portfolio page

---

src/plugins/router/nav-guards.ts

Fixes [this edge case bug](https://discord.com/channels/638460494168064021/1279826315163205686/1279826320968388628) reported in discord.

fix: avoid edit votes reloading 

---

src/components/contextual/pages/vebal/LMVoting/GaugesTable.vue

fix: gauge cap display

---

src/lib/config/base/index.ts

chore: update base subgraph urls

---

src/lib/config/base/keys.ts

fix: add graph api key

---

.github/workflows/allowlist.yml
.github/workflows/checks.yml
package-lock.json
package.json
src/components/footer/Footer.vue
src/composables/queries/useVotingPoolsQuery.ts
src/services/api/graphql/generated/api-schema.graphql
src/services/api/graphql/generated/api-types.ts
src/services/api/graphql/voting.graphql

Adds `includeKilled: true` param to `veBalGetVotingList` query to include expired queries in voting list.

feat: include killed gauges
